### ISSUE TITLE
Liquid Exception: Failed to get header. in 2013-06-04-welcome-to-jekyll.markdown

### ISSUE THREAD

**Issue by collaboratorium** [jekyll/jekyll#1181]
I just tried to run `jekyll new website2` and then `jekyll build` and I get the error below.
I'm using jekyll version 1.0.2.
(my actual home folder path has been replaced with $HOME)

``` text
  Configuration file: $HOME/tmp/collaboratorium01/website2/_config.yml
              Source: $HOME/tmp/collaboratorium01/website2
        Destination: $HOME/tmp/collaboratorium01/website2/_site
        Generating...   Liquid Exception: Failed to get header. in 2013-06-04-welcome-to-jekyll.markdown
  $HOME/.gem/ruby/2.0.0/gems/pygments.rb-0.5.0/lib/pygments/popen.rb:357:in `rescue in get_header'
  $HOME/.gem/ruby/2.0.0/gems/pygments.rb-0.5.0/lib/pygments/popen.rb:338:in `get_header'
  $HOME/.gem/ruby/2.0.0/gems/pygments.rb-0.5.0/lib/pygments/popen.rb:235:in `block in mentos'
  /usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
  $HOME/.gem/ruby/2.0.0/gems/pygments.rb-0.5.0/lib/pygments/popen.rb:209:in `mentos'
  $HOME/.gem/ruby/2.0.0/gems/pygments.rb-0.5.0/lib/pygments/popen.rb:192:in `highlight'
  $HOME/.gem/ruby/2.0.0/gems/jekyll-1.0.2/lib/jekyll/tags/highlight.rb:57:in `render_pygments'
  $HOME/.gem/ruby/2.0.0/gems/jekyll-1.0.2/lib/jekyll/tags/highlight.rb:45:in `render'
  /usr/lib/ruby/gems/2.0.0/gems/liquid-2.5.0/lib/liquid/block.rb:106:in `block in render_all'
  /usr/lib/ruby/gems/2.0.0/gems/liquid-2.5.0/lib/liquid/block.rb:93:in `each'
  /usr/lib/ruby/gems/2.0.0/gems/liquid-2.5.0/lib/liquid/block.rb:93:in `render_all'
  /usr/lib/ruby/gems/2.0.0/gems/liquid-2.5.0/lib/liquid/block.rb:82:in `render'
  /usr/lib/ruby/gems/2.0.0/gems/liquid-2.5.0/lib/liquid/template.rb:124:in `render'
  /usr/lib/ruby/gems/2.0.0/gems/liquid-2.5.0/lib/liquid/template.rb:132:in `render!'
  $HOME/.gem/ruby/2.0.0/gems/jekyll-1.0.2/lib/jekyll/convertible.rb:77:in `render_liquid'
  $HOME/.gem/ruby/2.0.0/gems/jekyll-1.0.2/lib/jekyll/convertible.rb:128:in `do_layout'
  $HOME/.gem/ruby/2.0.0/gems/jekyll-1.0.2/lib/jekyll/post.rb:285:in `render'
  $HOME/.gem/ruby/2.0.0/gems/jekyll-1.0.2/lib/jekyll/site.rb:230:in `block in render'
  $HOME/.gem/ruby/2.0.0/gems/jekyll-1.0.2/lib/jekyll/site.rb:229:in `each'
  $HOME/.gem/ruby/2.0.0/gems/jekyll-1.0.2/lib/jekyll/site.rb:229:in `render'
  $HOME/.gem/ruby/2.0.0/gems/jekyll-1.0.2/lib/jekyll/site.rb:44:in `process'
  $HOME/.gem/ruby/2.0.0/gems/jekyll-1.0.2/lib/jekyll/command.rb:18:in `process_site'
  $HOME/.gem/ruby/2.0.0/gems/jekyll-1.0.2/lib/jekyll/commands/build.rb:23:in `build'
  $HOME/.gem/ruby/2.0.0/gems/jekyll-1.0.2/lib/jekyll/commands/build.rb:7:in `process'
  $HOME/.gem/ruby/2.0.0/gems/jekyll-1.0.2/bin/jekyll:59:in `block (2 levels) in <top (required)>'
  $HOME/.gem/ruby/2.0.0/gems/commander-4.1.3/lib/commander/command.rb:180:in `call'
  $HOME/.gem/ruby/2.0.0/gems/commander-4.1.3/lib/commander/command.rb:180:in `call'
  $HOME/.gem/ruby/2.0.0/gems/commander-4.1.3/lib/commander/command.rb:155:in `run'
  $HOME/.gem/ruby/2.0.0/gems/commander-4.1.3/lib/commander/runner.rb:402:in `run_active_command'
  $HOME/.gem/ruby/2.0.0/gems/commander-4.1.3/lib/commander/runner.rb:66:in `run!'
  $HOME/.gem/ruby/2.0.0/gems/commander-4.1.3/lib/commander/delegates.rb:7:in `run!'
  $HOME/.gem/ruby/2.0.0/gems/commander-4.1.3/lib/commander/import.rb:10:in `block in <top (required)>'
  Build Failed
```

**Comment by CharlJKruger** [comment]
had the same problem on windows 8, using the below resolved the issue

pygments.rb latest
Python 2.7.6
ruby 2.1.X 
jekyll latest

**Comment by saysmy** [comment]
I met the same problem on win7,the issue is:
ruby 2.0.0p645 (2015-04-13) [x64-mingw32]
jekyll 2.5.3
python 3.4.3

help.....

**Comment by talolard** [comment]
I had the same problem. I managed to solve it by using a vitualenv for python with python 2.7 (My default interpreter was 3.4).
Install virtualenv like so https://virtualenv.pypa.io/en/latest/installation.html
Then create a virtualenv, and pip install pygments and you should be good to go.

**Comment by shunfan** [comment]
I got the same issue when I was trying to build my Jekyll blog in my ubuntu server.
The solution that worked for me is to install python and pygments (Use pip as @talolard mentioned).
Environment:
jekyll 2.5.3
ruby 2.2.1p85
Python 2.7.9
