### ISSUE TITLE
Strange new bug: Liquid Exception: highlight tag was never closed in

### ISSUE THREAD

**Issue by SLaks** [jekyll/jekyll#1401]
This occurred after upgrading from Jekyll 1.0 to 1.1.2.

I first noticed it when my blog stopped building on GitHub pages, and I then narrowed it down to the smallest possible reproduction locally:

```

---

---
{%highlight c%}

{%endhighlight%}
```

This happens with both CRLF and LF line endings.

It looks like this happens if there is a blank line anywhere in the highlight block.  
I have also noticed cases where it happens only if there isn't a blank line immediately preceding the `{% highlight %}` tag.

For example, the error happens [here](https://github.com/SLaks/SLaks.Blog/blob/gh-pages/_posts/2010-12-17-requiring-inherited-types-in-generic.html#L25), but goes away if I delete both blank lines in the code block or if I add a blank line above the `{% highlight %}`).  For some reason, the second highlight there does not give any errors.

Trace is 

```
  Liquid Exception: highlight tag was never closed in bad.md
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.5.1/lib/liquid/block.rb:88:in `assert_missing_delimitation!': highlight tag was never close
d (Liquid::SyntaxError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.5.1/lib/liquid/block.rb:49:in `parse'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.5.1/lib/liquid/tag.rb:10:in `initialize'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/tags/highlight.rb:15:in `initialize'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.5.1/lib/liquid/block.rb:28:in `new'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.5.1/lib/liquid/block.rb:28:in `parse'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.5.1/lib/liquid/document.rb:5:in `initialize'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.5.1/lib/liquid/template.rb:58:in `new'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.5.1/lib/liquid/template.rb:58:in `parse'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.5.1/lib/liquid/template.rb:46:in `parse'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/convertible.rb:81:in `render_liquid'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/convertible.rb:129:in `do_layout'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/post.rb:258:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/site.rb:213:in `block in render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/site.rb:212:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/site.rb:212:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/site.rb:44:in `process'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/command.rb:18:in `process_site'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/commands/build.rb:23:in `build'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/lib/jekyll/commands/build.rb:7:in `process'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-1.1.2/bin/jekyll:72:in `block (2 levels) in <top (required)>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/commander-4.1.4/lib/commander/command.rb:180:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/commander-4.1.4/lib/commander/command.rb:180:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/commander-4.1.4/lib/commander/command.rb:155:in `run'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/commander-4.1.4/lib/commander/runner.rb:402:in `run_active_command'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/commander-4.1.4/lib/commander/runner.rb:78:in `run!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/commander-4.1.4/lib/commander/delegates.rb:7:in `run!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/commander-4.1.4/lib/commander/import.rb:10:in `block in <top (required)>'
```

**Comment by devoxel** [comment]
Yep, thanks for the fix about the blank line. I got it to. My excerpt separator is some html, is that the cause?
