### ISSUE TITLE
Trouble with alpha release

### ISSUE THREAD

**Issue by troyswanson** [jekyll/jekyll#2055]
I thought I'd give the alpha release a try, but after running `gem install jekyll --pre` and trying `jekyll build`, i received this error:

```
troys-mbp:troyswanson.github.io troy$ jekyll build
/Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- rouge (LoadError)
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.0.0.alpha.1/lib/jekyll/converters/markdown/redcarpet_parser.rb:41:in `<module:WithRouge>'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.0.0.alpha.1/lib/jekyll/converters/markdown/redcarpet_parser.rb:40:in `<class:RedcarpetParser>'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.0.0.alpha.1/lib/jekyll/converters/markdown/redcarpet_parser.rb:4:in `<class:Markdown>'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.0.0.alpha.1/lib/jekyll/converters/markdown/redcarpet_parser.rb:3:in `<module:Converters>'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.0.0.alpha.1/lib/jekyll/converters/markdown/redcarpet_parser.rb:2:in `<module:Jekyll>'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.0.0.alpha.1/lib/jekyll/converters/markdown/redcarpet_parser.rb:1:in `<top (required)>'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.0.0.alpha.1/lib/jekyll.rb:11:in `block in require_all'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.0.0.alpha.1/lib/jekyll.rb:10:in `each'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.0.0.alpha.1/lib/jekyll.rb:10:in `require_all'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.0.0.alpha.1/lib/jekyll.rb:61:in `<top (required)>'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/troy/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.0.0.alpha.1/bin/jekyll:6:in `<top (required)>'
    from /Users/troy/.rbenv/versions/2.0.0-p247/bin/jekyll:23:in `load'
    from /Users/troy/.rbenv/versions/2.0.0-p247/bin/jekyll:23:in `<main>'
```

As you can see from the log, I'm running rbenv with ruby version 2.0.0-p247. Unfortunately, I don't know as much as I'd like about debugging ruby apps, so any help getting this fixed up would be appreciated.

**Comment by coder5** [comment]
thanks a lot it's help me a lot
