### ISSUE TITLE
PDF and JPEG file trigger a parsing failure in lib/jekyll/site.rb:422 

### ISSUE THREAD

**Issue by dbaillon** [jekyll/jekyll#2262]
with version jekyll 2.0.0.alpha.3
Mac OS X 10.9.2

The problem is not present in version 1.5.1
I have an asset folder at the root folder which contains a cv folder when I put either a my CV in pdf or my identity picture in jpeg in this folder I got  the following exception :

Change block raised an exception: invalid byte sequence in UTF-8

with the following stack trace

```
      Regenerating: 1 files at 2014-04-26 16:55:10 [Listen warning]: Change block raised an exception: invalid byte sequence in UTF-8
Backtrace:
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/site.rb:422:in `has_yaml_header?'
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/site.rb:138:in `block in read_directories'
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/site.rb:133:in `each'
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/site.rb:133:in `read_directories'
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/site.rb:137:in `block in read_directories'
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/site.rb:133:in `each'
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/site.rb:133:in `read_directories'
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/site.rb:137:in `block in read_directories'
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/site.rb:133:in `each'
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/site.rb:133:in `read_directories'
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/site.rb:112:in `read'
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/site.rb:41:in `process'
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/command.rb:43:in `process_site'
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.0.0.alpha.3/lib/jekyll/commands/build.rb:80:in `block in watch'
    /Library/Ruby/Gems/2.0.0/gems/listen-2.7.1/lib/listen/listener.rb:149:in `call'
    /Library/Ruby/Gems/2.0.0/gems/listen-2.7.1/lib/listen/listener.rb:149:in `block in _wait_for_changes'
    /Library/Ruby/Gems/2.0.0/gems/listen-2.7.1/lib/listen/listener.rb:138:in `loop'
    /Library/Ruby/Gems/2.0.0/gems/listen-2.7.1/lib/listen/listener.rb:138:in `_wait_for_changes'
    /Library/Ruby/Gems/2.0.0/gems/listen-2.7.1/lib/listen/listener.rb:42:in `block in start'
```

The picture triggering the behavior is the following one

![photo](https://cloud.githubusercontent.com/assets/690522/2809027/08091276-cd54-11e3-8c86-5dd9ce0c7ddb.jpg)

**Comment by xushvai** [comment]
how about move image file to images dir ?
