### ISSUE TITLE
 Could not find a JavaScript runtime. (ExecJS::RuntimeUnavailable)

### ISSUE THREAD

**Issue by yizeng** [jekyll/jekyll#2327]
After upgrading to Jekyll 2.0.2 from 1.5.1, I met this issue while building [my repository](https://github.com/yizeng/yizeng.me) using `jekyll serve --trace`.

Environment:
- Linux Mint 16, Ruby 2.1.1p76, Jekyll gem 2.0.2

Stacktrace:

```
/home/yze14/.rvm/gems/ruby-2.1.1/gems/execjs-2.0.2/lib/execjs/runtimes.rb:51:in `autodetect': Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
    from /home/yze14/.rvm/gems/ruby-2.1.1/gems/execjs-2.0.2/lib/execjs.rb:5:in `<module:ExecJS>'
    from /home/yze14/.rvm/gems/ruby-2.1.1/gems/execjs-2.0.2/lib/execjs.rb:4:in `<top (required)>'
    from /home/yze14/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /home/yze14/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /home/yze14/.rvm/gems/ruby-2.1.1/gems/coffee-script-2.2.0/lib/coffee_script.rb:1:in `<top (required)>'
    from /home/yze14/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /home/yze14/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /home/yze14/.rvm/gems/ruby-2.1.1/gems/coffee-script-2.2.0/lib/coffee-script.rb:1:in `<top (required)>'
    from /home/yze14/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /home/yze14/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /home/yze14/.rvm/gems/ruby-2.1.1/gems/jekyll-coffeescript-1.0.0/lib/jekyll-coffeescript.rb:2:in `<top (required)>'
    from /home/yze14/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /home/yze14/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /home/yze14/.rvm/gems/ruby-2.1.1/gems/jekyll-2.0.2/lib/jekyll.rb:73:in `<top (required)>'
    from /home/yze14/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /home/yze14/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /home/yze14/.rvm/gems/ruby-2.1.1/gems/jekyll-2.0.2/bin/jekyll:6:in `<top (required)>'
    from /home/yze14/.rvm/gems/ruby-2.1.1/bin/jekyll:23:in `load'
    from /home/yze14/.rvm/gems/ruby-2.1.1/bin/jekyll:23:in `<main>'
    from /home/yze14/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    from /home/yze14/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

A little bit Googling told me it had something to do with Node.js. `sudo apt-get install nodejs` fixes it. I'm wondering if this is something should be handled by Jekyll installation or not (at least we might want to document it somewhere maybe?)

**Comment by welligton1993** [comment]
Add therubyracer  to Gemfile works for me...

**Comment by akoimeexx** [comment]
Incredibly irritating dependency. Building therubyracer and libv8 takes forever, but better than swamping my cell phone 'net access with node.js downloading at the moment. I don't even use sass or scss.

Looking forward to 3. =p

**Comment by stugerdt** [comment]
Lovely thread. Very helpful too.

**Comment by fernandoGN** [comment]
Install node.js work for me...

**Comment by BigOcto** [comment]
sudo apt-get install nodejs. This is useful for me

**Comment by eddiejaoude** [comment]
Install `nodejs` let me move on, now get this error...

```
`block in materialize': Could not find timers-4.0.1 in any of the sources`
```

**Comment by envygeeks** [comment]
Please ask your questions about non-direct problems on https://talk.jekyllrb.com, thanks!
