### ISSUE TITLE
'--detach' doesn't work on Windows

### ISSUE THREAD

**Issue by gligoran** [jekyll/jekyll#2512]
I've tried creating a background process for Jekyll, but the `--detach` argument throw and error on here: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/commands/serve.rb#L48

Here's the full error:

```
    C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/commands/serve.rb:48:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/commands/serve.rb:48:in `process'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/commands/serve.rb:24:in `block (2 levels) in init_with_program'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `call'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `block in execute'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `each'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `execute'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/program.rb:35:in `go'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary.rb:22:in `program'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/bin/jekyll:18:in `<top (required)>'
    from C:/Ruby200-x64/bin/jekyll:23:in `load'
    from C:/Ruby200-x64/bin/jekyll:23:in `<main>'
```

Is there any way to make this work on Windows? I'm using Windows 8.

**Comment by TWiStErRob** [comment]
You could just restart Jekyll with `Process.spawn` without `--detach` arg, `Process.detach` that and exit the current instance. Is there a reason why that wouldn't work?
