### ISSUE TITLE
Invalid Byte Sequence UTF-8 

### ISSUE THREAD

**Issue by stampedosaurs** [jekyll/jekyll#2523]
Hi! I am very new to coding and jekyll in general. I've been following this tutorial 
http://24ways.org/2013/get-started-with-github-pages/
to create a website using github.
I am getting this error when I try to make the gingerbread recipe page. 

``` text
Error reading file C:/Users/Jin/Documents/GitHub/stampedosaurs/gingerbread/ginge
rbread.md: invalid byte sequence in UTF-8
  Liquid Exception: invalid byte sequence in UTF-8 in gingerbread/gingerbread.md
jekyll 2.0.3 | Error:  invalid byte sequence in UTF-8
```

I ran jekyll server --trace and this is the output

``` text
C:\Users\Jin\Documents\GitHub\stampedosaurs>jekyll server --trace
Configuration file: C:/Users/Jin/Documents/GitHub/stampedosaurs/_config.yml
            Source: C:/Users/Jin/Documents/GitHub/stampedosaurs
       Destination: C:/Users/Jin/Documents/GitHub/stampedosaurs/_site
      Generating...
Error reading file C:/Users/Jin/Documents/GitHub/stampedosaurs/gingerbread/ginge
rbread.md: invalid byte sequence in UTF-8
  Liquid Exception: invalid byte sequence in UTF-8 in gingerbread/gingerbread.md

C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.5.5/lib/liquid/template.rb:141:
in `split': invalid byte sequence in UTF-8 (ArgumentError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.5.5/lib/liquid/tem
plate.rb:141:in `tokenize'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.5.5/lib/liquid/tem
plate.rb:58:in `parse'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.5.5/lib/liquid/tem
plate.rb:46:in `parse'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/con
vertible.rb:96:in `render_liquid'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/con
vertible.rb:170:in `do_layout'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/pag
e.rb:122:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/sit
e.rb:245:in `block in render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/sit
e.rb:244:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/sit
e.rb:244:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/sit
e.rb:43:in `process'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/com
mand.rb:43:in `process_site'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/com
mands/build.rb:46:in `build'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/com
mands/build.rb:30:in `process'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/com
mands/serve.rb:23:in `block (2 levels) in init_with_program'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercena
ry/command.rb:220:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercena
ry/command.rb:220:in `block in execute'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercena
ry/command.rb:220:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercena
ry/command.rb:220:in `execute'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercena
ry/program.rb:35:in `go'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercena
ry.rb:22:in `program'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/bin/jekyll:18:
in `<top (required)>'
        from C:/Ruby200-x64/bin/jekyll:23:in `load'
        from C:/Ruby200-x64/bin/jekyll:23:in `<main>'
```

I am very new and if anyone knows how to fix this, would you be able to give me step by step instructions? 
Thank you everyone in advance

**Comment by groovecoder** [comment]
In case anyone gets here later ... I hit this on a page that contained a `©` character in HTML. I changed it to `&copy;` and it worked. Looks like the gingerbread recipe may have a similar troublesome character: `°` in Preheat the oven to 180°C.

**Comment by waqqasdadabhoy** [comment]
Is it possible to get a line number of the offending text, so that it's easier to find and fix?

**Comment by divillysausages** [comment]
+1 for getting the line number. Otherwise it's a case of cutting text, compiling, cutting text etc through trial and error

**Comment by divillysausages** [comment]
For info, my problem as that I was copying text from another web page, and the quotes were wrong (i.e. “ instead of ")

I saw this when I went to stage the file using SourceTree and it had marked the bad characters with a �

**Comment by envygeeks** [comment]
@divillysausages please file a new issue to ask for that feature! Thanks.

**Comment by LukeDemons** [comment]
I got the same trouble. win8.1 & jekyll2.5.3.
Some previous pages are written under Linux, no problem. ask for help..thx....
![ERROR](https://cloud.githubusercontent.com/assets/7044891/8867054/19ee5056-31f7-11e5-8288-200b47272dc0.PNG)
