### ISSUE TITLE
`jekyll serve --watch` crashes when using node packages (Gulp.js)

### ISSUE THREAD

**Issue by kleinfreund** [jekyll/jekyll#2541]
Tried a few things with Gulp.js lately and encountered the following issue: When I do `jekyll serve --watch`, it immediately crashes. Without the watch flag it works fine.

**Exclude in _config.yml:**

```
exclude:
- node_modules
```

**Error message:**

```
$ jekyll serve --watch --trace
Configuration file: c:/Users/Philipp/_dev/github/bbk-vogtland/_config.yml
            Source: c:/Users/Philipp/_dev/github/bbk-vogtland
       Destination: c:/Users/Philipp/_dev/github/bbk-vogtland/_site
      Generating...
                    done.
E, [2014-06-24T19:30:54.539315 #3852] ERROR -- : Listen::Record crashed!
Errno::ENOENT: No such file or directory - c:/Users/Philipp/_dev/github/bbk-vogt
land/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modul
es/glob2base/node_modules/lodash.findindex/node_modules/lodash.createcallback/no
de_modules/lodash._basecreatecallback/node_modules/lodash.bind
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.r
b:110:in `open'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.r
b:110:in `entries'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.r
b:110:in `_fast_build'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.r
b:67:in `block in build'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.r
b:66:in `each'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.r
b:66:in `build'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/c
alls.rb:25:in `public_send'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/c
alls.rb:25:in `dispatch'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/c
alls.rb:67:in `dispatch'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/a
ctor.rb:322:in `block in handle_message'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/a
ctor.rb:416:in `block in task'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/t
asks.rb:55:in `block in initialize'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/t
asks/task_fiber.rb:13:in `block in create'
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/record.rb:110:in
 `open': No such file or directory - c:/Users/Philipp/_dev/github/bbk-vogtland/n
ode_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glo
b2base/node_modules/lodash.findindex/node_modules/lodash.createcallback/node_mod
ules/lodash._basecreatecallback/node_modules/lodash.bind (Errno::ENOENT)
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/rec
ord.rb:110:in `entries'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/rec
ord.rb:110:in `_fast_build'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/rec
ord.rb:67:in `block in build'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/rec
ord.rb:66:in `each'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/rec
ord.rb:66:in `build'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/cellul
oid/calls.rb:25:in `public_send'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/cellul
oid/calls.rb:25:in `dispatch'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/cellul
oid/calls.rb:67:in `dispatch'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/cellul
oid/actor.rb:322:in `block in handle_message'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/cellul
oid/actor.rb:416:in `block in task'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/cellul
oid/tasks.rb:55:in `block in initialize'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/cellul
oid/tasks/task_fiber.rb:13:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/cellul
oid/calls.rb:92:in `value'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/cellul
oid/proxies/sync_proxy.rb:33:in `method_missing'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/lis
tener.rb:81:in `block in <class:Listener>'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/cellul
oid/fsm.rb:175:in `instance_eval'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/cellul
oid/fsm.rb:175:in `call'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/cellul
oid/fsm.rb:127:in `transition_with_callbacks!'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/cellul
oid/fsm.rb:95:in `transition'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-2.7.8/lib/listen/lis
tener.rb:90:in `start'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/com
mands/build.rb:87:in `watch'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/com
mands/build.rb:31:in `process'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/com
mands/serve.rb:23:in `block (2 levels) in init_with_program'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercena
ry/command.rb:220:in `call'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercena
ry/command.rb:220:in `block in execute'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercena
ry/command.rb:220:in `each'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercena
ry/command.rb:220:in `execute'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercena
ry/program.rb:35:in `go'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercena
ry.rb:22:in `program'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/bin/jekyll:18:
in `<top (required)>'
        from c:/Ruby200-x64/bin/jekyll:23:in `load'
        from c:/Ruby200-x64/bin/jekyll:23:in `<main>'
```

I tried reinstalling the node modules. Nope. Also I'm not sure if this is a Jekyll issue. Might as well be a listen issue.

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages:
```
lodash.findindex@3.0.0
└─┬ lodash._basecallback@3.2.0
  ├─┬ lodash._baseisequal@3.0.1
  │ ├── lodash.isarray@3.0.0
  │ └── lodash.istypedarray@3.0.0
  ├── lodash._bindcallback@3.0.0
  └─┬ lodash.keys@3.0.3
    ├── lodash.isarguments@3.0.0
    ├── lodash.isarray@3.0.0
    └── lodash.isnative@3.0.0
```
