### ISSUE TITLE
URL should validate output

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#2834]
Colons, for example, should not be allowed

https://github.com/jekyll/jekyll-paginate/issues/8

**Comment by kostiakoval** [comment]
I still have this issue what should I do ?

**Comment by rensa** [comment]
I get the same error as @tkrotoff (identical except for the path of the jekyll blog) when I'm serving and any of my files regenerate. I can't for the life of me work out which file has an illegal character, though.

**Comment by parkr** [comment]
Can you run with `LISTEN_GEM_DEBUGGING=1`? That env var will show us more about what Listen thinks is happening.

**Comment by rensa** [comment]
Sure. Here's what I'm getting when I `serve`:
```
Configuration file: /Users/rensa/Code/rensa.github.io/_config.yml
            Source: /Users/rensa/Code/rensa.github.io
       Destination: /Users/rensa/Code/rensa.github.io/_site
      Generating... 
                    done.
I, [2015-10-26T20:32:22.635804 #12929]  INFO -- : Celluloid loglevel set to: 1
I, [2015-10-26T20:32:22.635855 #12929]  INFO -- : Listen version: 2.8.4
I, [2015-10-26T20:32:22.681548 #12929]  INFO -- : Record.build(): 0.02466297149658203 seconds
 Auto-regeneration: enabled for '/Users/rensa/Code/rensa.github.io'
Configuration file: /Users/rensa/Code/rensa.github.io/_config.yml
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
```
And then when I save an alteration to a file (in this case, I added the word `Change!` to one my posts):
```
I, [2015-10-26T20:32:52.988417 #12929]  INFO -- : listen: raw changes: [[:modified, "/Users/rensa/Code/rensa.github.io/_posts/writing/2015-09-01-shell-tut.md"]]
I, [2015-10-26T20:32:52.988552 #12929]  INFO -- : listen: final changes: {:modified=>["/Users/rensa/Code/rensa.github.io/_posts/writing/2015-09-01-shell-tut.md"], :added=>[], :removed=>[]}
      Regenerating: 1 files at 2015-10-26 20:32:52 ...done.
E, [2015-10-26T20:32:53.272593 #12929] ERROR -- : run() in thread failed: different prefix: "" and "/Users/rensa/Code/rensa.github.io":/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:500:in `relative_path_from'
/Library/Ruby/Gems/2.0.0/gems/listen-2.8.4/lib/listen/adapter/darwin.rb:47:in `block in _process_event'
/Library/Ruby/Gems/2.0.0/gems/listen-2.8.4/lib/listen/adapter/darwin.rb:43:in `each'
/Library/Ruby/Gems/2.0.0/gems/listen-2.8.4/lib/listen/adapter/darwin.rb:43:in `_process_event'
/Library/Ruby/Gems/2.0.0/gems/listen-2.8.4/lib/listen/adapter/base.rb:47:in `block (2 levels) in configure'
/Library/Ruby/Gems/2.0.0/gems/rb-fsevent-0.9.4/lib/rb-fsevent/fsevent.rb:45:in `call'
/Library/Ruby/Gems/2.0.0/gems/rb-fsevent-0.9.4/lib/rb-fsevent/fsevent.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/listen-2.8.4/lib/listen/adapter/darwin.rb:39:in `_run'
/Library/Ruby/Gems/2.0.0/gems/listen-2.8.4/lib/listen/adapter/base.rb:58:in `block in start'
/Library/Ruby/Gems/2.0.0/gems/listen-2.8.4/lib/listen/internals/thread_pool.rb:7:in `call'
/Library/Ruby/Gems/2.0.0/gems/listen-2.8.4/lib/listen/internals/thread_pool.rb:7:in `block in add'
```

**Comment by Crunch09** [comment]
I'll try to come up with a patch for this in the next few days if no one has already started working on this.

**Comment by Crunch09** [comment]
I was only able to reproduce the issue when still using the deprecated `jekyll-paginate`. Just a colon in the url didn't raise an error unless `Jekyll::Paginate::Pager.paginate_path` was called.
Am i missing something? And does this still need to be fixed in core jekyll?

**Comment by parkr** [comment]
@Crunch09 The idea is to validate the output of `Jekyll::URL.new(params).to_s`. If the URL output contains a colon, we should raise an error and let them know that the URL is invalid.

**Comment by Crunch09** [comment]
@parkr 👍 Thank you!
