### ISSUE TITLE
invalid date '0000-00-00' from template

### ISSUE THREAD

**Issue by jnozsc** [jekyll/jekyll#2938]
Hi, 

I tried to upgrade my site from jekyll 1.x to 2.x on heroku.
I meet this issue.
<b>
2014-09-19T20:34:36.760150+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/utils.rb:95:in `rescue in parse_date': Invalid date '0000-00-00': Post '/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the filename. (Jekyll::Errors::FatalException)
2014-09-19T20:34:36.760217+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in`each'
</b>

```
2014-09-19T20:34:31.414716+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:31.414735+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:31.414749+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:44:in `process'
2014-09-19T20:34:31.414763+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
2014-09-19T20:34:31.414708+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:31.414727+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:31.414746+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:31.414760+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
2014-09-19T20:34:31.427185+00:00 app[web.1]: Configuration file: /app/_config.yml
2014-09-19T20:34:31.414682+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/utils.rb:102:in `initialize': No such file or directory @ rb_sysopen - /app/vendor/bundle/ruby/2.1.0/gems/ffi-1.9.3/ext/ffi_c/libffi-x86_64-linux/include/ffitarget.h (Errno::ENOENT)
2014-09-19T20:34:31.414701+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/utils.rb:102:in `has_yaml_header?'
2014-09-19T20:34:31.414723+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:31.414741+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:31.414757+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
2014-09-19T20:34:31.414770+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/bin/rackup:4:in `<top (required)>'
2014-09-19T20:34:31.414718+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:31.414720+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:31.414736+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:31.414750+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/bundler/gems/rack-jekyll-f5064cd72dae/lib/rack/jekyll.rb:29:in `initialize'
2014-09-19T20:34:31.414764+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
2014-09-19T20:34:31.414729+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:31.414739+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:31.414754+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
2014-09-19T20:34:31.414767+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:250:in `start'
2014-09-19T20:34:31.414768+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:141:in `start'
2014-09-19T20:34:31.414698+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/utils.rb:102:in `open'
2014-09-19T20:34:31.414719+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:31.414722+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:31.414737+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:31.414751+00:00 app[web.1]:    from /app/config.ru:3:in `new'
2014-09-19T20:34:31.414765+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
2014-09-19T20:34:31.414724+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:31.414742+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:31.414743+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:31.414758+00:00 app[web.1]:    from /app/config.ru:in `new'
2014-09-19T20:34:31.414771+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/bin/rackup:23:in `load'
2014-09-19T20:34:31.414731+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:31.414733+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:31.414738+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:31.414753+00:00 app[web.1]:    from /app/config.ru:3:in `block in <main>'
2014-09-19T20:34:31.414766+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
2014-09-19T20:34:34.801508+00:00 heroku[web.1]: Starting process with command `bundle exec rackup config.ru -p 56764`
2014-09-19T20:34:36.760179+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:190:in `read_content'
2014-09-19T20:34:36.760185+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:36.760187+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:36.760196+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:36.760203+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:36.760225+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/bundler/gems/rack-jekyll-f5064cd72dae/lib/rack/jekyll.rb:29:in `initialize'
2014-09-19T20:34:36.760247+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
2014-09-19T20:34:36.760183+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:36.760192+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:36.760198+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:36.760206+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:36.760218+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:36.760243+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
2014-09-19T20:34:36.760265+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/bin/rackup:23:in `load'
2014-09-19T20:34:36.760176+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:191:in `block in read_content'
2014-09-19T20:34:36.760181+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:138:in `read_directories'
2014-09-19T20:34:36.760191+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:36.760197+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:36.760204+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:36.760221+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:122:in `read'
2014-09-19T20:34:36.760244+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
2014-09-19T20:34:36.771806+00:00 app[web.1]: Configuration file: /app/_config.yml
2014-09-19T20:34:36.760173+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/post.rb:56:in `initialize'
2014-09-19T20:34:36.760184+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:36.760193+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:36.760199+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:36.760210+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:36.760236+00:00 app[web.1]:    from /app/config.ru:in `new'
2014-09-19T20:34:36.760266+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/bin/rackup:23:in `<main>'
2014-09-19T20:34:36.760168+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/utils.rb:93:in `parse_date'
2014-09-19T20:34:36.760207+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:36.760227+00:00 app[web.1]:    from /app/config.ru:3:in `new'
2014-09-19T20:34:36.760250+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
2014-09-19T20:34:36.760178+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:190:in `map'
2014-09-19T20:34:36.760211+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:36.760230+00:00 app[web.1]:    from /app/config.ru:3:in `block in <main>'
2014-09-19T20:34:36.760251+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
2014-09-19T20:34:36.760170+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/post.rb:162:in `process'
2014-09-19T20:34:36.760215+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:147:in `block in read_directories'
2014-09-19T20:34:36.760234+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
2014-09-19T20:34:36.760257+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:250:in `start'
2014-09-19T20:34:36.760180+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:166:in `read_posts'
2014-09-19T20:34:36.760188+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:36.760195+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:36.760202+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:36.760222+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:44:in `process'
2014-09-19T20:34:36.760240+00:00 app[web.1]:    from /app/config.ru:in `<main>'
2014-09-19T20:34:36.760262+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/bin/rackup:4:in `<top (required)>'
2014-09-19T20:34:36.760175+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:191:in `new'
2014-09-19T20:34:36.760212+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `read_directories'
2014-09-19T20:34:36.760233+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
2014-09-19T20:34:36.760254+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
2014-09-19T20:34:36.760150+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/utils.rb:95:in `rescue in parse_date': Invalid date '0000-00-00': Post '/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the filename. (Jekyll::Errors::FatalException)
2014-09-19T20:34:36.760217+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:143:in `each'
2014-09-19T20:34:36.760258+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:141:in `start'
2014-09-19T20:34:37.514418+00:00 heroku[web.1]: Process exited with status 1
```

I search closed issues and find there are a lot of similar issue. https://github.com/jekyll/jekyll/issues?q=invalid+date

I just wonder why jekyll will check the date in **/jekyll-2.4.0/lib/site_template/** , not my own _post folder.

Any suggestion?

Thanks!

**Comment by trkrameshkumar** [comment]
Thanks @parkr i had the same problem when i add this line ``exclude: [vendor]`` in _config.yml it is works, can you explain the reason.?

**Comment by parkr** [comment]
Jekyll has a copy of itself in the `vendor` directory there. It includes our tests. We have that post in our tests to ensure we fail on invalid dates.

**Comment by steveamaza** [comment]
Hello @parkr. Excluding vendor stops bootstrap, font-awesome and other files in my `vendor` file from being seen. How do I go about that? Thank you

**Comment by steveamaza** [comment]
Found a fix by only excluding vendor/bundle :grin:

**Comment by parkr** [comment]
Hey @steveamaza! In that case, I would extend the exclusion to the necessary subfolder:

```yaml
exclude:
- vendor/bundle
```

**Comment by parkr** [comment]
Yep! Good work. 🔍

**Comment by steveamaza** [comment]
Thanks for responding so fast @parkr :pray:
