### ISSUE TITLE
hitimes load error...

### ISSUE THREAD

**Issue by supercafe2013** [jekyll/jekyll#3092]
Hi ,
I'm the greener to jekyll,after I installed Jekyll and run for it,error happened...
According to the clues, I installed hittimes,but the problems still exists.

```
/Users/supercafe/my-awsome-site
supercafes-MacBook-Pro:my-awsome-site supercafe$ jekyll serve
Configuration file: /Users/supercafe/my-awsome-site/_config.yml
            Source: /Users/supercafe/my-awsome-site
       Destination: /Users/supercafe/my-awsome-site/_site
      Generating...
                    done.
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- hitimes/hitimes (LoadError)
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/hitimes-1.2.2/lib/hitimes.rb:37:in `rescue in <top (required)>'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/hitimes-1.2.2/lib/hitimes.rb:32:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/timers-4.0.1/lib/timers/group.rb:4:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/timers-4.0.1/lib/timers.rb:4:in `<top (required)>'

```

**Comment by AlejandroCruz** [comment]
I have trouble following the comments. I uninstalled hitmes and timers and re-installed timers (which automatically fetches hitimes) with no luck resolving the issue. Anything I should look out for or do?
