### ISSUE TITLE
UX of getting broken Jekyll to work

### ISSUE THREAD

**Issue by jglovier** [jekyll/jekyll#3124]
*Opening this issue in the interest of UX improvements to the CLI experience of getting Jekyll to work when it seems broken in a given directory.*

It's been months since I updated my blog, because life. I wanted to update my blog this evening, so I ran to my jglovier.github.io local directory, and not being sure whether I had actually upgraded Jekyll in that repository to Jekyll 2.0 yet, I ran `jekyll -v`, thinking that might tell me. I got:

```
|===jglovier===| ~/code/github-jglovier/jglovier.github.io $ jekyll -v
/opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find ffi-1.9.3 in any of the sources (Bundler::GemNotFound)
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/spec_set.rb:85:in `map!'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/spec_set.rb:85:in `materialize'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/definition.rb:133:in `specs'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/definition.rb:178:in `specs_for'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:13:in `setup'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler.rb:127:in `setup'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler.rb:132:in `require'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/lib/jekyll/plugin_manager.rb:40:in `require_from_bundler'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/bin/jekyll:16:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.1.2-github/bin/jekyll:23:in `load'
	from /opt/boxen/rbenv/versions/2.1.2-github/bin/jekyll:23:in `<main>'
```
That seemed rather unhelpful, so I assumed I must have asked for the version wrong. So I tried instead `jekyll version` which returned:

```
|===jglovier===| ~/code/github-jglovier/jglovier.github.io $ jekyll version
/opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find ffi-1.9.3 in any of the sources (Bundler::GemNotFound)
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/spec_set.rb:85:in `map!'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/spec_set.rb:85:in `materialize'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/definition.rb:133:in `specs'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/definition.rb:178:in `specs_for'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:13:in `setup'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler.rb:127:in `setup'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler.rb:132:in `require'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/lib/jekyll/plugin_manager.rb:40:in `require_from_bundler'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/bin/jekyll:16:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.1.2-github/bin/jekyll:23:in `load'
	from /opt/boxen/rbenv/versions/2.1.2-github/bin/jekyll:23:in `<main>'
```

I gave up trying to get the version, and just tried serving the repo at this point, wondering if Jekyll was even working in this directory still. I got the same result:

```
|===jglovier===| ~/code/github-jglovier/jglovier.github.io $ jekyll serve
/opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find ffi-1.9.3 in any of the sources (Bundler::GemNotFound)
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/spec_set.rb:85:in `map!'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/spec_set.rb:85:in `materialize'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/definition.rb:133:in `specs'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/definition.rb:178:in `specs_for'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:13:in `setup'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler.rb:127:in `setup'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler.rb:132:in `require'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/lib/jekyll/plugin_manager.rb:40:in `require_from_bundler'
	from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/bin/jekyll:16:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.1.2-github/bin/jekyll:23:in `load'
	from /opt/boxen/rbenv/versions/2.1.2-github/bin/jekyll:23:in `<main>'
```
So I just tried updating Jekyll:
```
|===jglovier===| ~/code/github-jglovier/jglovier.github.io $ gem update jekyll
Updating installed gems
Nothing to update
```
Hmm, nothing really helpful there. So then I remembered I do have a Gemfile in that directory, so i ran `bundle update`, which ended up giving me more unhelpful output:

```
|===jglovier===| ~/code/github-jglovier/jglovier.github.io $ bundle update
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies.........
Using RedCloth 4.2.9
Using i18n 0.6.11
Using json 1.8.1
Using blankslate 2.1.2.4
Using fast-stemmer 1.0.2
Using colorator 0.1
Installing minitest 5.4.3
Using ffi 1.9.6 (was 1.9.3)
Installing highline 1.6.21 (was 1.6.20)
Using liquid 2.5.5
Using rb-fsevent 0.9.4
Using maruku 0.7.0
Using posix-spawn 0.3.9 (was 0.3.8)
Using yajl-ruby 1.1.0
Using redcarpet 2.3.0
Using safe_yaml 1.0.4 (was 0.9.7)
Installing thread_safe 0.3.4
Using kramdown 1.3.1
Using rdiscount 2.1.7
Installing mini_portile 0.6.1
Using bundler 1.6.3
Using parslet 1.5.0
Using classifier 1.3.4
Using rb-inotify 0.9.5 (was 0.9.3)
Installing rb-kqueue 0.2.3 (was 0.2.0)
Installing sass 3.4.8 (was 3.2.13)
Installing commander 4.1.6 (was 4.1.5)
Installing pygments.rb 0.5.4
Installing tzinfo 1.2.2
Using toml 0.1.2 (was 0.1.0)
Installing listen 1.3.1
Installing gemoji 1.5.0
Installing activesupport 4.1.8
Installing jekyll 1.5.1 (was 1.4.3)
Installing jekyll-sitemap 0.3.0
Installing jekyll-redirect-from 0.3.1 (was 0.3.0)

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /opt/rubies/2.1.2-github1/bin/ruby extconf.rb
checking if the C compiler accepts -I/opt/boxen/homebrew/include... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
-----
The file "/usr/include/iconv.h" is missing in your build environment,
which means you haven't installed Xcode Command Line Tools properly.

To install Command Line Tools, try running `xcode-select --install` on
terminal and follow the instructions.  If it fails, open Xcode.app,
select from the menu "Xcode" - "Open Developer Tool" - "More Developer
Tools" to open the developer site, download the installer for your OS
version and run it.
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/rubies/2.1.2-github1/bin/ruby
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build

extconf failed, exit code 1

Gem files will remain installed in /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.4.1 for inspection.
Results logged to /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/nokogiri-1.6.4.1/gem_make.out
An error occurred while installing nokogiri (1.6.4.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.4.1'` succeeds before bundling.
```

I realize there may be very little that Jekyll is actually responsible for here, but then again I really don't even know. Is there anything in Jekyll that can be improved from my situation? At this point I still don't even know why Jekyll isn't working. `¯\_(ツ)_/¯` :sob:

**Comment by parkr** [comment]
Directions seem all setup now: https://github.com/jekyll/jekyll/tree/master/site#running-locally

I agree that `-v` or `--version` should exit more cleanly but this looks like a larger issue with environment weirdness. I think a case-by-case basis will be best for helping users with these kinds of issues. Thanks!

**Comment by nilsborchers** [comment]
Got it fixed by running `bundle update`
