### ISSUE TITLE
Error when running Jekyll after upgrading to 2.5.3

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll#3257]
Hello everyone,

I just have upgraded to Jekyll 2.5.3 and when I run `jekyll serve` I get the following error:
````
Malahovas-MacBook-Pro:iloveip Svetlana$ jekyll serve --trace
WARN: Unresolved specs during Gem::Specification.reset:
      rb-inotify (>= 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Users/Svetlana/.rvm/gems/ruby-2.0.0-p353/gems/mercenary-0.3.3/lib/mercenary.rb:20:in `program': cannot load such file -- mercenary/program (LoadError)
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p353/bin/jekyll:23:in `load'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p353/bin/jekyll:23:in `<main>'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
````

Does anyone know how I can fix this? I will appreciate any help.

Here is the link to my repository https://github.com/iloveip/iloveip.

**Comment by parkr** [comment]
Run jekyll with `bundle exec`.

**Comment by iloveip** [comment]
Hi @parkr,

Thank you very much. I installed Bundler and ran `bundle exec jekyll serve`, but I got the following error:

````
Malahovas-MacBook-Pro:~ Svetlana$ gem install bundler
Fetching: bundler-1.7.11.gem (100%)
Successfully installed bundler-1.7.11
Parsing documentation for bundler-1.7.11
Installing ri documentation for bundler-1.7.11
Done installing documentation for bundler after 3 seconds
1 gem installed
Malahovas-MacBook-Pro:~ Svetlana$ cd desktop/iloveip
Malahovas-MacBook-Pro:iloveip Svetlana$ bundle exec jekyll serve
/Users/Svetlana/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.7.11/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': jekyll is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p353/bin/jekyll:22:in `<main>'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
Malahovas-MacBook-Pro:iloveip Svetlana$ 
````

**Comment by parkr** [comment]
Your answer

> jekyll is not part of the bundle. Add it to Gemfile

`gem "jekyll"`

**Comment by iloveip** [comment]
@parkr Thank you very much! It's working now.
