### ISSUE TITLE
Jekyll install error

### ISSUE THREAD

**Issue by djmtype** [jekyll/jekyll#3283]
I installed Jekyll on my Mac. `sudo gem install jekyll`
The required components install. 

```
iMac:~ me$ sudo gem install jekyll
Fetching: jekyll-watch-1.2.0.gem (100%)
Successfully installed jekyll-watch-1.2.0
Fetching: jekyll-sass-converter-1.3.0.gem (100%)
Successfully installed jekyll-sass-converter-1.3.0
Fetching: jekyll-coffeescript-1.0.1.gem (100%)
Successfully installed jekyll-coffeescript-1.0.1
Fetching: jekyll-gist-1.1.0.gem (100%)
Successfully installed jekyll-gist-1.1.0
Fetching: jekyll-paginate-1.1.0.gem (100%)
Successfully installed jekyll-paginate-1.1.0
Fetching: jekyll-2.5.3.gem (100%)
Successfully installed jekyll-2.5.3
Parsing documentation for jekyll-watch-1.2.0
Installing ri documentation for jekyll-watch-1.2.0
Parsing documentation for jekyll-sass-converter-1.3.0
Installing ri documentation for jekyll-sass-converter-1.3.0
Parsing documentation for jekyll-coffeescript-1.0.1
Installing ri documentation for jekyll-coffeescript-1.0.1
Parsing documentation for jekyll-gist-1.1.0
Installing ri documentation for jekyll-gist-1.1.0
Parsing documentation for jekyll-paginate-1.1.0
Installing ri documentation for jekyll-paginate-1.1.0
Parsing documentation for jekyll-2.5.3
Installing ri documentation for jekyll-2.5.3
Done installing documentation for jekyll-watch, jekyll-sass-converter, jekyll-coffeescript, jekyll-gist, jekyll-paginate, jekyll after 1 seconds
6 gems installed
```

Then I run `jekyll -v`. Instead of seeing a Jekyll version number, a whole bunch of nonsense is returned. 

```
iMac:~ me$ jekyll -v
/Users/me/.rvm/gems/ruby-2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:4:in `<class:PsychResolver>': uninitialized constant Psych::Nodes (NameError)
	from /Users/me/.rvm/gems/ruby-2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:2:in `<module:SafeYAML>'
	from /Users/me/.rvm/gems/ruby-2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:1:in `<top (required)>'
	from /Users/me/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/me/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/me/.rvm/gems/ruby-2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:131:in `<module:SafeYAML>'
	from /Users/me/.rvm/gems/ruby-2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:26:in `<top (required)>'
	from /Users/me/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/me/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/me/.rvm/gems/ruby-2.1.0@global/gems/jekyll-2.5.3/lib/jekyll.rb:26:in `<top (required)>'
	from /Users/me/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/me/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/me/.rvm/gems/ruby-2.1.0@global/gems/jekyll-2.5.3/bin/jekyll:6:in `<top (required)>'
	from /Users/me/.rvm/rubies/ruby-2.1.0/bin/jekyll:23:in `load'
	from /Users/me/.rvm/rubies/ruby-2.1.0/bin/jekyll:23:in `<main>'
	from /Users/me/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/me/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

Mind you, I've tried uninstalling and reinstalling Jekyll again. I've also updated my system `sudo gem update --system`. The error obviously prevents me from creating a new Jekyll project, `jekyll new my-awesome-site`. 

Is the **safe_yaml** version the issue? If so, which version does Jekyll need? Do I need to install something more?

**Comment by djmtype** [comment]
Whoops, this thread is already open [https://github.com/jekyll/jekyll/issues/3201](https://github.com/jekyll/jekyll/issues/3201)
