### ISSUE TITLE
Jekyll i18n Error

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll#3293]
Hello,

I installed i18n gem and plugin to localize the dates, but when I serve the site I get the following error:

````
Malahovas-MacBook-Pro:test Svetlana$ rake
Configuration file: /Users/Svetlana/Desktop/test/_config.yml
            Source: /Users/Svetlana/Desktop/test
       Destination: /Users/Svetlana/Desktop/test/_site
      Generating... 
  Liquid Exception: Object must be a Date, DateTime or Time object. "2015-12-01" given. in _includes/footer.html, included in _layouts/post.html
jekyll 2.5.3 | Error:  Object must be a Date, DateTime or Time object. "2015-12-01" given.
````

In `footer.html` I have the following code:

````
<time datetime="{{ page.date | date: "%Y-%m-%d" }}">
    {{ page.date | localize: "%d %B %Y" }}
</time>
````

Do you know how this can be fixed?

**Comment by parkr** [comment]
I don't know how the jekyll i18n plugin works, so I'm not sure :( If you run build with `--trace`, you should see the line where it exploded. Is this a post, page, or collection document?

**Comment by iloveip** [comment]
@parkr after running build with `--trace` I get:

````
Malahovas-MacBook-Pro:iloveip Svetlana$ jekyll build --trace
Configuration file: /Users/Svetlana/Desktop/test/_config.yml
            Source: /Users/Svetlana/Desktop/test
       Destination: /Users/Svetlana/Desktop/test/_site
      Generating... 
  Liquid Exception: Object must be a Date, DateTime or Time object. "2015-31-01" given. in _includes/footer.html, included in _layouts/post.html
/Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/tags/include.rb:124:in `rescue in render': Object must be a Date, DateTime or Time object. "2015-31-01" given. (Jekyll::Tags::IncludeTagError)
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/tags/include.rb:116:in `render'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/liquid-2.6.1/lib/liquid/block.rb:109:in `block in render_all'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `each'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `render_all'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/liquid-2.6.1/lib/liquid/block.rb:82:in `render'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/liquid-2.6.1/lib/liquid/template.rb:128:in `render'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/liquid-2.6.1/lib/liquid/template.rb:138:in `render!'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/renderer.rb:92:in `render_liquid'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/renderer.rb:134:in `place_in_layouts'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/renderer.rb:56:in `run'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/site.rb:292:in `block (2 levels) in render'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/site.rb:291:in `each'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/site.rb:291:in `block in render'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/site.rb:290:in `each'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/site.rb:290:in `render'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `call'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `each'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `execute'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary/program.rb:35:in `go'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/mercenary-0.3.3/lib/mercenary.rb:22:in `program'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/bin/jekyll:23:in `load'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/bin/jekyll:23:in `<main>'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Svetlana/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `<main>'
```

It is a collection document. The date is set in front matter defaults. Here is the code for the plugin `i18n_filter.rb`:

````
require 'i18n'
 
LOCALE = :ru # set your locale
 
# Create folder "_locales" and put some locale file from
# https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale
module Jekyll
  module I18nFilter
    # Example:
    # {{ post.date | localize: "%d.%m.%Y" }}
    # {{ post.date | localize: ":short" }}
    def localize(input, format=nil)
      load_translations
      format = (format =~ /^:(\w+)/) ? $1.to_sym : format
      I18n.l input, :format => format
    end
 
    def load_translations
      unless I18n::backend.instance_variable_get(:@translations)
        I18n.backend.load_translations Dir[File.join(File.dirname(__FILE__), '../_locales/*.yml')]
        I18n.locale = LOCALE
      end
    end
  end
end
 
Liquid::Template.register_filter(Jekyll::I18nFilter)
````

**Comment by parkr** [comment]
> It is a collection document.

Collection documents unfortunately don't have any elements pre-filtered, meaning `date` won't be run through `Time.parse` like it is for a post. This will change soonish as we move posts to documents.

**Comment by iloveip** [comment]
@parkr I see, thank you very much. Is there any work around for now?

**Comment by parkr** [comment]
Ensure your date is a string, i.e. `date: "2014-01-10"` (note the quotes).

**Comment by iloveip** [comment]
@parkr Yes, it's a string. Do you mean that now `date` in collection documents can be run through the filter like it is for a post?

P. S. For me the plugin is working now. Please see here for details: http://stackoverflow.com/a/27916987/3354729.

**Comment by parkr** [comment]
`page.date | date` should always be able to take a String.

**Comment by penibelst** [comment]
@iloveip In case you just want Russian month names, you can build them with pure Liquid *without* any plugins. What do you want to see for 2015-02-08? *8 февраля 2015?*

**Comment by iloveip** [comment]
@penibelst Yes, I know, thank you very much. I'm already using it on my site.
