### ISSUE TITLE
Jekyll fails to start server- error in Liquid? Library not loaded

### ISSUE THREAD

**Issue by Behinder** [jekyll/jekyll#3344]
all gems in recent versions..

```
/Users/sebastian/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
Configuration file: /Users/sebastian/test/_config.yml
            Source: /Users/sebastian/test
       Destination: /Users/sebastian/test/_site
      Generating...
  Liquid Exception: dlopen(/Users/sebastian/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/posix-spawn-0.3.9/posix_spawn_ext.bundle, 9): Library not loaded: /Users/sebastian/.rvm/rubies/ruby-2.2.0-preview1/lib/libruby.2.2.0.dylib Referenced from: /Users/sebastian/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/posix-spawn-0.3.9/posix_spawn_ext.bundle Reason: image not found - /Users/sebastian/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/posix-spawn-0.3.9/posix_spawn_ext.bundle in _posts/2015-01-24-welcome-to-jekyll.markdown
/Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/sebastian/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/posix-spawn-0.3.9/posix_spawn_ext.bundle, 9): Library not loaded: /Users/sebastian/.rvm/rubies/ruby-2.2.0-preview1/lib/libruby.2.2.0.dylib (LoadError)
  Referenced from: /Users/sebastian/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/posix-spawn-0.3.9/posix_spawn_ext.bundle
  Reason: image not found - /Users/sebastian/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/posix-spawn-0.3.9/posix_spawn_ext.bundle
	from /Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/posix-spawn-0.3.9/lib/posix/spawn.rb:2:in `<top (required)>'
	from /Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/pygments.rb-0.6.0/lib/pygments/popen.rb:2:in `<top (required)>'
	from /Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/pygments.rb-0.6.0/lib/pygments.rb:1:in `<top (required)>'
	from /Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/sebastian/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/tags/highlight.rb:78:in `render_pygments'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/tags/highlight.rb:52:in `render'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.1/lib/liquid/block.rb:109:in `block in render_all'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `each'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `render_all'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.1/lib/liquid/block.rb:82:in `render'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.1/lib/liquid/template.rb:128:in `render'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.1/lib/liquid/template.rb:138:in `render!'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:233:in `do_layout'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/post.rb:261:in `render'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `load'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `<main>'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sebastian/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by parkr** [comment]
This is a problem with the way posix-spawn was installed. Try re-installing it!

**Comment by Behinder** [comment]
gem install posix-spawn gem cleanup
and another problem
``
jekyll serve                                                    [ruby-2.2.0]
/Users/sebastian/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
Configuration file: /Users/sebastian/test/_config.yml
            Source: /Users/sebastian/test
       Destination: /Users/sebastian/test/_site
      Generating...
  Liquid Exception: dlopen(/Users/sebastian/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/yajl-ruby-1.1.0/yajl/yajl.bundle, 9): Library not loaded: /Users/sebastian/.rvm/rubies/ruby-2.2.0-preview1/lib/libruby.2.2.0.dylib Referenced from: /Users/sebastian/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/yajl-ruby-1.1.0/yajl/yajl.bundle Reason: image not found - /Users/sebastian/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/yajl-ruby-1.1.0/yajl/yajl.bundle in _posts/2015-01-24-welcome-to-jekyll.markdown
``
this time error in yail??? Why is jekyll based on such numbers unstable dependencies??????

**Comment by parkr** [comment]
This error doesn't pop up frequently. When you ran `gem cleanup`, you might have inadvertently removed `yajl`, or used a different ruby to install yajl. Running `gem install yajl` might help, or `rvm remove 2.2.0 && rvm install 2.2.0`.

**Comment by Behinder** [comment]
Ok. Now wors..I had to complete remove all gems with dependencies. Then got new rubygems from rvm and installed jekyll with dependencies and now it starts to work again :) creepy
