### ISSUE TITLE
Jekyll::Tags::IncludeTagError on Windows PowerShell

### ISSUE THREAD

**Issue by luixxiul** [jekyll/jekyll#3389]
After installing 3.0.0.beta1, I got ``Jekyll::Tags::IncludeTagError`` on Windows PowerShell. 

````
C:\Users\Admin\Temp\Jekyll> bundle exec jekyll serve --limit_posts 3 --trace
DL is deprecated, please use Fiddle
Configuration file: C:/Users/Admin/Temp/Jekyll/_config.yml
            Source: _src
       Destination: _dest
 Incremental build: enabled
      Generating...
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/posix-spawn-0.3.9/lib/posix/spawn.rb:164: warning: cannot close fd before spawn
'which' is not recognized as an internal or external command, operable program or batch file. 
  Liquid Exception: No such file or directory - C:/Users/Admin/Temp/Jekyll/_src/tag/decoding.html does not exist! in _includes/head_tag.html, included in _layouts/default.html
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/tags/include.rb:133:in `rescue in render': No such file or directory - C:/Users/Admin/Temp/Jekyll/_src/tag/decoding.html does not exist! (Jekyll::Tags::IncludeTagError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/tags/include.rb:125:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-3.0.1/lib/liquid/block.rb:151:in `render_token'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-3.0.1/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-3.0.1/lib/liquid/profiler.rb:80:in `profile_token_render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-3.0.1/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-3.0.1/lib/liquid/block.rb:135:in `block in render_all'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-3.0.1/lib/liquid/block.rb:122:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-3.0.1/lib/liquid/block.rb:122:in `render_all'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-3.0.1/lib/liquid/block.rb:108:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-3.0.1/lib/liquid/template.rb:210:in `block in render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-3.0.1/lib/liquid/template.rb:262:in `with_profiling'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-3.0.1/lib/liquid/template.rb:209:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-3.0.1/lib/liquid/template.rb:222:in `render!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/convertible.rb:106:in `render_liquid'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/convertible.rb:205:in `render_all_layouts'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/convertible.rb:245:in `do_layout'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/page.rb:122:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:307:in `block in render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:305:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:305:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:55:in `process'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/commands/build.rb:58:in `build'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/commands/build.rb:34:in `process'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/bin/jekyll:17:in `<top (required)>'
        from C:/Ruby200-x64/bin/jekyll:23:in `load'
        from C:/Ruby200-x64/bin/jekyll:23:in `<main>'
````

Interestingly this error occurs only on PowerShell, not on a command prompt.

My ``Gemfile`` is:
````
source 'https://rubygems.org'

gem 'jekyll', '3.0.0.pre.beta1'
gem 'kramdown'
gem 'jekyll-redirect-from'
gem 'jekyll-last-modified-at'
gem 'jekyll-tagging'

# Please add the following to your Gemfile to avoid polling for changes:
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
````

**Comment by parkr** [comment]
Does it work in Cygwin? Does `C:/Users/Admin/Temp/Jekyll/_src/tag/decoding.html` actually exist?

**Comment by luixxiul** [comment]
No, it doesn't work. Same error occurs :disappointed: 
The file has is generated dynamically by the gem [``jekyll-tagging``](https://github.com/pattex/jekyll-tagging).

**Comment by luixxiul** [comment]
I found the error was caused by the gem ``jekyll-last-modified-at``.

````
<meta property="article:modified_time" content="{{ page.last_modified_at | date: '%Y-%m-%dT%H:%M:%S+00:00' }}">
````

By removing this from ``_includes/head_tag.html, included in _layouts/default.html`` the error stops occurring.

**Comment by parkr** [comment]
If it's generated dynamically but isn't written then the plugins aren't compatible as-is. It's a plugin problem, sadly.
