### ISSUE TITLE
“rake aborted!” when following development install directions

### ISSUE THREAD

**Issue by migurski** [jekyll/jekyll#3394]
I’m attempting to [follow the development directions](http://jekyllrb.com/docs/installation/):

    $ git clone git://github.com/jekyll/jekyll.git
    $ cd jekyll
    $ script/bootstrap
    $ bundle exec rake build
    $ ls pkg/*.gem | head -n 1 | xargs gem install -l

On Ubuntu 14.04, it fails at step four. I have Ruby installed using RVM, looks to be `ruby 2.2.0p0`. Out from from `bundle` looks like:

```
** Invoke build (first_time)
** Execute build
mkdir -p pkg
gem build jekyll.gemspec
  Successfully built RubyGem
  Name: jekyll
  Version: 3.0.0.pre.beta1
  File: jekyll-3.0.0.pre.beta1.gem
mv jekyll-3.0.0-beta1.gem pkg
mv: cannot stat ‘jekyll-3.0.0-beta1.gem’: No such file or directory
rake aborted!
Command failed with status (1): [mv jekyll-3.0.0-beta1.gem pkg...]
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/file_utils.rb:66:in `block in create_shell_runner'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/file_utils.rb:57:in `call'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/file_utils.rb:57:in `sh'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `sh'
/home/migurski/jekyll/Rakefile:308:in `block in <top (required)>'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/migurski/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/migurski/.rvm/rubies/ruby-2.2.0/bin/rake:33:in `<main>'
Tasks: TOP => build
```

I do have a `jekyll-3.0.0.pre.beta1.gem` in the directory, but no `jekyll-3.0.0.beta1.gem`.

**Comment by envygeeks** [comment]
It's because of the way that RubyGems behaves and the way Jekyll expects RubyGems to behave, it's kinda odd this has never risen before but it should be fixed now since I've switched it to use RubyGems to build the version string for the `*.gem` file.

**Comment by migurski** [comment]
Worked, thank you!

**Comment by parkr** [comment]
Thanks, Jordon!
