### ISSUE TITLE
Problem with sorting in _data directory on multiple JSON files on property value

### ISSUE THREAD

**Issue by fkostadinov** [jekyll/jekyll#3414]
I have a data files directory <code>&#95;data/blahs</code> containing JSON files, which all look alike:
```
file1.json: {  "foo": "bbb" }
file2.json: {  "foo": "aaa" }
file3.json: {  "foo": "ccc" }
```
Then I want to iterate with a Liquid template over all data files and sort by the _foo_ property:
```
  {% assign sorted_blah = site.data.blahs | sort: "foo" %}
  {% for blah in sorted_blah %}
    <div>{{ blah }}</div>
  {% endfor %}
```
This part of the code does not work: <code>{% assign sorted_blah = site.data.blahs | sort: "foo" %}</code>. I always receive this error message: <code>jekyll 2.5.3 | Error:  no implicit conversion of String into Integer</code>.

If I however only use <code>  {% assign sorted_blah = site.data.blahs | sort %}</code> (without providing a JSON property), then it actually seems to sort by filename, but not by property value.

Am I misunderstanding how the sort filter actually works? Or is this a bug?

**Comment by parkr** [comment]
What does it give you if you run Jekyll with `--trace`?

**Comment by fkostadinov** [comment]
Hi parkr, here is my stack trace:

```
WARN: Unresolved specs during Gem::Specification.reset:
      redcarpet (~> 3.1)
      jekyll-watch (~> 1.1)
      classifier-reborn (~> 2.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: C:/Users/FK/Documents/GitHub/My-Repo/_config.yml
            Source: C:/Users/FK/Documents/GitHub/My-Repo
       Destination: C:/Users/FK/Documents/GitHub/My-Repo/_site
      Generating...
  Liquid Exception: no implicit conversion of String into Integer in test-sort.html
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/filters.rb:321:in `[]': no implicit conversion of String into Integer (TypeError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/filters.rb:321:in `item_property'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/filters.rb:249:in `block in sort'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/filters.rb:248:in `sort'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/filters.rb:248:in `sort'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/strainer.rb:43:in `invoke'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/context.rb:82:in `invoke'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/variable.rb:50:in `block in render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/variable.rb:38:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/variable.rb:38:in `inject'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/variable.rb:38:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/tags/assign.rb:26:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/block.rb:109:in `block in render_all'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `render_all'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/block.rb:82:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/template.rb:128:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/template.rb:138:in `render!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:233:in `do_layout'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/page.rb:122:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
        from C:/Ruby200-x64/bin/jekyll:23:in `load'
        from C:/Ruby200-x64/bin/jekyll:23:in `<main>'
```

**Comment by parkr** [comment]
[The line where this freaked out](https://github.com/jekyll/jekyll/blob/stable-2-5/lib/jekyll/filters.rb#L321) was expecting a *Number* but instead received a *String*. This means it's a positional Array, not a key-value Hash. The items you're trying to sort are *Array*'s not *Hash*'s.

**Comment by fkostadinov** [comment]
Well, that's what the error message already tells me. What I don't understand is why it is expecting a number and not a string, or in other terms, why this is a positional array and not a key-value hash. Or to make it short: How can I then sort JSON files in my data directory according to a property value? What would the correct syntax here be?

**Comment by RobertDeRose** [comment]
:+1: Would like to know this as well.
