### ISSUE TITLE
Fail to install Jekyll

### ISSUE THREAD

**Issue by ZhipengZeng** [jekyll/jekyll#3425]
Hi, just for creating a github blog, I've already encountered many issues...
I've read over 15 issues about installing Jeskll, but no one is  useful.
Please help!!!
Here is the situation I met:

I indicated my environment in advance:
    Windows7 (64-bit)
    Ruby21-x64
    environment variables all set
    following this website: http://jekyll-windows.juthilo.com/
    finish `gem install bundler` & `gem install linguist`
    administrator authority

when I run `gem install wdm`
it shows this message:
```
c:/Ruby21-x64/bin/ruby.exe -r ./siteconf20150208-5188-1cm5er1.rb extconf.rb
checking for main() in -lkernel32... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=c:/Ruby21-x64/bin/ruby
	--with-kernel32lib
	--without-kernel32lib
c:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from c:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
	from c:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
	from c:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:742:in `try_func'
	from c:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:973:in `block in have_library'
	from c:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
	from c:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from c:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from c:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
	from c:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from c:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
	from c:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
	from c:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:968:in `have_library'
	from extconf.rb:19:in `<main>'

extconf failed, exit code 1
```

when I run `gem install jekyll`
it shows this such long message:
```
c:/Ruby21-x64/bin/ruby.exe -r ./siteconf20150208-1672-1qpyma9.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating stemmer-x64-mingw32.def
compiling porter.c
porter.c: In function 'step1ab':
porter.c:233:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:234:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:234:7: warning: passing argument 2 of 'setto' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:196:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:237:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:238:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:238:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:240:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:240:7: warning: passing argument 2 of 'setto' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:196:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:241:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:241:7: warning: passing argument 2 of 'setto' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:196:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:242:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:242:7: warning: passing argument 2 of 'setto' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:196:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:249:7: warning: passing argument 2 of 'setto' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:196:13: note: expected 'char *' but argument is of type 'const char *'
porter.c: In function 'step1c':
porter.c:257:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c: In function 'step2':
porter.c:267:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:267:4: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:268:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:268:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:270:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:270:4: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:271:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:271:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:273:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:273:4: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:275:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:275:4: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:280:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:280:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:281:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:281:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:282:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:282:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:283:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:283:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:285:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:285:4: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:286:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:286:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:287:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:287:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:289:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:289:4: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:290:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:290:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:291:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:291:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:292:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:292:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:294:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:294:4: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:295:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:295:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:296:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:296:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:298:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:298:4: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c: In function 'step3':
porter.c:308:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:308:4: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:309:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:309:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:310:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:310:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:312:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:312:4: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:314:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:314:4: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:315:14: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:315:14: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c:317:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:317:4: warning: passing argument 2 of 'r' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:205:13: note: expected 'char *' but argument is of type 'const char *'
porter.c: In function 'step4':
porter.c:325:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:326:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:327:17: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:328:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:329:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:330:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:331:17: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:332:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:333:17: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:334:17: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:335:17: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:336:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:337:17: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:339:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:340:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:341:17: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:342:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:343:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
porter.c:344:7: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]
porter.c:182:12: note: expected 'char *' but argument is of type 'const char *'
compiling porter_wrap.c
In file included from c:/Ruby21-x64/include/ruby-2.1.0/ruby.h:33:0,
                 from porter_wrap.c:1:
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:109:14: error: size of array 'ruby_check_sizeof_voidp' is negative
In file included from c:/Ruby21-x64/include/ruby-2.1.0/ruby.h:33:0,
                 from porter_wrap.c:1:
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h: In function 'rb_obj_wb_unprotect':
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:1234:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:1235:6: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:1238:2: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h: In function 'rb_obj_written':
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:1253:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h: In function 'rb_num2char_inline':
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:1324:35: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:1324:35: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:1324:35: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:1325:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:1325:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:1325:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h: In function 'rb_class_of':
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:1642:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h: In function 'rb_type':
c:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:1659:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
porter_wrap.c: In function 'stem_word':
porter_wrap.c:26:16: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
porter_wrap.c:26:16: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
porter_wrap.c:26:16: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
porter_wrap.c:27:16: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
porter_wrap.c:27:16: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
porter_wrap.c:27:16: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
porter_wrap.c:27:34: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
porter_wrap.c:27:34: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
porter_wrap.c:27:34: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
porter_wrap.c:28:7: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
porter_wrap.c:28:7: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
porter_wrap.c:28:7: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
porter_wrap.c:20:17: warning: unused variable 'i' [-Wunused-variable]
make: *** [porter_wrap.o] Error 1

make failed, exit code 2
```

**Comment by ZhipengZeng** [comment]
Also, the content in my  `_config.yml` is 
```
baseurl: /AAA-Blog

- C:/Ruby21-x64
# Build settings
highlighter: true
highlighter: rouge
```

and my Gemfile:
```
source "https://rubygems.org"
gem 'nokogiri'
gem 'rack', '~>1.1'
gem 'rspec', :require => 'spec'
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
#require 'json'
require 'open-uri'
require 'rubygems'
require 'bundler/setup'
gem 'github-pages'
gem 'linguist', '~> 4.3.1'
#versions = JSON.parse(open('https://pages.github.com/versions.json').read)
#gem 'github-pages', versions['github-pages']

require 'rugged'
require 'linguist'
```

any improvements to me?

Thanks in advance for my questions!

**Comment by parkr** [comment]
The problem is this:

```text
You have to install development tools first.
```

You don't have the Ruby development tools. @jekyll/windows, should that be added to the guide?

**Comment by ZhipengZeng** [comment]
Do you mean DevKit?  I already installed it first

**Comment by kleinfreund** [comment]
Do you have the devkit on the path as well? It needs to be there, too.

**Comment by ZhipengZeng** [comment]
Yes, c:/devkit is already included in PATH, both user and system
And `ruby dk.rb init`  and  `ruby dk.rb install` were successful

**Comment by kleinfreund** [comment]
Can you please do `ruby -v` and `gem -v`? I also do `gem update --system` from time to time to make sure the Ruby Gems gem is up to date.

**Comment by ZhipengZeng** [comment]
Trust me, I've tried this method before I asked here...
They're up to date.
^.^

**Comment by kleinfreund** [comment]
Huh, not sure. Last guess: Try it with `source "http://rubygems.org"` (protocol changed to http) in your Gemfile.

**Comment by ZhipengZeng** [comment]
Thank you all the same, bro, I went to bed though.
I'll @ you with result tomorrow.

**Comment by kleinfreund** [comment]
Also, I just noticed. Can you go to `C:\devkit` and open the _config.yml there? Because that's the file that should contain `- C:/Ruby21-x64`. I knew your project configuration confused me.

**Comment by ZhipengZeng** [comment]
I have solved this issue already.
After I deleted the whole folder of `C:/Ruby21-x64` and `C:/DevKit`,
I was gonna re-download and re-install them.
Then I found out that my previous devkit version actually matched ruby20.
That's the problem.
Thank you guys!  @parkr  @kleinfreund
