### ISSUE TITLE
Jekyll conflicts with GIFLIB

### ISSUE THREAD

**Issue by dongli** [jekyll/jekyll#3429]
After I installed `giflib` and set the corresponding `DYLD_LIBRARY_PATH` in Mac OS X, `bundle exec jekyll serve` shows the following error:
```
Configuration file: /Users/dongli/Works/packman-website/_config.yml
            Source: /Users/dongli/Works/packman-website
       Destination: /Users/dongli/Works/packman-website/_site
      Generating... 
                    done.
/Library/Ruby/Gems/2.0.0/gems/hitimes-1.2.2/lib/hitimes.rb:37:in `require': cannot load such file -- hitimes/hitimes (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/hitimes-1.2.2/lib/hitimes.rb:37:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/hitimes-1.2.2/lib/hitimes.rb:32:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/timers-4.0.1/lib/timers/group.rb:4:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/timers-4.0.1/lib/timers/group.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/timers-4.0.1/lib/timers.rb:4:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/timers-4.0.1/lib/timers.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/receivers.rb:3:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/receivers.rb:3:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid.rb:475:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid.rb:475:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/listen-2.8.5/lib/listen.rb:1:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/listen-2.8.5/lib/listen.rb:1:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-watch-1.2.1/lib/jekyll/watcher.rb:26:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-watch-1.2.1/lib/jekyll/watcher.rb:26:in `build_listener'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-watch-1.2.1/lib/jekyll/watcher.rb:7:in `watch'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:67:in `watch'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:37:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'
```

**Comment by parkr** [comment]
What gems are in your bundle? This is a problem with Celluloid, which Jekyll uses via jekyll-watch and listen. Check out #3092. Try running `bundle install` again.

**Comment by dongli** [comment]
@parkr Just `gem 'github-pages'`. When remove `giflib`, the problem disappeared. Is there any possibility that the libraries of `giflib` conflict with `jekyll`?
```
$ ls /opt/packman/giflib/4.1.6/0/lib/
libgif.4.1.6.dylib libgif.a           libgif.la
libgif.4.dylib     libgif.dylib
```
