### ISSUE TITLE
Errno::EISDIR error when building site using 3.0 beta

### ISSUE THREAD

**Issue by troyswanson** [jekyll/jekyll#3446]
```
Troys-Air:www troy$ jekyll --version
jekyll 3.0.0-beta1
Troys-Air:www troy$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
```

```
Troys-Air:www troy$ jekyll build --trace
Configuration file: /Users/troy/Projects/ObjectRocket/www/_config.yml
            Source: /Users/troy/Projects/ObjectRocket/www
       Destination: /Users/troy/Projects/ObjectRocket/www/_site
 Incremental build: enabled
      Generating... 
/Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/convertible.rb:256:in `initialize': Is a directory @ rb_sysopen - /Users/troy/Projects/ObjectRocket/www/_site/blog/company/in-memory-mongodb-concurrency-testing-on-objectrocket (Errno::EISDIR)
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/convertible.rb:256:in `open'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/convertible.rb:256:in `write'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:326:in `block in write'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:485:in `block (2 levels) in each_site_file'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:484:in `each'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:484:in `block in each_site_file'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:483:in `each'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:483:in `each_site_file'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:325:in `write'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:57:in `process'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/command.rb:28:in `process_site'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/commands/build.rb:58:in `build'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/bin/jekyll:17:in `<top (required)>'
	from /Users/troy/.rbenv/versions/2.2.0/bin/jekyll:23:in `load'
	from /Users/troy/.rbenv/versions/2.2.0/bin/jekyll:23:in `<main>'
```

I'm afraid I can't post a link to the repo since it's private. I'm happy to provide any additional info, though.

**Comment by troyswanson** [comment]
For reference, it builds just fine with Jekyll 2.5.3

```
Troys-Air:www troy$ jekyll --version
jekyll 2.5.3
Troys-Air:www troy$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
```

```
Troys-Air:www troy$ jekyll build --trace
Configuration file: /Users/troy/Projects/ObjectRocket/www/_config.yml
            Source: /Users/troy/Projects/ObjectRocket/www
       Destination: /Users/troy/Projects/ObjectRocket/www/_site
      Generating... 
                    done.
 Auto-regeneration: disabled. Use --watch to enable.
```

**Comment by parkr** [comment]
What happens if you run it with `--full-rebuild`?

**Comment by troyswanson** [comment]
Same thing

```
Troys-Air:www troy$ jekyll --version
jekyll 3.0.0-beta1
Troys-Air:www troy$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
```

```
Troys-Air:www troy$ jekyll build --trace --full-rebuild
Configuration file: /Users/troy/Projects/ObjectRocket/www/_config.yml
            Source: /Users/troy/Projects/ObjectRocket/www
       Destination: /Users/troy/Projects/ObjectRocket/www/_site
 Incremental build: disabled
      Generating... 
/Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/convertible.rb:256:in `initialize': Is a directory @ rb_sysopen - /Users/troy/Projects/ObjectRocket/www/_site/blog/company/in-memory-mongodb-concurrency-testing-on-objectrocket (Errno::EISDIR)
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/convertible.rb:256:in `open'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/convertible.rb:256:in `write'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:326:in `block in write'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:485:in `block (2 levels) in each_site_file'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:484:in `each'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:484:in `block in each_site_file'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:483:in `each'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:483:in `each_site_file'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:325:in `write'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/site.rb:57:in `process'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/command.rb:28:in `process_site'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/commands/build.rb:58:in `build'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/troy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta1/bin/jekyll:17:in `<top (required)>'
	from /Users/troy/.rbenv/versions/2.2.0/bin/jekyll:23:in `load'
	from /Users/troy/.rbenv/versions/2.2.0/bin/jekyll:23:in `<main>'
```

**Comment by parkr** [comment]
If you `rm -r _site`, this should go away. The destination of the file being written is a directory instead of a file and Ruby can't figure out wtf to do.

**Comment by troyswanson** [comment]
:mag_right: Nice, dude. Thanks!
