### ISSUE TITLE
jekyll 2.4.0 | Error:  invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by phillipadsmith** [jekyll/jekyll#3451]
Getting this when reading from a .csv in _data:

```
project@web ~/git-repo $ bundle exec jekyll build --config _config.yml,_config.development.yml -d ~/project/www/ --trace
Configuration file: _config.yml
Configuration file: _config.development.yml
            Source: /var/home/project/git-repo
       Destination: /var/home/project/www/
      Generating...
/var/home/project/.rbenv/versions/2.1.2/lib/ruby/2.1.0/csv.rb:1783:in `sub!': invalid byte sequence in US-ASCII (ArgumentError)
        from /var/home/project/.rbenv/versions/2.1.2/lib/ruby/2.1.0/csv.rb:1783:in `block in shift'
        from /var/home/project/.rbenv/versions/2.1.2/lib/ruby/2.1.0/csv.rb:1777:in `loop'
        from /var/home/project/.rbenv/versions/2.1.2/lib/ruby/2.1.0/csv.rb:1777:in `shift'
        from /var/home/project/.rbenv/versions/2.1.2/lib/ruby/2.1.0/csv.rb:1719:in `each'
        from /var/home/project/.rbenv/versions/2.1.2/lib/ruby/2.1.0/csv.rb:1733:in `to_a'
        from /var/home/project/.rbenv/versions/2.1.2/lib/ruby/2.1.0/csv.rb:1733:in `read'
        from /var/home/project/.rbenv/versions/2.1.2/lib/ruby/2.1.0/csv.rb:1325:in `block in read'
        from /var/home/project/.rbenv/versions/2.1.2/lib/ruby/2.1.0/csv.rb:1268:in `open'
        from /var/home/project/.rbenv/versions/2.1.2/lib/ruby/2.1.0/csv.rb:1325:in `read'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:229:in `block in read_data_to'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:219:in `each'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:219:in `read_data_to'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:202:in `read_data'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:123:in `read'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:44:in `process'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/command.rb:28:in `process_site'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:55:in `build'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:33:in `process'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:17:in `block (2 levels) in init_with_program'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `call'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `block in execute'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `each'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `execute'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/mercenary-0.3.4/lib/mercenary/program.rb:35:in `go'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/mercenary-0.3.4/lib/mercenary.rb:22:in `program'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
        from /var/home/project/git-repo/_vendor/ruby/2.1.0/bin/jekyll:23:in `load'
```

Oddly enough, I don't get this when building the project locally. Set-up is the same:
jekyll 2.4.0
ruby 2.1.2p95

Any pointers on where to start investigating this?

Phillip.

**Comment by phillipadsmith** [comment]
Different CSV files work fine on the remote host (Gentoo), but what's odd is that the CSV in question works fine on my local machine (OSX). As mentioned, the set-up otherwise is identical: rbenv + bundler, so same ruby version, gems, etc.

**Comment by parkr** [comment]
Encoding bug :frowning:

**Comment by phillipadsmith** [comment]
@parkr Let me know if there's anything that I can provide to assist.

**Comment by parkr** [comment]
@phillipadsmith Can you please try it with `master`?

**Comment by parkr** [comment]
If it fails with master, please try this change on master and try again:

```diff
diff --git a/lib/jekyll/site.rb b/lib/jekyll/site.rb
index 3af4767..c57d451 100644
--- a/lib/jekyll/site.rb
+++ b/lib/jekyll/site.rb
@@ -262,19 +262,19 @@ module Jekyll
         end
       end
     end
-    
+
     # Determines how to read a data file.
     #
     # Returns the contents of the data file.
     def read_data_file(path)
       case File.extname(path).downcase
       when '.csv'
-        CSV.read(path, :headers => true).map(&:to_hash)
+        CSV.read(path, :headers => true, :encoding => config['encoding']).map(&:to_hash)
       else
         SafeYAML.load_file(path)
       end
     end
-      
+
     # Read in all collections specified in the configuration
     #
     # Returns nothing.
```

**Comment by phillipadsmith** [comment]
@parkr: jekyll 3.0.0-beta1 | Error:  invalid byte sequence in US-ASCII

But, no error when I use the patch above. :)
