### ISSUE TITLE
cannot load such file -- jemoji (LoadError)

### ISSUE THREAD

**Issue by jastuccio** [jekyll/jekyll#3541]
I cannot get the Jekyll server running.  ```bundle exec jekyll build --trace``` returns this error message:

```sh
/Users/joe/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jemoji (LoadError)
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/joe/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /Users/joe/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `load'
	from /Users/joe/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `<main>'
	from /Users/joe/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/joe/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by envygeeks** [comment]
Add `jemoji` to your Gemfile and `bundle install` or remove `jemoji` from your `_config.yml`

**Comment by jastuccio** [comment]
Ty that error is gone.  Now I am getting a different one and opened an issue for it.

**Comment by sourabhverma** [comment]
Installing ```jemoji``` resolved my issue too. Apparently, theme was using it 

https://rubygems.org/gems/gemoji
