### ISSUE TITLE
Clean checkout has test failures

### ISSUE THREAD

**Issue by nickburlett** [jekyll/jekyll#3587]
After a brand-new clone of the repository, there are a couple of tests that fail: 

```
> bundle exec rake test
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I"lib:lib:test" -I"/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib" "/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/**/test_*.rb" 

# Running tests with run options --seed 16779:

...............................................................................................................................................................................................E................................E...........................................................................................................................................................................................................................................................................................................................................

Finished tests in 57.428560s, 9.6816 tests/s, 16.5075 assertions/s.

Error:
TestTags#test_: relative include tag with variable and liquid filters with symlink'd include should not allow symlink includes. :
Errno::ENOENT: No such file or directory - tmp/pages-test
    /Users/nick/Projects/jekyll-learn/jekyll/test/test_tags.rb:750:in `initialize'
    /Users/nick/Projects/jekyll-learn/jekyll/test/test_tags.rb:750:in `open'
    /Users/nick/Projects/jekyll-learn/jekyll/test/test_tags.rb:750:in `block (3 levels) in <class:TestTags>'
    /Library/Ruby/Gems/2.0.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
    /Library/Ruby/Gems/2.0.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'

Error:
TestTags#test_: include tag with parameters with symlink'd include should not allow symlink includes. :
Errno::ENOENT: No such file or directory - tmp/pages-test
    /Users/nick/Projects/jekyll-learn/jekyll/test/test_tags.rb:467:in `initialize'
    /Users/nick/Projects/jekyll-learn/jekyll/test/test_tags.rb:467:in `open'
    /Users/nick/Projects/jekyll-learn/jekyll/test/test_tags.rb:467:in `block (3 levels) in <class:TestTags>'
    /Library/Ruby/Gems/2.0.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
    /Library/Ruby/Gems/2.0.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'

556 tests, 948 assertions, 0 failures, 2 errors, 0 skips
Coverage report generated for Unit Tests to /Users/nick/Projects/jekyll-learn/jekyll/coverage. 1914 / 2218 LOC (86.29%) covered.
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test" -I"/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib" "/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/**/test_*.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
````````

After making a new "tmp" directory, it passes:

````
> mkdir tmp
> bundle exec rake test
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I"lib:lib:test" -I"/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib" "/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/**/test_*.rb" 

# Running tests with run options --seed 43952:

............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished tests in 62.715838s, 8.8654 tests/s, 15.2115 assertions/s.

556 tests, 954 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /Users/nick/Projects/jekyll-learn/jekyll/coverage. 1914 / 2218 LOC (86.29%) covered.
````````

**Comment by parkr** [comment]
We use script/test to run the tests and it takes care of these pre req's. Looks like there's already a PR in to roll that into rake.

**Comment by chrisfinazzo** [comment]
This also came up in #3567 as I was working through things, good to know it's not just me. I will point out that I did get an error related to CoffeeScript compilation:

As @nickburlett said, <pre>mkdir tmp</pre> takes care of the errors, but this failure still shows up.


<pre>Failure:
TestCoffeeScript#test_: converting CoffeeScript should produce JS.  [/Users/Chris/Documents/Jekyll/test/test_coffeescript.rb:44]
Minitest::Assertion: --- expected
+++ actual
@@ -9,13 +9,13 @@
       return square(x) * x;
     };
     cubes = (function() {
-      var i, len, results;
-      results = [];
-      for (i = 0, len = list.length; i < len; i++) {
-        num = list[i];
-        results.push(math.cube(num));
+      var _i, _len, _results;
+      _results = [];
+      for (_i = 0, _len = list.length; _i < _len; _i++) {
+        num = list[_i];
+        _results.push(math.cube(num));
       }
-      return results;
+      return _results;
     })();
     if (typeof elvis !== \"undefined\" && elvis !== null) {
       return alert(\"I knew it!\");
</pre>

**Comment by parkr** [comment]
@chrisfinazzo I don't encounter that error. Are you running `script/cibuild`? A new version of CoffeeScript (1.9) changed some things.

**Comment by chrisfinazzo** [comment]
Oops, was just using `rake test`. Is this recommended for all changes or just those that modify things in `/lib` or `/features`?

A fresh checkout + `script/cibuild` and everything seems to work.

**Comment by parkr** [comment]
> Oops, was just using rake test. Is this recommended for all changes or just those that modify things in /lib or /features?

`rake test` doesn't use the bundled gems, it could use any version. It's good practice to have a Gemfile for your ruby projects and to run them with `bundle exec <command>`.

For us, we use `script/cibuild` to run the whole test suite or just `script/test [test_file.rb]` to just run the unit tests.

**Comment by chrisfinazzo** [comment]
Not thinking clearly today...I knew this already 😉.

I do this inside of `build.sh` for my personal site. Not sure why I didn't `bundle exec` here.

Need ☕️.
