### ISSUE TITLE
{{ site.baseurl }} cannot be pre-processed in SCSS files because YAML front-matter causes an error

### ISSUE THREAD

**Issue by manastungare** [jekyll/jekyll#3646]
See also #3408 .

I need to have Jekyll correctly pre-process the `{{ site.baseurl }}` marker in SCSS files. To do this, I added YAML front-matter to my SASS partials. This causes Jekyll to fail to parse that entire file.

Removing the front-matter makes it parse correctly, but `{{ site.baseurl }}` does not get replaced.

_sass/page.scss:
```
---
---

.banner {
  background-image: url('{{ site.baseurl }}/media/banner.png');
}
```

all.css:
```
---
---

@import "page.scss";
```

Error:
```
  Conversion error: Jekyll::Converters::Scss encountered an error converting 'all.scss'.
  Conversion error: Invalid CSS after "": expected selector, was "---"
/Users/manas/Dropbox/Manas/Web/HermitCrab/_sass/reset.scss:1: Invalid CSS after "": expected selector, was "---" (Sass::SyntaxError)
	from (sass):1
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/scss/parser.rb:1165:in `expected'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/scss/parser.rb:1101:in `expected'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/scss/parser.rb:1081:in `expr!'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/scss/static_parser.rb:20:in `parse_selector'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:424:in `visit_rule'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/stack.rb:79:in `block in with_base'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/stack.rb:79:in `with_base'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `visit'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:325:in `block (2 levels) in visit_import'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:325:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:325:in `block in visit_import'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/stack.rb:88:in `block in with_import'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/stack.rb:88:in `with_import'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/stack.rb:79:in `block in with_base'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/stack.rb:79:in `with_base'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `visit'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `visit_children'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `block in visit'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:157:in `visit'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:8:in `visit'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/root_node.rb:36:in `css_tree'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/tree/root_node.rb:20:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass/engine.rb:268:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.13/lib/sass.rb:57:in `compile'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-sass-converter-1.2.0/lib/jekyll/converters/scss.rb:93:in `convert'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:67:in `block in transform'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:65:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:65:in `reduce'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:65:in `transform'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:234:in `do_layout'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/page.rb:122:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:269:in `block in render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:268:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:268:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:46:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/command.rb:28:in `process_site'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:33:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'
```

**Comment by parkr** [comment]
Remove the YAML front matter in your partial and try again.

**Comment by manastungare** [comment]
Removing the YAML front matter leaves {{ site.baseurl }} verbatim in the output file. Sorry for being unclear.

**Comment by parkr** [comment]
You may only be able to use Liquid in the main `all.scss` file. Try assigning it to an Sass variable.

**Comment by parkr** [comment]
I think that's your trouble. I know @imathis has gotten it to work so there's hope!

**Comment by charliesneath** [comment]
@parkr I'm also trying to get `{{ site.baseurl }}` to output in an image path.  

In the above example, is the `all.css` file the equivalent of the default `main.css` file in Jekyll projects? When I add `$baseurl: {{ site.baseurl }};` to my `main.css` file (which has the front matter), I get the following error: 

`Invalid CSS after "$baseurl: ": expected expression (e.g. 1px, bold), was ";" on line 27`.

The `{{ site.baseurl }}` variable does not seem to be rendering correctly. Any ideas?

**Comment by rdyar** [comment]
This post worked for me:
http://stackoverflow.com/questions/20037266/how-to-use-jekyll-baseurl-in-css-files

in the main.scss file where you import all the sass partials you can put `$baseurl:"{{ site.baseurl }}";` at the top to declare a variable, then in the sass file do `background: url($baseurl + "/my/image.svg");`

**Comment by qaisjp** [comment]
And what @rdyar suggested/x-posted works if you declare the variable in a main file, and then try to use it inside an include. ☑️
