### ISSUE TITLE
Jekyll 3 beta2 error: undefined method getConverterImpl

### ISSUE THREAD

**Issue by pepelsbey** [jekyll/jekyll#3662]
Since beta 1 (actually since the first alpha) of Jekyll 3 I can’t build [Dev.Opera](https://dev.opera.com) site because of following error:
```sh
$ jekyll build
Configuration file: /Users/pepelsbey/Sites/dev.opera/_config.yml
            Source: /Users/pepelsbey/Sites/dev.opera
       Destination: /Users/pepelsbey/Sites/dev.opera/_site
 Incremental build: enabled
      Generating... 
  Liquid Exception: undefined method `getConverterImpl' for #<Jekyll::Site:0x007fa25e0b38c8> in _layouts/author.html
jekyll 3.0.0.pre.beta2 | Error:  undefined method `getConverterImpl' for #<Jekyll::Site:0x007fa25e0b38c8>
```
Here’s `_layouts/author.html` and the rest source code on [operasoftware/devopera](https://github.com/operasoftware/devopera)
```liquid
---
layout: default
---

<main block="layout">
	<div elem="content">
		<article block="content" role="main">
			<h1 elem="title">{{ page.title | markdownline }}</h1>
			<p>{% include link.html link=page.link %}</p>
			{{ content }}
			<h2>{{ page.title | split: ' ' | first | append: '’s' | replace: 's’s','s’' }} articles:</h2>
			<ul>
{% assign author = page.url | split: '/' | last %}
{% for post in site.posts %}
	{% if post.authors contains author %}
		{% unless post.categories[1] %}
				<li><a href="{{ post.url }}">{{ post.title | markdownline }}</a></li>
		{% endunless %}
	{% endif %}
{% endfor %}
			</ul>
		</article>
	</div>
	<div elem="aside">
		<p block="authors">
			<a href="{{ page.link }}">
				<img elem="picture" src="/authors/{{ page.url | split: '/' | last }}.jpg" alt="{{ page.title }}">
			</a>
		</p>
	</div>
</main>
```
Previously, with beta 1, I saw a bit different output blaming `entry.html` (but it has changed since)
```sh
Jekyll output:
Configuration file: /Users/pepelsbey/Sites/dev.opera/_config.yml
            Source: /Users/pepelsbey/Sites/dev.opera
       Destination: /Users/pepelsbey/Sites/dev.opera/_site
 Incremental build: enabled
      Generating... 
jekyll 3.0.0-beta1 | Error:  undefined method `getConverterImpl' for #<Jekyll::Site:0x007fc235596420>
Warning: Command failed:   Liquid Exception: undefined method `getConverterImpl' for #<Jekyll::Site:0x007fc235596420> in _layouts/entry.html
 Use --force to continue.
Error: Command failed:   Liquid Exception: undefined method `getConverterImpl' for #<Jekyll::Site:0x007fc235596420> in _layouts/entry.html
 
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
 
Aborted due to warnings.
```
I’ll be more that happy to use all new shiny features of Jekyll 3, but for now it seems like I’m going to stuck on 2.x branch. I believe Dev.Opera is one of the biggest sites using Jekyll so I really hope you could help us to figure this out.

**Comment by parkr** [comment]
We changed the method name! Are you using plugins?

**Comment by pepelsbey** [comment]
[We are](https://github.com/operasoftware/devopera/tree/master/_plugins), but only tags.rb is the real one

**Comment by parkr** [comment]
Fixed here: https://github.com/operasoftware/devopera/pull/269

**Comment by pepelsbey** [comment]
Thank you!
