### ISSUE TITLE
Incremental regeneration prevents rebuilding if a file is deleted... ever.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3716]
If a file is deleted (either before, after or even during Jekyll) then incremental regeneration falls down trying to read a file that doesn't exist, it does not even try to correct this behavior, it just prevents Jekyll from loading at all.

```shell
docker run -p 127.0.0.1:4000:4000 --volume $(pwd):/srv/jekyll --name jekyll --rm -it jekyll/jekyll:beta jekyll serve --watch --trace
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: enabled
      Generating... 
/usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:105:in `mtime': No such file or directory @ rb_file_s_mtime - /srv/jekyll/_layouts/post.html (Errno::ENOENT)
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:105:in `modified?'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:101:in `block in modified?'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:100:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:100:in `modified?'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:79:in `source_modified_or_dest_missing?'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:22:in `regenerate?'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:189:in `block in write'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:326:in `block (2 levels) in each_site_file'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:325:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:325:in `block in each_site_file'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:324:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:324:in `each_site_file'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:188:in `write'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:59:in `process'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/command.rb:28:in `process_site'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/commands/build.rb:60:in `build'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/commands/build.rb:35:in `process'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

/cc @alfredxing

**Comment by alfredxing** [comment]
Definitely a bug. Should be a simple fix though&mdash;just add a check to see if the file is deleted?

**Comment by envygeeks** [comment]
I think it's that easy, I'd be happy to try and see what i could work out tonight if you don't have time since I'm working on my own site and ran into this bug when I was porting it back into Jekyll so I'll probably end up breaking Jekyll in plenty of ways and trying to sort out how to fix problems.

**Comment by alfredxing** [comment]
I'm working on it already, PR going out soon! :)
