### ISSUE TITLE
Random test failures with SafeYAML and configuration tests.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3794]
```
Using worker: worker-linux-docker-7e8d2c97.prod.travis-ci.org:travis-linux-2

Build system information
Build language: ruby
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"

$ git clone --depth=50 --branch=update-dependencies git://github.com/jekyll/jekyll.git jekyll/jekyll
Cloning into 'jekyll/jekyll'...
remote: Counting objects: 1255, done.
remote: Compressing objects: 100% (948/948), done.
remote: Total 1255 (delta 549), reused 733 (delta 233), pack-reused 0
Receiving objects: 100% (1255/1255), 902.99 KiB | 0 bytes/s, done.
Resolving deltas: 100% (549/549), done.
Checking connectivity... done.
$ cd jekyll/jekyll
$ git checkout -qf 9c4bf19c71402760f07fa045720cbd9c4f6ccdb7

This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

Setting environment variables from .travis.yml
$ export TEST_SUITE=test

Setting up build cache
$ export CASHER_DIR=$HOME/.casher
$ Installing caching utilities
attempting to download cache archive
fetching update-dependencies/cache--rvm-2.2--gemfile-Gemfile.tbz
fetching master/cache--rvm-2.2--gemfile-Gemfile.tbz
found cache
$ rvm use 2.2 --install --binary --fuzzy
Using /home/travis/.rvm/gems/ruby-2.2.0
$ export BUNDLE_GEMFILE=$PWD/Gemfile
$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
$ rvm --version
rvm 1.26.10 (latest-minor) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
Bundler version 1.7.9
$ gem --version
2.4.5
adding /home/travis/build/jekyll/jekyll/vendor/bundle to cache
$ bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
Fetching gem metadata from https://rubygems.org/...........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.7.0
Using thread_safe 0.3.5
Using addressable 2.3.8
Using ansi 1.5.0
Using blankslate 2.1.2.4
Using builder 3.2.2
Using hitimes 1.2.2
Using fast-stemmer 1.0.2
Using coderay 1.1.0
Using coffee-script-source 1.9.1.1
Using execjs 2.5.2
Using colorator 0.1
Using multi_json 1.11.1
Using diff-lcs 1.2.5
Using multi_test 0.1.2
Using docile 1.1.5
Using ffi 1.9.8
Using sass 3.4.14
Using rb-fsevent 0.9.5
Using kramdown 1.7.0
Using liquid 3.0.3
Using rouge 1.9.0
Using mercenary 0.3.5
Using safe_yaml 1.0.4
Using jekyll-gist 1.2.1
Using jekyll-paginate 1.1.0
Using jekyll_test_plugin 0.1.0
Using jekyll_test_plugin_malicious 0.1.0
Using method_source 0.8.2
Using minitest-profile 0.0.2
Using ruby-progressbar 1.7.5
Using posix-spawn 0.3.11
Using power_assert 0.2.3
Using slop 3.6.0
Using yajl-ruby 1.2.1
Using rdiscount 2.1.8
Using rdoc 4.2.0
Using redcarpet 3.3.1
Using redgreen 1.2.2
Using rspec-support 3.3.0
Using shoulda-context 1.2.1
Using simplecov-html 0.10.0
Using bundler 1.7.9
Using tzinfo 1.2.2
Using launchy 2.4.3
Using parslet 1.5.0
Using timers 4.0.1
Using classifier-reborn 2.0.3
Using coffee-script 2.4.1
Using gherkin 2.12.2
Using rb-inotify 0.9.5
Using jekyll-sass-converter 1.3.0
Using liquid-c 3.0.0
Using minitest-reporters 1.0.17
Using test-unit 3.1.2
Using pry 0.10.1
Using pygments.rb 0.6.3
Using rspec-mocks 3.3.0
Using simplecov 0.10.0
Installing activesupport 4.2.2
Installing mime-types 2.6.1
Using toml 0.1.2
Using celluloid 0.16.0
Using jekyll-coffeescript 1.0.1
Using shoulda-matchers 2.8.0
Installing listen 2.10.1
Using shoulda 3.5.0
Using jekyll-watch 1.2.1
Installing cucumber-core 1.1.3
Using jekyll 3.0.0.pre.beta6 from source at .
Installing cucumber 2.0.0
Your bundle is complete!
It was installed into ./vendor/bundle
$ bundle update
Fetching gem metadata from https://rubygems.org/...........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.7.0
Using thread_safe 0.3.5
Using addressable 2.3.8
Using ansi 1.5.0
Using builder 3.2.2
Using hitimes 1.2.2
Using fast-stemmer 1.0.2
Using blankslate 2.1.2.4
Using coffee-script-source 1.9.1.1
Using coderay 1.1.0
Using execjs 2.5.2
Using colorator 0.1
Using diff-lcs 1.2.5
Using multi_json 1.11.1
Using docile 1.1.5
Using multi_test 0.1.2
Using ffi 1.9.8
Using rb-fsevent 0.9.5
Using kramdown 1.7.0
Using sass 3.4.14
Using liquid 3.0.3
Using mercenary 0.3.5
Using safe_yaml 1.0.4
Using rouge 1.9.0
Using jekyll-gist 1.2.1
Using jekyll_test_plugin 0.1.0
Using jekyll_test_plugin_malicious 0.1.0
Using jekyll-paginate 1.1.0
Using method_source 0.8.2
Using minitest-profile 0.0.2
Using ruby-progressbar 1.7.5
Using mime-types 2.6.1
Using posix-spawn 0.3.11
Using power_assert 0.2.3
Using yajl-ruby 1.2.1
Using slop 3.6.0
Using rdiscount 2.1.8
Using rdoc 4.2.0
Using redcarpet 3.3.1
Using rspec-support 3.3.0
Using redgreen 1.2.2
Using simplecov-html 0.10.0
Using bundler 1.7.9
Using shoulda-context 1.2.1
Using tzinfo 1.2.2
Using launchy 2.4.3
Using classifier-reborn 2.0.3
Using timers 4.0.1
Using parslet 1.5.0
Using coffee-script 2.4.1
Using gherkin 2.12.2
Using rb-inotify 0.9.5
Using liquid-c 3.0.0
Using jekyll-sass-converter 1.3.0
Using minitest-reporters 1.0.17
Using test-unit 3.1.2
Using pry 0.10.1
Using pygments.rb 0.6.3
Using simplecov 0.10.0
Using rspec-mocks 3.3.0
Using activesupport 4.2.2
Using toml 0.1.2
Using cucumber-core 1.1.3
Using celluloid 0.16.0
Using jekyll-coffeescript 1.0.1
Using listen 2.10.1
Using shoulda-matchers 2.8.0
Using cucumber 2.0.0
Using jekyll-watch 1.2.1
Using shoulda 3.5.0
Using jekyll 3.0.0.pre.beta6 from source at .
Your bundle is updated!
$ script/cibuild
 ---------------------------------------------------------- 
          _   ______   _  __ __     __  _        _          
         | | |  ____| | |/ / \ \   / / | |      | |         
         | | | |__    | ' /   \ \_/ /  | |      | |         
     _   | | |  __|   |  <     \   /   | |      | |         
    | |__| | | |____  | . \     | |    | |____  | |____     
     \____/  |______| |_|\_\    |_|    |______| |______|    
                                                            
 ---------------------------------------------------------- 
/home/travis/.rvm/rubies/ruby-2.2.0/bin/ruby
+ruby -S bundle exec rake TESTOPTS=--profile test
/home/travis/.rvm/rubies/ruby-2.2.0/bin/ruby -I"lib:lib:test"  "/home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/**/test_*.rb" --profile

# Running tests with run options --profile --seed 61118:

.............................................................................................................................................................................................................................................................................................................................F.......................................
...........................................................................................................................EE.E.E..E..............................................................................................

Finished tests in 57.591647s, 10.1230 tests/s, 17.1379 assertions/s.


Failure:
TestSite#test_: configuring sites should have an array for plugins by default.  [/home/travis/build/jekyll/jekyll/test/test_site.rb:7]
Minitest::Assertion: --- expected
+++ actual
@@ -1 +1 @@
-["/home/travis/build/jekyll/jekyll/_plugins"]
+["/home/travis/build/jekyll/jekyll/test/source/_plugins"]


Error:
TestConfiguration#test_: loading configuration should fire warning with no _config.yml. :
RSpec::Mocks::MockExpectationError: SafeYAML received :load_file with unexpected arguments
  expected: ("/home/travis/build/jekyll/jekyll/_config.yml")
       got: ("/home/travis/build/jekyll/jekyll/test/source/_config.yml")
 Please stub a default value first if message might be received with other args as well. 

    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:86:in `block in <module:Support>'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `call'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `notify_failure'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:320:in `notify'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:304:in `__raise'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:63:in `raise_missing_default_stub_error'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:206:in `raise_missing_default_stub_error'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:191:in `message_received'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:321:in `message_received'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:120:in `safe_load_file'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:154:in `read_config_file'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:179:in `block in read_config_files'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:178:in `each'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:178:in `read_config_files'
    /home/travis/build/jekyll/jekyll/lib/jekyll.rb:105:in `configuration'
    /home/travis/build/jekyll/jekyll/test/test_configuration.rb:120:in `block (2 levels) in <class:TestConfiguration>'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'

Error:
TestConfiguration#test_: loading configuration should load configuration as hash. :
RSpec::Mocks::MockExpectationError: SafeYAML received :load_file with unexpected arguments
  expected: ("/home/travis/build/jekyll/jekyll/_config.yml")
       got: ("/home/travis/build/jekyll/jekyll/test/source/_config.yml")
 Please stub a default value first if message might be received with other args as well. 

    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:86:in `block in <module:Support>'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `call'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `notify_failure'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:320:in `notify'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:304:in `__raise'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:63:in `raise_missing_default_stub_error'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:206:in `raise_missing_default_stub_error'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:191:in `message_received'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:321:in `message_received'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:120:in `safe_load_file'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:154:in `read_config_file'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:179:in `block in read_config_files'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:178:in `each'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:178:in `read_config_files'
    /home/travis/build/jekyll/jekyll/lib/jekyll.rb:105:in `configuration'
    /home/travis/build/jekyll/jekyll/test/test_configuration.rb:126:in `block (2 levels) in <class:TestConfiguration>'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'

Error:
TestConfiguration#test_: loading config from external file should load default config if path passed is empty. :
RSpec::Mocks::MockExpectationError: SafeYAML received :load_file with unexpected arguments
  expected: ("/home/travis/build/jekyll/jekyll/_config.yml")
       got: ("/home/travis/build/jekyll/jekyll/test/source/_config.yml")
 Please stub a default value first if message might be received with other args as well. 

    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:86:in `block in <module:Support>'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `call'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `notify_failure'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:320:in `notify'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:304:in `__raise'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:63:in `raise_missing_default_stub_error'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:206:in `raise_missing_default_stub_error'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:191:in `message_received'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:321:in `message_received'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:120:in `safe_load_file'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:154:in `read_config_file'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:179:in `block in read_config_files'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:178:in `each'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:178:in `read_config_files'
    /home/travis/build/jekyll/jekyll/lib/jekyll.rb:105:in `configuration'
    /home/travis/build/jekyll/jekyll/test/test_configuration.rb:174:in `block (2 levels) in <class:TestConfiguration>'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'

Error:
TestConfiguration#test_: loading configuration should fire warning with bad config. :
RSpec::Mocks::MockExpectationError: SafeYAML received :load_file with unexpected arguments
  expected: ("/home/travis/build/jekyll/jekyll/_config.yml")
       got: ("/home/travis/build/jekyll/jekyll/test/source/_config.yml")
 Please stub a default value first if message might be received with other args as well. 

    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:86:in `block in <module:Support>'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `call'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `notify_failure'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:320:in `notify'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:304:in `__raise'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:63:in `raise_missing_default_stub_error'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:206:in `raise_missing_default_stub_error'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:191:in `message_received'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:321:in `message_received'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:120:in `safe_load_file'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:154:in `read_config_file'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:179:in `block in read_config_files'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:178:in `each'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:178:in `read_config_files'
    /home/travis/build/jekyll/jekyll/lib/jekyll.rb:105:in `configuration'
    /home/travis/build/jekyll/jekyll/test/test_configuration.rb:133:in `block (2 levels) in <class:TestConfiguration>'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'

Error:
TestConfiguration#test_: loading config from external file should load default config if no config_file is set. :
RSpec::Mocks::MockExpectationError: SafeYAML received :load_file with unexpected arguments
  expected: ("/home/travis/build/jekyll/jekyll/_config.yml")
       got: ("/home/travis/build/jekyll/jekyll/test/source/_config.yml")
 Please stub a default value first if message might be received with other args as well. 

    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:86:in `block in <module:Support>'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `call'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `notify_failure'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:320:in `notify'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:304:in `__raise'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/error_generator.rb:63:in `raise_missing_default_stub_error'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:206:in `raise_missing_default_stub_error'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:191:in `message_received'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:321:in `message_received'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:120:in `safe_load_file'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:154:in `read_config_file'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:179:in `block in read_config_files'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:178:in `each'
    /home/travis/build/jekyll/jekyll/lib/jekyll/configuration.rb:178:in `read_config_files'
    /home/travis/build/jekyll/jekyll/lib/jekyll.rb:105:in `configuration'
    /home/travis/build/jekyll/jekyll/test/test_configuration.rb:162:in `block (2 levels) in <class:TestConfiguration>'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'

583 tests, 987 assertions, 1 failures, 5 errors, 0 skips

================================================================================
Your 10 Slowest Tests
================================================================================

 4.3130ms - TestSite#test_: creating sites should write static files if not modified but missing in destination. 
 4.3080ms - TestSite#test_: creating sites should write only modified static files. 
 3.8895ms - TestSite#test_: creating sites incremental build should build incrementally. 
 1.5635ms - TestSite#test_: creating sites incremental build should regnerate files that have had their destination deleted. 
 1.0060ms - TestStaticFile#test_: A StaticFile should known if the source path is modified, when its not. 
 1.0057ms - TestStaticFile#test_: A StaticFile should known if the source path is modified, when it is. 
 0.7575ms - TestSite#test_: creating sites with orphaned files in destination should remove orphaned files in destination - keep_files .svn. 
 0.7465ms - TestRegenerator#test_: The site metadata should not regenerate again if multiple dependencies. 
 0.6976ms - TestSite#test_: creating sites manipulating the Jekyll environment in production should be overridden by JEKYLL_ENV. 
 0.6959ms - TestSite#test_: creating sites with orphaned files in destination should remove orphaned files in destination. 

rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test"  "/home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/**/test_*.rb" --profile]
/home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)

The command "script/cibuild" exited with 1.
store build cache
$ bundle clean
Resolving dependencies...
Removing mime-types (1.25.1)
Removing rdoc (3.12.2)
Removing activesupport (4.2.1)
Removing listen (2.10.0)
Removing cucumber (1.3.18)
change detected: /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/cache/activesupport-4.2.2.gem
changes detected, packing new archive
uploading archive

Done. Your build exited with 1.
```

Normally this is fixed by simply restarting the test but there is a problem in our tests or with SafeYAML.

**Comment by envygeeks** [comment]
Seems to no longer be an issue.
