### ISSUE TITLE
Jekyll 3.0.0.pre.beta7, when quitting immediately after starting I get an error report

### ISSUE THREAD

**Issue by Lewiscowles1986** [jekyll/jekyll#3812]
On windows if I quit Jekyll once it says it is done and before I have visited at least one URL, I get the following 

```cmd
C:\Users\Lewis\Documents\GitHub\birdyrose.github.io>jekyll serve
Configuration file: C:/Users/Lewis/Documents/GitHub/birdyrose.github.io/_config.
yml
            Source: C:/Users/Lewis/Documents/GitHub/birdyrose.github.io
       Destination: C:/Users/Lewis/Documents/GitHub/birdyrose.github.io/_site
 Incremental build: enabled
      Generating...
                    done in 0.158 seconds.
C:/Ruby22-x64/lib/ruby/2.2.0/securerandom.rb:123:in `gen_random': Interrupt
        from C:/Ruby22-x64/lib/ruby/2.2.0/securerandom.rb:110:in `random_bytes'
        from C:/Ruby22-x64/lib/ruby/2.2.0/securerandom.rb:173:in `hex'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/cellulo
id/uuid.rb:9:in `<module:UUID>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/cellulo
id/uuid.rb:8:in `<module:Celluloid>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/cellulo
id/uuid.rb:3:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/cellulo
id.rb:484:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/listen-2.10.0/lib/listen.rb:
1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-watch-1.2.1/lib/jekyl
l/watcher.rb:26:in `build_listener'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-watch-1.2.1/lib/jekyl
l/watcher.rb:7:in `watch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/commands/build.rb:72:in `watch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/commands/build.rb:39:in `process'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `block in execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/program.rb:42:in `go'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y.rb:19:in `program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/bin/j
ekyll:17:in `<top (required)>'
        from C:/Ruby22-x64/bin/jekyll:23:in `load'
        from C:/Ruby22-x64/bin/jekyll:23:in `<main>'
Terminate batch job (Y/N)? y
```

trace

```cmd
C:\Users\Lewis\Documents\GitHub\birdyrose.github.io>jekyll serve --trace
Configuration file: C:/Users/Lewis/Documents/GitHub/birdyrose.github.io/_config.
yml
            Source: C:/Users/Lewis/Documents/GitHub/birdyrose.github.io
       Destination: C:/Users/Lewis/Documents/GitHub/birdyrose.github.io/_site
 Incremental build: enabled
      Generating...
                    done in 0.16 seconds.
C:/Ruby22-x64/lib/ruby/2.2.0/securerandom.rb:123:in `gen_random': Interrupt
        from C:/Ruby22-x64/lib/ruby/2.2.0/securerandom.rb:110:in `random_bytes'
        from C:/Ruby22-x64/lib/ruby/2.2.0/securerandom.rb:173:in `hex'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/cellulo
id/uuid.rb:9:in `<module:UUID>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/cellulo
id/uuid.rb:8:in `<module:Celluloid>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/cellulo
id/uuid.rb:3:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/cellulo
id.rb:484:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/listen-2.10.0/lib/listen.rb:
1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-watch-1.2.1/lib/jekyl
l/watcher.rb:26:in `build_listener'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-watch-1.2.1/lib/jekyl
l/watcher.rb:7:in `watch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/commands/build.rb:72:in `watch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/commands/build.rb:39:in `process'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `block in execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/program.rb:42:in `go'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y.rb:19:in `program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/bin/j
ekyll:17:in `<top (required)>'
        from C:/Ruby22-x64/bin/jekyll:23:in `load'
        from C:/Ruby22-x64/bin/jekyll:23:in `<main>'
Terminate batch job (Y/N)? y
```

**Comment by envygeeks** [comment]
Unfortuantely Windows issues are handled on a can-do basis because none of us readily runs Windows so this'll get a response sometime this weekend when I can get on one of my Window boxes since I think I'm the only one on @jekyll/core with a Windows box readily available, I think everybody else uses a Mac.

**Comment by Lewiscowles1986** [comment]
:+1:  Yeah, I don't know what to say, I was committing to github, but I couldn't test plugins, and it strained my work-flow while I am mobile with only a laptop to play with...

I am pretty sure it has something to do with a new file which cropped up `.jekyll-metadata`, which I am assuming `jekyll clean` removes and rebuilds... 

It's an improvement over `2.5.3` in terms of being able to run `clean` command on windows, and the build process seeming much faster, and the clean command also fixed several other issues relating to accessing front-matter data, so that command may help others to resolve similar issues

**Comment by SuriyaaKudoIsc** [comment]
@Lewiscowles1986 Did you try to use the new versions of Jekyll?

**Comment by Lewiscowles1986** [comment]
Sorry, haven't followed up on this as I've not touched the site on windows, going to close this off for now as I'm using linux for all work-tasks
