### ISSUE TITLE
TypeError in jekyll when trying to use octopress-paginate instead of jekyll-paginate

### ISSUE THREAD

**Issue by gntech** [jekyll/jekyll#3929]
When I try to run jekyll with the octopress-paginate gem I get the error pasted below.
Since the octopress-paginate gem also pulls in octopress-hooks as a dependency it is possible that the bug really is in octopress-hooks.

Have anyone seen this error before and/or could give me a hint on some ways of troubleshooting it?

Thanks in advance :)

``` sh
$ jekyll clean && jekyll b -t
Configuration file: /home/gustav/git/www.gntech.se/_config.yml
Cleaning /home/gustav/git/www.gntech.se/_site... 
                    done.
Nothing to do for /home/gustav/git/www.gntech.se/.jekyll-metadata. 
Configuration file: /home/gustav/git/www.gntech.se/_config.yml
            Source: /home/gustav/git/www.gntech.se
       Destination: /home/gustav/git/www.gntech.se/_site
 Incremental build: enabled
      Generating... 
  Liquid Exception: no implicit conversion of nil into String in _projects/audio-shelf.md
/home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll.rb:159:in `expand_path': no implicit conversion of nil into String (TypeError)
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll.rb:159:in `sanitized_path'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:371:in `block in in_source_dir'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:370:in `each'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:370:in `reduce'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:370:in `in_source_dir'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/liquid_renderer.rb:16:in `file'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/renderer.rb:95:in `render_liquid'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:311:in `render_liquid'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/renderer.rb:52:in `run'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:306:in `run'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:172:in `block (2 levels) in render'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:170:in `each'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:170:in `block in render'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:169:in `each'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:169:in `render'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:197:in `render'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:59:in `process'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/command.rb:28:in `process_site'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/commands/build.rb:60:in `build'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/commands/build.rb:35:in `process'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/gustav/.rvm/gems/ruby-2.2.0/gems/jekyll-3.0.0.pre.beta8/bin/jekyll:17:in `<top (required)>'
	from /home/gustav/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `load'
	from /home/gustav/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `<main>'
	from /home/gustav/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/gustav/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by envygeeks** [comment]
Hi, while I hate to do this, if it's Octopress causing the error and not one of Jekyll's own libs it should be filed at Octopress so that it can be traced back here properly if it is indeed a bug in Jekyll.  We do not debug external dependencies.

**Comment by envygeeks** [comment]
To answer your question: Your best bet is to add pry to your Gemfile and then edit the first file in the callback chain you recieved and insert a binding.pry onto the line so that you can step into that context, if you get nothing move from file to file (backwards) until you reach the origin that sends or chivs the data and you'll have a starter for what's causing it.

However, I should also note that AWAIW @imathis has a beta version specifically for Jekyll 3.

**Comment by gntech** [comment]
Okay, thanks for the tips on using pry, i will look into that! I will also file a new issue at octopress instead. Thanks :)

**Comment by gntech** [comment]
@envygeeks For your information and to update on this issue: By some trial and error I have figured out that the problem is arrising when i use jekyll 3.0.0.pre.beta8 together with octopress-hooks on a site that uses collections. The problem doesnt appear when i do the same with jekyll 3.0.0.pre.beta7. I filed a bug at https://github.com/octopress/hooks/issues/13
