### ISSUE TITLE
Another issue with Liquid array method.

### ISSUE THREAD

**Issue by Sajgoniarz** [jekyll/jekyll#3944]
Hello guys!

I have portion of almost the same code used twice in different views to list posts in chosen category :
```
{% assign ordered_posts = site.categories[current_category] | sort: "title" %}
{% for post in ordered_posts %}
...
```
In default.html 
```
{% assign current_category = item.category %}
```
where `item` is an array cell from `submenu` in `_config.yml` :
```
pagelist:
 - title: "Home"
   url: "/"
   icon: "home"
   class: red
 - title: "Courses"
   icon: "image:collections-bookmark"
   submenu: // item
    - title: "HTML"
      category: html // item.category
      class: blue
    - title: "C#"
      category: cs
      class: yellow
 - title: "About"
   url: "/about"
   icon: "icons:assignment-ind"
   class: red
```
In course.html :
```
{% assign current_category = page.categories[1] %}
```

Both variables `ordered_posts` contains the same array, but when it comes to `| sort:` them Liquid returns :
`Liquid Exception: undefined method `sort' for nil:NilClass in _layouts/default.html`

The strange thing here is that build without sort in `default.html` and with it in `course.html` works fine. When I tried `{% for post in ordered_posts reversed %}` in first case it built normal too.

jekyll build --trace log :
```
  Liquid Exception: undefined method `sort' for nil:NilClass in _layouts/default.html
D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/filters.rb:248:in `sort': undefined method `sort' for nil:NilClass (NoMethodError)
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/strainer.rb:43:in `invoke'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/context.rb:82:in `invoke'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/variable.rb:50:in `block in render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/variable.rb:38:in `each'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/variable.rb:38:in `inject'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/variable.rb:38:in `render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/assign.rb:26:in `render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:109:in `block in render_all'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:96:in `each'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:96:in `render_all'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/for.rb:117:in `block (2 levels) in render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/for.rb:105:in `each'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/for.rb:105:in `each_with_index'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/for.rb:105:in `block in render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/context.rb:112:in `stack'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/for.rb:104:in `render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:109:in `block in render_all'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:96:in `each'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:96:in `render_all'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/if.rb:40:in `block (2 levels) in render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/if.rb:38:in `each'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/if.rb:38:in `block in render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/context.rb:112:in `stack'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/if.rb:37:in `render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:109:in `block in render_all'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:96:in `each'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:96:in `render_all'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/for.rb:117:in `block (2 levels) in render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/for.rb:105:in `each'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/for.rb:105:in `each_with_index'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/for.rb:105:in `block in render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/context.rb:112:in `stack'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/tags/for.rb:104:in `render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:109:in `block in render_all'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:96:in `each'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:96:in `render_all'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:82:in `render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/template.rb:128:in `render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/template.rb:138:in `render!'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:205:in `render_all_layouts'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:239:in `do_layout'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/post.rb:261:in `render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from D:/Programy/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
        from D:/Programy/Ruby22-x64/bin/jekyll:23:in `load'
        from D:/Programy/Ruby22-x64/bin/jekyll:23:in `<main>'
```

**Comment by envygeeks** [comment]
You are trying to use a variable to pull up a value in a hash, this is not a bug in Jekyll. However, this is a feature request for Liquid.  Sort gets the data that it's passed based on the data that you give it (which comes by way of Liquid itself into our liquid filter,) which means that because Liquid could not pull up the data, sort got nil and we aren't responsible for that, we let it fall as expected.  Please file your ticket at https://github.com/shopify/liquid/issues/new because there is nothing we can do about that.

This might also help you solve the problem: https://ecommerce.shopify.com/c/ecommerce-design/t/get-page-using-variable-name-as-array-key-if-pages-my-var-name-138285

**Comment by Sajgoniarz** [comment]
@envygeeks If its so, why it's working in one case? It should fail in both.

**Comment by envygeeks** [comment]
Unfortunately that's something you will have to ask the Liquid maintainers and programmers.  We do not maintain Liquid, it is one of our dependencies.  Now I could be wrong but my experience leads me to conjecture that the only thing we get is the final data, everything before that is Liquid doing the lifting because we are filtering, not parsing which means we should not get raw data (like variables.)

**Comment by envygeeks** [comment]
I'll reopen this just in-case I'm wrong though, because this could be a case of something else and I'm just not catching right now and maybe somebody else will catch it.

**Comment by parkr** [comment]
Pages are not a part of site.categories. We only do that for posts. It will work for some posts if you have a post with that category.

**Comment by Sajgoniarz** [comment]
@parkr I'm not listing pages, just posts in category marked in submenu items. I find workaround, but it require to iterate over all categories and it's not satisfying me. I like direct access :D

**Comment by parkr** [comment]
> I like direct access :D

You should be able to do this. `site.categories` is a hash of `category_name => [Post]`, so you should be able to do `site.categories["html"]`, for example.

**Comment by Sajgoniarz** [comment]
@parkr but then I can't sort this. all array method works beside :sort.

**Comment by envygeeks** [comment]
Sort is not an array method, it's a hash method.

**Comment by parkr** [comment]
Are you talking about [our sort filter](https://github.com/jekyll/jekyll/blob/1dc2a34252b353f9f64e91c98f03350bbb8a40cd/lib/jekyll/filters.rb#L217-L223). If so, it should work just fine with sort:

```liquid
{% assign sorted = myArray | sort %}
{% assign sorted_posts = site.posts | sort: "title" %}
```

If that doesn't work, please create a sample repo that we can use to reproduce. I can't get this to break.

**Comment by envygeeks** [comment]
Going to reiterate what @parkr asked, if it worked for you please close the ticket, if it didn't please provide a repo so we can replicate the issue and test it, thanks!
