### ISSUE TITLE
undefined local variable or method `path' for Jekyll::Layout

### ISSUE THREAD

**Issue by matthiasbeyer** [jekyll/jekyll#3987]
Hi.

I'm using these plugins:

* https://gist.github.com/dtjm/517556
* https://gist.github.com/mildred/1472645

(Both from the plugins site at jekyllrb.com)

I get the following error (with `--trace`):

```
Configuration file: /home/m/archive/development/ruby/wiki.template/_config.yml
            Source: /home/m/archive/development/ruby/wiki.template
       Destination: /home/m/archive/development/ruby/wiki.template/_site
      Generating... 
/home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:69:in `rescue in block in transform': undefined local variable or method `path' for #<Jekyll::Layout:0x000000012bcae0> (NameError)
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:66:in `block in transform'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:65:in `each'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:65:in `reduce'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:65:in `transform'
        from /home/m/archive/development/ruby/wiki.template/_plugins/transform_layout.rb:9:in `initialize'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/layout_reader.rb:11:in `new'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/layout_reader.rb:11:in `block in read'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/layout_reader.rb:10:in `each'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/layout_reader.rb:10:in `read'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:150:in `read'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:49:in `process'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/bin/jekyll:23:in `load'
        from /home/m/archive/development/ruby/wiki.template/vendor/bundle/ruby/2.2.0/bin/jekyll:23:in `<main>'

```

I can provide complete page source if you need.

**Comment by matthiasbeyer** [comment]
PS: I applied the patch which is stated in https://gist.github.com/mildred/1472645.

**Comment by parkr** [comment]
`path` is an attr_reader for Layout and has been for a while, so `#path` should be available. Right before calling `self.transform`, can you add `p self.methods.sort; p @path; p path`?
