### ISSUE TITLE
Liquid Exception: No such file or directory - .../yajl-ruby-1.2.1/yajl/yajl.so

### ISSUE THREAD

**Issue by gmacario** [jekyll/jekyll#4039]
Hello,

I tried to install Jekyll to serve my GitHub pages <https://github.com/gmacario/gmacario.github.io> locally

I am using Cygwin64 on my laptop running MS Windows 7 64-bit.

Inside a Cygwin bash I typed the following commands:

```
$ git clone https://github.com/gmacario/gmacario.github.io.git
$ cd gmacario.github.io
$ gem install bundler
$ bundle install
$ jekyll serve
```

but I got the following error:

```
gmacario@ITM-GMACARIO-W7 /cygdrive/e/data/MYGIT/gmacario.github.io
$ jekyll serve
Configuration file: /cygdrive/e/data/MYGIT/gmacario.github.io/_config.yml
            Source: /cygdrive/e/data/MYGIT/gmacario.github.io
       Destination: /cygdrive/e/data/MYGIT/gmacario.github.io/_site
      Generating...
  Liquid Exception: No such file or directory - /cygdrive/c/Users/gmacario/.gem/ruby/extensions/x86_64-cygwin/yajl-ruby-1.2.1/yajl/yajl.so in _posts/2015-01-20-welcome-to-jekyll.markdown/#excerpt
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:69:in `require': No such file or directory - /cygdrive/c/Users/gmacario/.gem/ruby/extensions/x86_64-cygwin/yajl-ruby-1.2.1/yajl/yajl.so (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/yajl-ruby-1.2.1/lib/yajl.rb:1:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:3:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/pygments.rb-0.6.3/lib/pygments.rb:1:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/tags/highlight.rb:77:in `render_pygments'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/tags/highlight.rb:51:in `render'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:106:in `render_liquid'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:233:in `do_layout'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/post.rb:258:in `render'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/site.rb:269:in `block in render'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/site.rb:268:in `each'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/site.rb:268:in `render'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/site.rb:46:in `process'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/command.rb:28:in `process_site'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:55:in `build'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:33:in `process'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /cygdrive/c/Users/gmacario/.gem/ruby/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
        from /cygdrive/c/Users/gmacario/bin/jekyll:23:in `load'
        from /cygdrive/c/Users/gmacario/bin/jekyll:23:in `<main>'

gmacario@ITM-GMACARIO-W7 /cygdrive/e/data/MYGIT/gmacario.github.io
$
```

But apparently the file is there:

```
gmacario@ITM-GMACARIO-W7 /cygdrive/e/data/MYGIT/gmacario.github.io
$ ls -la /cygdrive/c/Users/gmacario/.gem/ruby/extensions/x86_64-cygwin/yajl-ruby-1.2.1/yajl/
total 212
drwxrwxr-x+ 1 gmacario Domain Users      0 May 11 14:26 .
drwxrwxr-x+ 1 gmacario Domain Users      0 Oct 17 10:49 ..
-rwxr-xr-x  1 gmacario Domain Users 214837 May 11 14:26 yajl.so

gmacario@ITM-GMACARIO-W7 /cygdrive/e/data/MYGIT/gmacario.github.io
$
```

My apologies in advance if the question is trivial - I searched the web but could not find the answer myself.

**Comment by gmacario** [comment]
I actually fixed it myself by doing the following

```
$ rm /cygdrive/c/Users/gmacario/.gem/ruby/extensions/x86_64-cygwin/yajl-ruby-1.2.1/yajl/yajl.so
$ gem install yajl-ruby
$ bundle install
```

I probably had an old installation around which was causing some trouble.

Sorry for the noise.
