### ISSUE TITLE
The "jekyll serve" command reports error "cannot load such file -- jekyll/post (LoadError)" after upgrading to 3.0.0

### ISSUE THREAD

**Issue by tommyjiang** [jekyll/jekyll#4105]
Everything is OK when I use jekyll-3.0.0.pre.beta8 for building my site. 

But after upgrading to 3.0.0, when I run the `jekyll serve` command in my repo, I get the following error:

```
Configuration file: /Users/tommy/Documents/tommyjiang.github.io/_config.yml
/Users/tommy/Documents/tommyjiang.github.io/_plugins/debug.rb:13:in `<module:Jekyll>': cannot load such file -- jekyll/post (LoadError)
	from /Users/tommy/Documents/tommyjiang.github.io/_plugins/debug.rb:8:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:97:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:49:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

I am new to Ruby so I can not figure out what happens. Could anyone provide the solution? Thanks.

**Comment by envygeeks** [comment]
This is an implementation error with your `_plugins` and is not a bug in Jekyll so please ask your question on https://talk.jekyllrb.com where the wider community can help you rewrite your Ruby code to support Jekyll 3.0 changes.  Thanks!

**Comment by mashdot** [comment]
I notice that ```/lib/jekyll/post.rb``` no longer exists in 3.0.0 as it did in 2.5.3?

What has replaced it as a number of plugins are now breaking when calling ```class Post```.

- https://github.com/eggcaker/jekyll-org/issues/13
- https://talk.jekyllrb.com/t/error-messages-when-upgrading-to-3-0-on-mac-os-x/1398/4

**Comment by uraimo** [comment]
For who finds this issue while debugging a broken plugin when upgrading to 3.x like i did, most of the fixes are straightforward, check out this gist:  https://gist.github.com/uraimo/aa1437323a5da43c86cf for some sample fixes.
