### ISSUE TITLE
/lib/jekyll/post.rb no longer exists in 3.0.0 as it did in 2.5.3?

### ISSUE THREAD

**Issue by mashdot** [jekyll/jekyll#4116]
I notice that ```/lib/jekyll/post.rb``` no longer exists in 3.0.0 as it did in 2.5.3?

What has replaced it as a number of plugins are now breaking when calling ```class Post```.

- eggcaker/jekyll-org#13
- https://talk.jekyllrb.com/t/error-messages-when-upgrading-to-3-0-on-mac-os-x/1398/4

**Comment by sammcj** [comment]
I'm having issues with this too.

```
~/git/smcleod (master|…) % jekyll build
Configuration file: /Users/samm/git/smcleod/_config.yml
/Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-press-0.2.1/lib/jekyll-press.rb:55:in `<module:Jekyll>': cannot load such file -- jekyll/post (LoadError)
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-press-0.2.1/lib/jekyll-press.rb:7:in `<top (required)>'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /Users/samm/git/smcleod/_plugins/bundler.rb:3:in `<top (required)>'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:75:in `require'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `each'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `each'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/site.rb:97:in `setup'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/site.rb:49:in `initialize'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `new'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `process'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
	from /Users/samm/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
	from /Users/samm/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
	from /Users/samm/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/samm/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by envygeeks** [comment]
Jekyll 3.0.0 is a major release and is the perfect time to break things to change implementation details and internal API's.  As such, Post no longer exists and is now part of Document and the larger collection's.  You can see the code that handles this here: 

https://github.com/jekyll/jekyll/blob/master/lib/jekyll/collection.rb -> https://github.com/jekyll/jekyll/blob/master/lib/jekyll/document.rb

As such, this is not a bug in Jekyll but a need for a plugin to update to the new Collection -> Document structure.  If you are having trouble with this update please ask your questions at https://talk.jekyllrb.com and the wider community and sometimes maintainers will help you update your source to the latest Jekyll.

**Comment by envygeeks** [comment]
To add a second note: If you have to monkey patch any piece of Jekyll, please at that point do file a ticket as with the 3.1 release we would like to enable hooks at feasible points to help keep you from having to maintain Monkey patches and instead get passed the object you would like to work on, making it easier to maintain your code.

**Comment by ellisp** [comment]
@envygeeks is there any documentation of how Document and collections work and are different to the old way that post.rb did things, other than the source code you linked to?  The [Jekyll documentation page on the upgrade](http://jekyllrb.com/docs/upgrading/2-to-3/) doesn't mention the change and it probably should as I've found at least five plugins that are now broken.

**Comment by parkr** [comment]
@ellisp There isn't a migration guide as most things should be fairly identical, just naming tweaks. The documentation at http://www.rubydoc.info/gems/jekyll/3.1.1 should also help :)
