### ISSUE TITLE
Issues when trying to start node/gulp/Jekyll

### ISSUE THREAD

**Issue by richardcopestake** [jekyll/jekyll#4131]
[08:59:27] Using gulpfile ~/projects/website/gulpfile.js
[08:59:27] Starting 'default'...
[08:59:27] Starting 'clean'...
[08:59:27] Finished 'clean' after 10 ms
[08:59:27] Starting 'lint'...
[08:59:28] Finished 'lint' after 296 ms
[08:59:28] Starting 'jekyll'...
[08:59:28] Starting 'scripts'...
[08:59:28] Starting 'libs'...
[08:59:28] Starting 'html'...
[08:59:28] Starting 'images'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
richardcopestake in ~/projects/website on master

**Comment by envygeeks** [comment]
This is out of scope for Jekyll.  We are a project and Gulp is not an official part of Jekyll, please ask your question at https://talk.jekyllrb.com since this is for bugs directly related to Jekyll.
