### ISSUE TITLE
Jekyll 3.0.0 ran errors

### ISSUE THREAD

**Issue by LuckyLuke001** [jekyll/jekyll#4151]
```
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:75:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:97:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:49:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```
Anyone knows how to fix this? Tried a few advice I saw online. But jekyll still won't run

**Comment by envygeeks** [comment]
That's not the whole error.  Provide the whole error.

**Comment by parkr** [comment]
Closing as dead.

**Comment by parkr** [comment]
Search and post to talk.jekyllrb.com if the error persists.
