### ISSUE TITLE
Jekyll doesn't declare hitimes as a dependency in gemspec

### ISSUE THREAD

**Issue by jcoyne** [jekyll/jekyll#4247]
So when you `gem install jekyll` it isn't installed.  Then when you run the server you get an error:

```
$ jekyll serve
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find hitimes-1.2.2 in any of the sources (Bundler::GemNotFound)
```

**Comment by jcoyne** [comment]
When I did install hitimes, it gets version 1.2.3. But jekyll seems to only want 1.2.2

```
$ gem install hitimes
Fetching: hitimes-1.2.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed hitimes-1.2.3
Parsing documentation for hitimes-1.2.3
Installing ri documentation for hitimes-1.2.3
Done installing documentation for hitimes after 0 seconds
1 gem installed
2016.code4lib.org [master*]$ jekyll serve
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find hitimes-1.2.2 in any of the sources (Bundler::GemNotFound)
```

**Comment by jcoyne** [comment]
Mea culpa. This was in the Gemfile.lock of the project I checked out.
