### ISSUE TITLE
Jekyll master still not playing nice with Jekyll-Archives

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#4298]
```text
Configuration file: ~/Jekyll-Sites/Blog/_config.yml
            Source: ~/Jekyll-Sites/Blog
       Destination: ~/Jekyll-Sites/Blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-e048e428d19d/lib/jekyll/convertible.rb:248:in `do_layout': undefined method `page' for #<Hash:0x007fab462973b0> (NoMethodError)
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-archives-40823a4e16d8/lib/jekyll-archives/archive.rb:104:in `render'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-archives-40823a4e16d8/lib/jekyll-archives.rb:104:in `block in render'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-archives-40823a4e16d8/lib/jekyll-archives.rb:103:in `each'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-archives-40823a4e16d8/lib/jekyll-archives.rb:103:in `render'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-archives-40823a4e16d8/lib/jekyll-archives.rb:48:in `generate'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-e048e428d19d/lib/jekyll/site.rb:154:in `block in generate'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-e048e428d19d/lib/jekyll/site.rb:153:in `each'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-e048e428d19d/lib/jekyll/site.rb:153:in `generate'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-e048e428d19d/lib/jekyll/site.rb:58:in `process'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-e048e428d19d/lib/jekyll/command.rb:28:in `process_site'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-e048e428d19d/lib/jekyll/commands/build.rb:60:in `build'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-e048e428d19d/lib/jekyll/commands/build.rb:35:in `process'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-e048e428d19d/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from ~/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from ~/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from ~/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from ~/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from ~/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from ~/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-e048e428d19d/bin/jekyll:17:in `<top (required)>'
	from ~/.rvm/gems/ruby-2.1.2/bin/jekyll:23:in `load'
	from ~/.rvm/gems/ruby-2.1.2/bin/jekyll:23:in `<main>'
	from ~/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from ~/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by parkr** [comment]
Yeah, `Renderer` and `Convertible` need to use the hash setter `[]=` for backwards-compatibility.

**Comment by envygeeks** [comment]
This is a problem I ran into with some of my changes.  Drops should delegate the lot of hash methods.

**Comment by alfredxing** [comment]
Ref jekyll/jekyll-archives#55.
