### ISSUE TITLE
Jekyll master _still_ not playing nicely with jekyll-archives

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll#4326]
The latest bug in a continuing saga… (see https://github.com/jekyll/jekyll-archives/issues/55, and https://github.com/jekyll/jekyll/issues/4298)

I’m using the pre-release of Jekyll 3.1 (on master) with the latest liquid drop related fixes, but still getting an error, albeit different from the one before. Going by the trace, it still seems to relate to jekyll-archives. Here’s that trace:

```
Liquid Exception: no implicit conversion of nil into String in _includes/title.html, included in _layouts/index.html
/Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/tags/include.rb:132:in `rescue in render': no implicit conversion of nil into String (Jekyll::Tags::IncludeTagError)
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/tags/include.rb:124:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/convertible.rb:112:in `render_liquid'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/convertible.rb:216:in `render_all_layouts'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/convertible.rb:264:in `do_layout'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives/archive.rb:104:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:104:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:48:in `generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/site.rb:154:in `block in generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/site.rb:153:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/site.rb:153:in `generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/site.rb:58:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/command.rb:26:in `process_site'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/commands/build.rb:58:in `build'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/commands/build.rb:33:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/bin/jekyll:13:in `<top (required)>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

The source files referenced can be seen here: https://github.com/paulrobertlloyd/paulrobertlloyd.com/blob/master/source/_includes/title.html and https://github.com/paulrobertlloyd/paulrobertlloyd.com/blob/master/source/_layouts/index.html

If I remove `{% include title.html %}` from /_layouts/index.html, I get a different error, still with reference to jekyll-archives:

```
  Liquid Exception: undefined method `[]' for nil:NilClass in _layouts/default.html
/Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-assets-2.1.2/lib/jekyll/assets/liquid/tag.rb:80:in `render': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/convertible.rb:112:in `render_liquid'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/convertible.rb:216:in `render_all_layouts'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/convertible.rb:264:in `do_layout'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives/archive.rb:104:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:104:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:48:in `generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/site.rb:154:in `block in generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/site.rb:153:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/site.rb:153:in `generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/site.rb:58:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/command.rb:26:in `process_site'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/commands/build.rb:58:in `build'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/commands/build.rb:33:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-50086b686a89/bin/jekyll:13:in `<top (required)>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

Any ideas?

**Comment by pathawks** [comment]
I am getting the same error message running master branches of **jekyll** and **jekyll-archives**

> Going by the trace, it still seems to relate to jekyll-archives

Yes, when I disable **jekyll-archives**, my site builds fine.

**Comment by parkr** [comment]
That line has `@includes_dir` and `@file`, one of which must be `nil`.

**Comment by pathawks** [comment]
When **jekyll-archives** renders a page, `{{ page }}` is `nil`, so anything that tries to access it dies.

**Comment by pathawks** [comment]
When **jekyll-archives** calls [`do_layout` at `archive.rb:104`](https://github.com/jekyll/jekyll-archives/blob/master/lib/jekyll-archives/archive.rb#L104), I can confirm that payload is a `Hash`, but it seems like `do_layout` *really* wants a `Jekyll::Drops::UnifiedPayloadDrop`.

Does there need to be some sort of check inside `do_layout` to convert a `Hash` to a Drop?

**Comment by pathawks** [comment]
Oh! [`site_payload` at `archive.rb:102`](https://github.com/jekyll/jekyll-archives/blob/master/lib/jekyll-archives/archive.rb#L102) is a `Jekyll::Drops::UnifiedPayloadDrop`

*So*, when it tries to `deep_merge_hashes` the new hash with `site_payload`, it just silently fails.

**Comment by pathawks** [comment]
In [`Utils.deep_merge_hashes`](https://github.com/jekyll/jekyll/blob/v3.1.0.pre.beta1/lib/jekyll/utils.rb#L32-L48), if `target` has a key that does not appear in `overwrite`, that key will be dropped if `target` is a Hash and `overwrite` is a Drop.

When [**jekyll-archives** calls `Utils.deep_merge_hashes`](https://github.com/jekyll/jekyll-archives/blob/master/lib/jekyll-archives/archive.rb#L100-L102), it puts the Hash first and the Drop second. If these two are swapped, problem goes away.

Here is a dirty hack that fixes the problem. I have no idea why.

```diff
      def deep_merge_hashes!(target, overwrite)
+       if target.is_a?(Hash) && overwrite.is_a?(Drops::Drop)
+         target, overwrite = overwrite, target
+       end
        overwrite.each_key do |key|
```

**Comment by pathawks** [comment]
So, looking at how [**jekyll-archives** is using `Utils.deep_merge_hashes`](https://github.com/jekyll/jekyll-archives/blob/master/lib/jekyll-archives/archive.rb#L100-L102), my guess as to what is happening is this:

Before 3.1, `site_payload` did not contain a **page** key, so the **page** key of the new Hash was left unaffected. Now, `site_payload` has a `page` key set to `nil` by default, and that `nil` overwrites all of the data that is in the target Hash.

**Comment by parkr** [comment]
The Drop should be able to be turned into a Hash. So... it should behave as expected. Maybe the fix is `if target.is_a? Hash && overwrite.respond_to?(:to_hash) then overwrite = overwrite.to_hash`. Hmmm. The drop should behave just like a hash.

**Comment by envygeeks** [comment]
@parkr make Drops more like a hash, use Fowardable and a single internal hash (if you really want it immutable then freeze it -- no need to be fancy) and start Forwarding things like merge, to_h and otherwise straight to that instance variable, this drastically simplifies the Utils code and will finally allow me to update that unoptimized code to something twice as fast.

**Comment by envygeeks** [comment]
@parkr the reason I never updated that code (sent a pull) when I first spoted it was because of Drops :/

**Comment by parkr** [comment]
Why doesn't it work with drops?

**Comment by envygeeks** [comment]
Well to optiimize that code and it's complexities I need to shorten the amount of trips I make to message things. If drops behave more like a hash it instantly makes the code as optimized as it can be.  If I have to account for behaviors in the drops as they are, it makes it so I have to path more, it increases complexity, it increases messaging and ultimately it can lead to complicated code.

If we have them behave more like hashes, I can give you very fast deep merge code:

```ruby
module Utils extend self
  def deep_merge_hashes(old_hash, new_hash)
    old_hash.merge(new_hash) do |key, old_val, new_val|
      mergable?(old_val) && mergable?(new_val) ? deep_merge_hashes(old_val, new_val) : new_val
    end
  end

  #

  def mergable?(val)
    val.is_a?(Hash) || val.is_a?(Drop)
  end
end
```

The key here is it responding to merge to decrease the amount of work we have to do.

**Comment by paulrobertlloyd** [comment]
Can confirm this is now fixed. Thanks!

**Comment by parkr** [comment]
Hooray! Thanks, @paulrobertlloyd!
