### ISSUE TITLE
Liquid Exception caused by using 'class' in a conditional (3.1.0.pre.rc2)

### ISSUE THREAD

**Issue by budparr** [jekyll/jekyll#4383]
Trying out 3.1.0.pre.rc2, I got an error:
``` Liquid Exception: undefined method `to_liquid' for Jekyll::Drops::DocumentDrop:Class in _layouts/default.html ```

which I narrowed down to be caused by using this: 
```{% if page.class %} ...  {% endif %}```
_which I was merely using to assign a body class to certain pages_. When I remove it (or change the word "class" to anything else), Jekyll builds normally.

It's not a problem to _not do that_ but I'm not sure I understand the issue fully—maybe a reserved word(?)—and thought it worth bringing up here.

Here's my output with the trace flag:

```
Liquid Exception: undefined method `to_liquid' for Jekyll::Drops::DocumentDrop:Class in _layouts/default.html
/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/variable_lookup.rb:49:in `block in evaluate': undefined method `to_liquid' for Jekyll::Drops::DocumentDrop:Class (NoMethodError)
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/variable_lookup.rb:38:in `each_index'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/variable_lookup.rb:38:in `evaluate'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/context.rb:168:in `evaluate'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/context.rb:160:in `[]'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/condition.rb:99:in `interpret_condition'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/condition.rb:39:in `evaluate'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/tags/if.rb:38:in `block (2 levels) in render'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/tags/if.rb:37:in `each'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/tags/if.rb:37:in `block in render'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/tags/if.rb:36:in `render'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/renderer.rb:106:in `render_liquid'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/renderer.rb:143:in `place_in_layouts'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/renderer.rb:70:in `run'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/site.rb:171:in `block (2 levels) in render'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/site.rb:169:in `each'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/site.rb:169:in `block in render'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/site.rb:168:in `each'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/site.rb:168:in `render'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/site.rb:59:in `process'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/command.rb:26:in `process_site'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/commands/build.rb:58:in `build'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/commands/build.rb:33:in `process'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/lib/jekyll/commands/serve.rb:34:in `block (2 levels) in init_with_program'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-3.1.0.pre.rc2/bin/jekyll:13:in `<top (required)>'
	from /.rbenv/versions/2.1.3/bin/jekyll:23:in `load'
	from /.rbenv/versions/2.1.3/bin/jekyll:23:in `<main>'
```

**Comment by parkr** [comment]
Hey, @budparr! Thanks for the issue. :smile: 

> maybe a reserved word(?)

Yep, `class` is a reserved word. I'm surprised Liquid::Drop doesn't make that impossible to see from Liquid, though. Maybe we can find a way around this as it breaks behaviour...

**Comment by budparr** [comment]
Thanks. I think just a more explicit error would be enough, but glad the report was helpful.
