### ISSUE TITLE
Error while highlighting Swift code

### ISSUE THREAD

**Issue by kaunteya** [jekyll/jekyll#4701]
My travis build is suddenly failing, generating following logs.
It is not able to highlight `Swift` Code
[Here](https://github.com/kaunteya/lanyon) is my repo.
```
Configuration file: /home/travis/build/kaunteya/lanyon/_config.yml
Source: /home/travis/build/kaunteya/lanyon
Destination: out
Generating...   Liquid Exception: Traceback (most recent call last): 
File "/home/travis/.rvm/gems/ruby-2.1.5/gems/pygments.rb-0.5.4/lib/pygments/mentos.py", line 303, in start res = self.get_data(method, lexer, args, kwargs, text) 
File "/home/travis/.rvm/gems/ruby-2.1.5/gems/pygments.rb-0.5.4/lib/pygments/mentos.py", line 171, in get_data res = self.highlight_text(text, lexer, formatter_name, args, _convert_keys(opts))
 File "/home/travis/.rvm/gems/ruby-2.1.5/gems/pygments.rb-0.5.4/lib/pygments/mentos.py", line 122, in highlight_text lexer = self.return_lexer(lexer, args, kwargs, code) 
File "/home/travis/.rvm/gems/ruby-2.1.5/gems/pygments.rb-0.5.4/lib/pygments/mentos.py", line 79, in return_lexer return lexers.get_lexer_by_name(lexer, **inputs) 
File "/home/travis/.rvm/gems/ruby-2.1.5/gems/pygments.rb-0.5.4/vendor/pygments-main/pygments/lexers/__init__.py", line 81, in get_lexer_by_name raise 
ClassNotFound('no lexer for alias %r found' % _alias) ClassNotFound: no lexer for alias 'swift' found in _posts/2015-09-28-equatable-enums.md

**Comment by parkr** [comment]
Hey @kaunteya. `swift` isn't in `pygments.rb` v0.5.4. Upgrade to v0.6.0 or later. You may need to bump your Jekyll version to do that.

Alternatively, switch to Rouge. 😄

**Comment by kaunteya** [comment]
Thanks @parkr 
But how do I do I bump the Jekyll Version?

----
I tried updating my Gemfile by `gem 'jekyll',  '>=3.1'` and still not working.
Travis CI is giving this error
```
In Gemfile:
    github-pages (>= 0) ruby depends on\\
      jekyll (= 1.1.2) ruby

    jekyll (3.1.0)
```
