### ISSUE TITLE
Error:  error parsing fragment (1)

### ISSUE THREAD

**Issue by Mikaela** [jekyll/jekyll#4865]
###### What version of Jekyll are you using (`jekyll -v`)?

* jekyll 3.1.3

###### What operating system are you using?

* Arch Linux
* *GitHub pages*

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

* `jekyll build`
* `jekyll serve`

###### What did you expect to see?

* I expected the site to build properly like it did on older versions, but since GitHub pages updated I have been getting error message that says nothing to me so I would expect Jekyll to give me clear error message telling me what I should fix.
* I have contacted GitHub support and they only pointed me to deprecation error, which was fixed by removing + from URLs (https://github.com/Mikaela/mikaela.github.io/commit/6fb4c3cb60d194d226ff6446d8da46d273946281), but the issue is still there.

###### What did you see instead?

```
mikaela@sedric ~/src/github/mikaela/mikaela.github.io
% jekyll build -t
Configuration file: /home/mikaela/src/github/mikaela/mikaela.github.io/_config.yml
            Source: /home/mikaela/src/github/mikaela/mikaela.github.io
       Destination: /home/mikaela/src/github/mikaela/mikaela.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/home/mikaela/.gem/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:404:in `in_context': error parsing fragment (1) (RuntimeError)
        from /home/mikaela/.gem/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:404:in `parse'
        from /home/mikaela/.gem/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/html/document_fragment.rb:20:in `initialize'
        from /home/mikaela/.gem/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:371:in `new'
        from /home/mikaela/.gem/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:371:in `fragment'
        from /home/mikaela/.gem/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:812:in `coerce'
        from /home/mikaela/.gem/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:244:in `children='
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-mentions-1.1.2/lib/jekyll-mentions.rb:19:in `mentionify'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-mentions-1.1.2/lib/jekyll-mentions.rb:83:in `block in <top (required)>'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/hooks.rb:97:in `block in trigger'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/hooks.rb:96:in `each'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/hooks.rb:96:in `trigger'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/document.rb:409:in `trigger_hooks'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/site.rb:172:in `block (2 levels) in render'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/site.rb:169:in `each'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/site.rb:169:in `block in render'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/site.rb:168:in `each'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/site.rb:168:in `render'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/site.rb:59:in `process'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/command.rb:26:in `process_site'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/commands/build.rb:60:in `build'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/commands/build.rb:33:in `process'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
        from /home/mikaela/.gem/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /home/mikaela/.gem/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /home/mikaela/.gem/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /home/mikaela/.gem/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /home/mikaela/.gem/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /home/mikaela/.gem/ruby/2.3.0/gems/jekyll-3.1.3/bin/jekyll:13:in `<top (required)>'
        from /home/mikaela/.gem/ruby/2.3.0/bin/jekyll:23:in `load'
        from /home/mikaela/.gem/ruby/2.3.0/bin/jekyll:23:in `<main>'
```

Without `-t` I see 

```
mikaela@sedric ~/src/github/mikaela/mikaela.github.io
% jekyll build
Configuration file: /home/mikaela/src/github/mikaela/mikaela.github.io/_config.yml
            Source: /home/mikaela/src/github/mikaela/mikaela.github.io
       Destination: /home/mikaela/src/github/mikaela/mikaela.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.1.3 | Error:  error parsing fragment (1)
```

but I think the `-t` might be more useful in issue report.

**Comment by envygeeks** [comment]
Hey @Mikaela this is actually a Jekyll-Mentions error, can you just copy your ticket to https://github.com/jekyll/jekyll-mentions/issues/new, if they think it's a Core issue they'll either issue a fix or refile it here but for posterity it's good that the issue originate there so that @jekyll/plugin-core can take a look at it.

**Comment by Mikaela** [comment]
Thanks, I moved it to https://github.com/jekyll/jekyll-mentions/issues/31 .
