### ISSUE TITLE
Could not find gem 'jekyll-sitemap' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by wittyResry** [jekyll/jekyll#4972]
![image](https://cloud.githubusercontent.com/assets/7262998/15702920/421ef836-2815-11e6-8a0f-10773e4046ef.png)

**Comment by wittyResry** [comment]
```
sudo gem install jekyll-sitemap
```

**Comment by wittyResry** [comment]
```
➜  wittyResry.github.io git:(master) ✗ jekyll serve
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /Users/resry/alipay/apache-maven-2.2.1/bin in PATH, mode 040777
/Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:356:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'pygments.rb' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:331:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:331:in `verify_gemfile_dependencies_are_found!'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:200:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:184:in `resolve'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in `specs_for'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.1.6/lib/jekyll/plugin_manager.rb:33:in `require_from_bundler'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.1.6/bin/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>
```

**Comment by wittyResry** [comment]
use
```
sudo gem install pygments.rb
```

**Comment by kevinnerd** [comment]
Thanks for solving my problem~

**Comment by gusg21** [comment]
mine too

**Comment by talothman** [comment]
wittyResry solution isn't solving my issue. Still getting the same error.

**Comment by researcherGeekLab** [comment]
$ sudo gem install pygments.rb
$ gem install bundler
$ bundle install
