### ISSUE TITLE
Any suggestions: problem to run jekyll 

### ISSUE THREAD

**Issue by rubenmedios** [jekyll/jekyll#4991]
This morning i ran my project without problems, but 2 hours ago i try run the project but i can't.

My problem is this:
```
rubenmedios@rubenmedios:~/Github/MOREPRO/WEBSITE$ jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      rouge (~> 1.7)
      listen (< 3.1, ~> 3.0)
WARN: Clearing out unresolved specs.
rubenmedios@rubenmedios:~/Github/MOREPRO/WEBSITE$ jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      rouge (~> 1.7)
      listen (< 3.1, ~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/lib/ruby/vendor_ruby/bundler/spec_set.rb:92:in `block in materialize': Could not find listen-3.0.7 in any of the sources (Bundler::GemNotFound)
	from /usr/lib/ruby/vendor_ruby/bundler/spec_set.rb:85:in `map!'
	from /usr/lib/ruby/vendor_ruby/bundler/spec_set.rb:85:in `materialize'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:114:in `specs'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:159:in `specs_for'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:148:in `requested_specs'
	from /usr/lib/ruby/vendor_ruby/bundler/environment.rb:18:in `requested_specs'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:13:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:120:in `setup'
	from /var/lib/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/plugin_manager.rb:33:in `require_from_bundler'
	from /var/lib/gems/2.2.0/gems/jekyll-3.1.6/bin/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
rubenmedios@rubenmedios:~/Github/MOREPRO/WEBSITE$ 
```
`

Please help me! 
`

**Comment by parkr** [comment]
Try running `gem install jekyll` again. This isn't a problem with jekyll, but with the Ruby environment on your machine.
