### ISSUE TITLE
URL: check to see if the key exists or rescue NoMethodError

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#5332]
If you have URL template like `/:year/:headline`, you'll see a NoMethodError, like:

``` text
  Liquid Exception: undefined method `headline' for #<Jekyll::Drops::UrlDrop:0x007ff42b74aa28> in sitemap.xml
NoMethodError: undefined method `headline' for #<Jekyll::Drops::UrlDrop:0x007ff42b74aa28>
  /Users/parkr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/url.rb:89:in `public_send'
  /Users/parkr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/url.rb:89:in `block in generate_url_from_drop'
  /Users/parkr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/url.rb:88:in `gsub'
  /Users/parkr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/url.rb:88:in `generate_url_from_drop'
  /Users/parkr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/url.rb:69:in `generate_url'
  /Users/parkr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/url.rb:60:in `generated_url'
  /Users/parkr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/url.rb:40:in `to_s'
  /Users/parkr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/document.rb:211:in `url'
  /Users/parkr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/drops/drop.rb:52:in `public_send'
  /Users/parkr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/drops/drop.rb:52:in `[]'
```

This is because [`URL#generate_url_from_drop`](https://github.com/jekyll/jekyll/blob/v3.2.1/lib/jekyll/url.rb#L89) uses `public_send` to look for all these values. It should either use `#[]` or warn and ignore a missing method like this.

**Comment by fene** [comment]
@parkr why would we need to ignore these errors? does the generated site work regardless of there being a missing method in the url template?

**Comment by parkr** [comment]
@fene We wouldn't ignore the error, but we should transform it into something smarter. The resulting site could still work, but saying "Oy! That's not a valid URL template variable" would be more useful than "What's that method you're trying to access?"
