### ISSUE TITLE
Too many open files on build

### ISSUE THREAD

**Issue by r0fls** [jekyll/jekyll#5766]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
I just installed jekyll with `brew`, the Mac OS package manager. Here is the version:
```
$ jekyll --version
WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.4, ~> 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
jekyll 3.2.1
```

- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
---
- [x] I am on (or have tested on) ***macOS*** 10+
---
- [x] I was trying to build.

## My Reproduction Steps

I can't provide actual reproduction steps because this is a closed source repository. Using `jekyll build` and `jekyll build --incremenatal` both report too many open files:

```
$ jekyll build --incremental
WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.4, ~> 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/r0fls/Documents/code/platform/gitlab/platformsh/_config.yml
            Source: /Users/r0fls/Documents/code/platform/gitlab/platformsh
       Destination: /Users/r0fls/Documents/code/platform/gitlab/platformsh/_site
 Incremental build: enabled
      Generating... 
jekyll 3.2.1 | Error:  Too many open files @ rb_sysopen - /Users/r0fls/Documents/code/platform/gitlab/platformsh/images/blog/eurocloud-tweet.png
```
 

I found another issue where this occurs, but there it was due to a recursive relationship. However a colleague of mine is able to build this same project successfully. Here is the same command with `--trace` enabled:

```
$ jekyll build --trace
WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.4, ~> 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/r0fls/Documents/code/platform/gitlab/platformsh/_config.yml
            Source: /Users/r0fls/Documents/code/platform/gitlab/platformsh
       Destination: /Users/r0fls/Documents/code/platform/gitlab/platformsh/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/usr/local/lib/ruby/gems/2.3.0/gems/sprockets-3.6.3/lib/sprockets/path_utils.rb:278:in `initialize': Too many open files @ rb_sysopen - /Users/r0fls/Documents/code/platform/gitlab/platformsh/_site/assets/home/picto-symfony.png.70101531252760.7049.740484 (Errno::EMFILE)
        from /usr/local/lib/ruby/gems/2.3.0/gems/sprockets-3.6.3/lib/sprockets/path_utils.rb:278:in `open'
        from /usr/local/lib/ruby/gems/2.3.0/gems/sprockets-3.6.3/lib/sprockets/path_utils.rb:278:in `atomic_write'
        from /usr/local/lib/ruby/gems/2.3.0/gems/sprockets-3.6.3/lib/sprockets/asset.rb:165:in `write_to'
        from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/manifest.rb:92:in `block (2 levels) in compile'
        from /usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
        from /usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
        from /usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
        from /usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/ivar.rb:170:in `safe_execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/future.rb:52:in `block in execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
        from /usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
        from /usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
        from /usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
        from /usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
        from /usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by r0fls** [comment]
Whoops, I finally increased the file limit and it's working now:

```
$ echo kern.maxfiles=65536 | sudo tee -a /etc/sysctl.conf
$ echo kern.maxfilesperproc=65536 | sudo tee -a /etc/sysctl.conf
$ sudo sysctl -w kern.maxfiles=65536
$ sudo sysctl -w kern.maxfilesperproc=65536
$ ulimit -n 65536 65536    
```
