### ISSUE TITLE
Liquid Exception: Liquid error (line 8): Cannot sort a null object.

### ISSUE THREAD

**Issue by oneohthree** [jekyll/jekyll#5856]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [x] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

Run `jekyll b --verbose --trace`

## The Output I Wanted

Using Jekyll 3.4.0 trying to build my site this error appear:

```
Liquid Exception: Liquid error (line 8): Cannot sort a null object. in foo.html
/home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/filters.rb:265:in `sort': Liquid error (line 8): Cannot sort a null object. (Liquid::ArgumentError)
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/strainer.rb:56:in `invoke'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/context.rb:86:in `invoke'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/variable.rb:78:in `block in render'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/variable.rb:76:in `each'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/variable.rb:76:in `inject'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/variable.rb:76:in `render'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/tags/assign.rb:24:in `render'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
        from /home/foo/.gem/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/liquid_renderer/file.rb:40:in `measure_bytes'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/liquid_renderer/file.rb:47:in `measure_time'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/renderer.rb:134:in `render_liquid'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/renderer.rb:82:in `run'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:463:in `block in render_pages'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:461:in `each'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:461:in `render_pages'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:191:in `render'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:69:in `process'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/command.rb:26:in `process_site'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/commands/build.rb:63:in `build'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/commands/build.rb:34:in `process'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
        from /home/foo/.gem/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /home/foo/.gem/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /home/foo/.gem/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /home/foo/.gem/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /home/foo/.gem/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /home/foo/.gem/ruby/2.3.0/gems/jekyll-3.4.0/exe/jekyll:13:in `<top (required)>'
        from /home/foo/.gem/ruby/2.3.0/bin/jekyll:22:in `load'
        from /home/foo/.gem/ruby/2.3.0/bin/jekyll:22:in `<main>'
```

**However using Jekyll 3.1.2 the site builds flawlessly.**

I solved the issue upgrading `rubygems` package to 2.4.

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by HareshMiriyala** [comment]
I still have the same issue. I have ruby v2.7.7 and jekyll latest as of Jul 6th 2018.
