### ISSUE TITLE
I am getting this error "here was an error while trying to load the gem 'jekyll_pages_api'. (Bundler::GemRequireError)"

### ISSUE THREAD

**Issue by remya-cn** [jekyll/jekyll#6077]
I got this issue while trying to add the [jekyll_pages_api gem](https://github.com/18F/jekyll_pages_api).

- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I am on (or have tested on)  CentOS GNU/Linux
- [x] I was trying to install.

## My Reproduction Steps

```
[root@cu560 testsite1]# jekyll serve --host=0.0.0.0 /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'jekyll_pages_api'. (Bundler::GemRequireError) Gem Load Error is: undefined method `render' for class `Jekyll::Site' Backtrace for gem load error is: 
/usr/local/share/gems/gems/jekyll_pages_api-0.1.6/lib/jekyll/site.rb:7:in `alias_method' /usr/local/share/gems/gems/jekyll_pages_api-0.1.6/lib/jekyll/site.rb:7:in `<class:Site>' /usr/local/share/gems/gems/jekyll_pages_api-0.1.6/lib/jekyll/site.rb:5:in `<module:Jekyll>' /usr/local/share/gems/gems/jekyll_pages_api-0.1.6/lib/jekyll/site.rb:4:in `<top (required)>' /usr/local/share/gems/gems/jekyll_pages_api-0.1.6/lib/jekyll_pages_api.rb:7:in `require_relative' /usr/local/share/gems/gems/jekyll_pages_api-0.1.6/lib/jekyll_pages_api.rb:7:in `<top (required)>' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler.rb:107:in `require' /usr/local/share/gems/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler' /usr/local/share/gems/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>' /usr/local/bin/jekyll:23:in `load' /usr/local/bin/jekyll:23:in `<main>' Bundler Error Backtrace:         from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'         from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'         from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'         from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'         from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'         from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'         from /usr/local/share/gems/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler'         from /usr/local/share/gems/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'         from /usr/local/bin/jekyll:23:in `load'         from /usr/local/bin/jekyll:23:in `<main>'
```

## The Output I Wanted

http://localhost:4000/api/v1/pages.json displaying entries in json

**Comment by DirtyF** [comment]
It's working fine on MacOS. 
Have you asked the plugin maintainers?

**Comment by ashmaroli** [comment]
`not-reproduced` on Windows 7 with Jekyll-3.4.3
@remya-cn  can you try again with just `bundle exec jekyll serve`?

**Comment by remya-cn** [comment]
yeah. it actually worked now. I was trying it with sudo permission. that caused the issue i guess.
