### ISSUE TITLE
Serious issues installing with Homebrew copy of Ruby

### ISSUE THREAD

**Issue by Nickersoft** [jekyll/jekyll#6152]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [x] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

Hi all, I had successfully installed Jekyll using the Xcode-provided copy of Ruby on my Macbook running OS X Sierra 10.12.15, however, I decided I wanted to install all my future gems using my Homebrew copy of Ruby, so I uninstalled Jekyll and went to reinstall using Homebrew. I altered my bash profile to place Homebrew's /usr/local path before the rest of my paths, then did a simple install of Ruby:

```
$ brew install ruby
```

And checked my version of `ruby` and `gem`:

```
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
$ gem -v
2.6.11
```

Then I installed Jekyll:

```
$ gem install jekyll
Fetching: public_suffix-2.0.5.gem (100%)
Successfully installed public_suffix-2.0.5
Fetching: addressable-2.5.1.gem (100%)
Successfully installed addressable-2.5.1
Fetching: colorator-1.1.0.gem (100%)
Successfully installed colorator-1.1.0
Fetching: sass-3.4.24.gem (100%)
Successfully installed sass-3.4.24
Fetching: jekyll-sass-converter-1.5.0.gem (100%)
Successfully installed jekyll-sass-converter-1.5.0
Fetching: rb-fsevent-0.9.8.gem (100%)
Successfully installed rb-fsevent-0.9.8
Fetching: ffi-1.9.18.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.18
Fetching: rb-inotify-0.9.10.gem (100%)
Successfully installed rb-inotify-0.9.10
Fetching: listen-3.0.8.gem (100%)
Successfully installed listen-3.0.8
Fetching: jekyll-watch-1.5.0.gem (100%)
Successfully installed jekyll-watch-1.5.0
Fetching: kramdown-1.13.2.gem (100%)
Successfully installed kramdown-1.13.2
Fetching: liquid-3.0.6.gem (100%)
Successfully installed liquid-3.0.6
Fetching: mercenary-0.3.6.gem (100%)
Successfully installed mercenary-0.3.6
Fetching: forwardable-extended-2.6.0.gem (100%)
Successfully installed forwardable-extended-2.6.0
Fetching: pathutil-0.14.0.gem (100%)
Successfully installed pathutil-0.14.0
Fetching: rouge-1.11.1.gem (100%)
Successfully installed rouge-1.11.1
Fetching: safe_yaml-1.0.4.gem (100%)
Successfully installed safe_yaml-1.0.4
Fetching: jekyll-3.4.4.gem (100%)
Successfully installed jekyll-3.4.4
Parsing documentation for public_suffix-2.0.5
Installing ri documentation for public_suffix-2.0.5
Parsing documentation for addressable-2.5.1
Installing ri documentation for addressable-2.5.1
Parsing documentation for colorator-1.1.0
Installing ri documentation for colorator-1.1.0
Parsing documentation for sass-3.4.24
Installing ri documentation for sass-3.4.24
Parsing documentation for jekyll-sass-converter-1.5.0
Installing ri documentation for jekyll-sass-converter-1.5.0
Parsing documentation for rb-fsevent-0.9.8
Installing ri documentation for rb-fsevent-0.9.8
Parsing documentation for ffi-1.9.18
Installing ri documentation for ffi-1.9.18
Parsing documentation for rb-inotify-0.9.10
Installing ri documentation for rb-inotify-0.9.10
Parsing documentation for listen-3.0.8
Installing ri documentation for listen-3.0.8
Parsing documentation for jekyll-watch-1.5.0
Installing ri documentation for jekyll-watch-1.5.0
Parsing documentation for kramdown-1.13.2
Installing ri documentation for kramdown-1.13.2
Parsing documentation for liquid-3.0.6
Installing ri documentation for liquid-3.0.6
Parsing documentation for mercenary-0.3.6
Installing ri documentation for mercenary-0.3.6
Parsing documentation for forwardable-extended-2.6.0
Installing ri documentation for forwardable-extended-2.6.0
Parsing documentation for pathutil-0.14.0
Installing ri documentation for pathutil-0.14.0
Parsing documentation for rouge-1.11.1
Installing ri documentation for rouge-1.11.1
Parsing documentation for safe_yaml-1.0.4
Installing ri documentation for safe_yaml-1.0.4
Parsing documentation for jekyll-3.4.4
Installing ri documentation for jekyll-3.4.4
Done installing documentation for public_suffix, addressable, colorator, sass, jekyll-sass-converter, rb-fsevent, ffi, rb-inotify, listen, jekyll-watch, kramdown, liquid, mercenary, forwardable-extended, pathutil, rouge, safe_yaml, jekyll after 36 seconds
18 gems installed
```

This installed version 3.4.4. All I did next was just run the `jekyll` command and:

```
$ jekyll
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.4/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.4/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:22:in `load'
	from /usr/local/bin/jekyll:22:in `<main>'
```

So I went ahead and installed bundler 1.15.1 and reran `jekyll`:

```
$ jekyll
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/resolver.rb:396:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jekyll (= 3.4.3)' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/resolver.rb:366:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/resolver.rb:366:in `verify_gemfile_dependencies_are_found!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/resolver.rb:212:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/resolver.rb:191:in `resolve'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:235:in `resolve'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:159:in `specs'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:218:in `specs_for'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:207:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:109:in `block in definition_method'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:21:in `setup'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler.rb:101:in `setup'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.4/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.4/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:22:in `load'
	from /usr/local/bin/jekyll:22:in `<main>'
```

So I thought "Oh, the bundler must not have a caught up with the new version yet." So I uninstalled Jekyll 3.4.4 and installed 3.4.3 instead, but running 3.4.3 yielded:

```
$ jekyll 
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/resolver.rb:396:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'minima (~> 2.0)' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/resolver.rb:366:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/resolver.rb:366:in `verify_gemfile_dependencies_are_found!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/resolver.rb:212:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/resolver.rb:191:in `resolve'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:235:in `resolve'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:159:in `specs'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:218:in `specs_for'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:207:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:109:in `block in definition_method'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:21:in `setup'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler.rb:101:in `setup'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:22:in `load'
	from /usr/local/bin/jekyll:22:in `<main>'
```

I tried installing `minima` but every time I ran Jekyll it still would throw a dependency error. What exactly is happening here? Why would it work so flawlessly on Apple's Ruby (ruby 2.0.0p648) but not Homebrew's (ruby 2.4.1p111)? 

## The Output I Wanted

I expected it to just install properly, just as any other normal gem would.
/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by pathawks** [comment]
Sorry you are having trouble. The installation is still my least favorite part of Jekyll.

When you are using Bundler, it helps to prefix every command with `bundle exec`. This is mentioned in [our Quick-start guide](http://jekyllrb.com/docs/quickstart/#about-bundler), but we could probably do a better job explaining things.

One additional recommendation: You might look into using RVM on macOS. That has made my life easier, so that I could stop fighting against Apple's Ruby.

If you have further questions about the installation procedure, you could search https://talk.jekyllrb.com. If you find an area where our documentation could be improved, please do submit a pull request.
