### ISSUE TITLE
`bundle exec site:generate` doesn't work on latest master

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#6154]
After merging the Jekyll 3.5 release post, I went to go generate the site (to generate the history & latest_version.txt files) and got this:

```text
NoMethodError: undefined method `registers' for nil:NilClass
  /Users/parkr/jekyll/jekyll/lib/jekyll/filters/url_filters.rb:44:in `site'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/redirect_page.rb:58:in `context'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/redirect_page.rb:45:in `set_paths'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/redirect_page.rb:20:in `from_paths'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/redirect_page.rb:26:in `redirect_from'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/generator.rb:27:in `block in generate_redirect_from'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/generator.rb:26:in `each'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/generator.rb:26:in `generate_redirect_from'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/generator.rb:17:in `block in generate'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/generator.rb:15:in `each'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-redirect-from-0.12.1/lib/jekyll-redirect-from/generator.rb:15:in `generate'
  /Users/parkr/jekyll/jekyll/lib/jekyll/site.rb:178:in `block in generate'
  /Users/parkr/jekyll/jekyll/lib/jekyll/site.rb:176:in `each'
  /Users/parkr/jekyll/jekyll/lib/jekyll/site.rb:176:in `generate'
  /Users/parkr/jekyll/jekyll/lib/jekyll/site.rb:72:in `process'
  /Users/parkr/jekyll/jekyll/lib/jekyll/command.rb:26:in `process_site'
  /Users/parkr/jekyll/jekyll/lib/jekyll/commands/build.rb:63:in `build'
  /Users/parkr/jekyll/jekyll/lib/jekyll/commands/build.rb:34:in `process'
  /Users/parkr/jekyll/jekyll/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/parkr/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/parkr/jekyll/jekyll/exe/jekyll:13:in `<top (required)>'
```

**Comment by parkr** [comment]
jekyll-redirect-from's RedirectPage simply [sets the `context` method](https://github.com/jekyll/jekyll-redirect-from/blob/5f0544a270dd6834de1348aa6cda9aa8fd0e024b/lib/jekyll-redirect-from/redirect_page.rb#L67-L69) whereas the Jekyll URL filters [use `@context` directly](https://github.com/jekyll/jekyll/blob/22072235598838311eb14d26f3aeebf39d435234/lib/jekyll/filters/url_filters.rb#L44).

**Comment by parkr** [comment]
Oddly enough, [`#set_paths` seems to set `@context`](https://github.com/jekyll/jekyll-redirect-from/blob/5f0544a270dd6834de1348aa6cda9aa8fd0e024b/lib/jekyll-redirect-from/redirect_page.rb#L46) so... why is it nil?

**Comment by DirtyF** [comment]
could it be related to #6058 ?

**Comment by benbalter** [comment]
The problem is that RedirectPage inherits from Page, which has `attr_accessor :site`. Extending URLFilters now has a `site` method, which relies on @context, which isn't set when it's called (and if it were, would create a circular reference in that the `context` method calls `site` to create the context). The simplest fix is to have RedirectFrom call `@site`, instead of `site` so the extended method doesn't prevent the `context` method from accessing the instance variable `@site`.

**Comment by ashmaroli** [comment]
Wow..
Note to self: Even `private` methods (albeit new) can lead to unforeseen bugs somewhere..

**Comment by benbalter** [comment]
Also an issue with page excludes in Jekyll Sitemap: https://github.com/jekyll/jekyll-sitemap/issues/176.

**Comment by Crunch09** [comment]
Can we close this? Now that #6163 has been merged?
