### ISSUE TITLE
jekyll on gentoo fails

### ISSUE THREAD

**Issue by pauledd** [jekyll/jekyll#6423]
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] I am on (or have tested on) ***Other*** GNU/Linux

---

- [x] I was trying to build.

## My Reproduction Steps
`#emerge --sync`
`#emerge jekyll`
(...www-apps/jekyll-3.6.0 merged.)

```
#jekyll -v
#jekyll 3.6.0
#jekyll new 1
Running bundle install in /mnt/store/www/1... 
  Bundler: The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
  Bundler: Fetching gem metadata from https://rubygems.org/...........
  Bundler: Fetching version metadata from https://rubygems.org/..
  Bundler: Fetching dependency metadata from https://rubygems.org/.
  Bundler: Resolving dependencies...
  Bundler: Using public_suffix 3.0.0
  Bundler: Using colorator 1.1.0
  Bundler: Using forwardable-extended 2.6.0
  Bundler: Using jekyll-sass-converter 1.5.0
  Bundler: Using jekyll-watch 1.5.0
  Bundler: Using kramdown 1.15.0
  Bundler: Using liquid 4.0.0
  Bundler: Using mercenary 0.3.6
  Bundler: Using rouge 3.0.0
  Bundler: Using safe_yaml 1.0.4
  Bundler: Using bundler 1.14.6
  Bundler: Using addressable 2.5.2
  Bundler: Using pathutil 0.16.0
  Bundler: Using jekyll 3.6.0
  Bundler: Using jekyll-feed 0.9.2
  Bundler: Installing minima 2.1.1
  Bundler: Bundle complete! 4 Gemfile dependencies, 16 gems now installed.
  Bundler: Use `bundle show [gemname]` to see where a bundled gem is installed.
New jekyll site installed in /mnt/store/www/1.
#cd new 1
#jekyll serve
Configuration file: /mnt/store/www/1/_config.yml
/usr/lib64/ruby/gems/2.2.0/gems/jekyll-3.6.0/lib/jekyll/theme.rb:40:in `require': cannot load such file -- sass (LoadError)
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-3.6.0/lib/jekyll/theme.rb:40:in `configure_sass'
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-3.6.0/lib/jekyll/theme.rb:11:in `initialize'
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-3.6.0/lib/jekyll/site.rb:430:in `new'
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-3.6.0/lib/jekyll/site.rb:430:in `configure_theme'
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-3.6.0/lib/jekyll/site.rb:58:in `config='
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-3.6.0/lib/jekyll/site.rb:26:in `initialize'
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-3.6.0/lib/jekyll/commands/build.rb:30:in `new'
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-3.6.0/lib/jekyll/commands/build.rb:30:in `process'
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-3.6.0/lib/jekyll/commands/serve.rb:42:in `block (3 levels) in init_with_program'
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-3.6.0/lib/jekyll/commands/serve.rb:42:in `each'
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-3.6.0/lib/jekyll/commands/serve.rb:42:in `block (2 levels) in init_with_program'
        from /usr/lib64/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
        from /usr/lib64/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/lib64/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /usr/lib64/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /usr/lib64/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /usr/lib64/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-3.6.0/exe/jekyll:15:in `<top (required)>'
        from /usr/bin/jekyll:9:in `load'
        from /usr/bin/jekyll:9:in `<main>'
```
```
#bundle exec jekyll serve
/usr/lib64/ruby/gems/2.2.0/gems/jekyll-sass-converter-1.5.0/lib/jekyll/converters/scss.rb:3:in `require': cannot load such file -- sass (LoadError)
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-sass-converter-1.5.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-sass-converter-1.5.0/lib/jekyll-sass-converter.rb:2:in `require'
        from /usr/lib64/ruby/gems/2.2.0/gems/jekyll-sass-converter-1.5.0/lib/jekyll-sass-converter.rb:2:in `<top (required)>'
        from /home/paul/.gem/ruby/2.2.0/gems/jekyll-3.6.0/lib/jekyll.rb:195:in `require'
        from /home/paul/.gem/ruby/2.2.0/gems/jekyll-3.6.0/lib/jekyll.rb:195:in `<top (required)>'
        from /home/paul/.gem/ruby/2.2.0/gems/jekyll-3.6.0/exe/jekyll:8:in `require'
        from /home/paul/.gem/ruby/2.2.0/gems/jekyll-3.6.0/exe/jekyll:8:in `<top (required)>'
        from /home/paul/.gem/ruby/2.2.0/bin/jekyll:23:in `load'
        from /home/paul/.gem/ruby/2.2.0/bin/jekyll:23:in `<main>'
```
any ideas?

**Comment by DirtyF** [comment]
Anyone else using Gentoo Linux can confirm this?

/cc @mgorny maintainer of the Gentoo package

**Comment by pauledd** [comment]
I tested  again the whole installation on a clean new gentoo system. After 
`emerge jekyll`
it complains about Bundler not installed:
```
 jekyll new 1
Could not load Bundler. Bundle install skipped. 
New jekyll site installed in /home/user/1.
```
Maybe we should start from here...

**Comment by mgorny** [comment]
It's my fault. The previous Gentoo version completely removed all bundler bits. I've seen they changed upstream, so left them out to see if they work. I'll restore stripping them again when I find time for it.

Please make sure to report a Gentoo bug for things like that. We really want to trace the problems our users have.

**Comment by pauledd** [comment]
ok so this is more a gentoo issue... So I will only add another comment for Bug 625994.

**Comment by mgorny** [comment]
@pauledd, my original assessment was wrong. I have no clue if it's a specific Gentoo issue, or upstream issue that exhibits itself on Gentoo.

**Comment by pathawks** [comment]
Is `emerge` supported by @jekyll as an installation method?

Is there something in our code that we need to change, or does this issue belong somewhere else?

/cc: @jekyll/linux
