### ISSUE TITLE
Problems to install 3.7.2

### ISSUE THREAD

**Issue by neburs** [jekyll/jekyll#6786]
Hi,

I'm try to install the last version off jekyll and minima and when try to build the html, next error appears.

```
$ jekyll build --watch
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find public_suffix-3.0.1 in any of the sources (Bundler::GemNotFound)
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `map!'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
from /usr/local/bundle/gems/jekyll-3.7.0/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
from /usr/local/bundle/gems/jekyll-3.7.0/exe/jekyll:11:in `<top (required)>'
from /usr/local/bundle/bin/jekyll:23:in `load'
from /usr/local/bundle/bin/jekyll:23:in `<main>'
```

This is the sentence that I use to install jekyll

```
$ gem install jekyll
$ gem install                                                                  \
    jekyll-feed                                                                  \
    minima                                                                       \
    jekyll-seo-tag
```

I think that exist a problem with dependencies because if I force to use the versions of the install was indicate, they continue to indicate that the version specified not made installed.

Does someone else happen to you?

**Comment by ashmaroli** [comment]
instead of running `gem install` multiple times, simply run `bundle install` from within your project directory.

**Comment by neburs** [comment]
I can see that my project have a Gemfile.lock. If I delete it, the command woks again. 

Thanks for your help.
