### ISSUE TITLE
jekyll serve: undefined local variable or method `source_path' for Jekyll::Watcher:Module

### ISSUE THREAD

**Issue by benswift** [jekyll/jekyll#7308]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | macOS 10.13.6           |
| `jekyll`         | 3.8.4     |
| `github-pages`   | No     |

---

## Expected Behaviour

`jekyll serve` re-builds any modified files and keeps serving the website

## Current Behavior

I've just upgraded Jekyll to 3.8.4 (from 3.8.3). Now when I run `jekyll serve` it works fine the first time, but on any file changes I get the following error & backtrace:

```
E, [2018-10-10T17:31:24.115653 #36230] ERROR -- : exception while processing events: undefined local variable or method `source_path' for Jekyll::Watcher:Module

Backtrace:
 -- /usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-watch-2.1.0/lib/jekyll/watcher.rb:63:in `block (2 levels) in listen_handler'
 -- /usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-watch-2.1.0/lib/jekyll/watcher.rb:63:in `each'
 -- /usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-watch-2.1.0/lib/jekyll/watcher.rb:63:in `block in listen_handler'
 -- /usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
 -- /usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:115:in `_process_changes'
 -- /usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:19:in `block in loop_for'
 -- /usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
 -- /usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
 -- /usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
 -- /usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
 -- /usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'

```

## Code Sample

I can reproduce the issue using the following repo:

<https://github.com/benswift/jekyll-bug-report>

**Comment by ashmaroli** [comment]
@benswift This is a bug with the latest release of `jekyll-watch-2.1.0`. The plugin will be patched as soon as possible.
Sorry for the inconvenience caused.

**Comment by benswift** [comment]
s'all good, let me know when it's up and I'll do an update.

**Comment by DirtyF** [comment]
@benswift 👍 you can update to [`jekyll-watch v2.1.1`](https://github.com/jekyll/jekyll-watch/releases/tag/v2.1.1)

**Comment by benswift** [comment]
yep, works great. 👏
