### ISSUE TITLE
Hi everyone, I'm new to this... so please be easy on me.  I'm trying to install jekyll on mu mac, and getting the following  "/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rubygems/core_ext/kernel_warn (LoadError) 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require' 	from /Library/Ruby/Site/2.3.0/rubygems.rb:1395:in `<top (required)>' 	from <internal:gem_prelude>:4:in `require' 	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'"   can anyone help to let me know what i should do, I tried so many things to no avail.

### ISSUE THREAD

**Issue by 1leopold** [jekyll/jekyll#7435]
Hi everyone, I'm new to this... so please be easy on me.  I'm trying to install jekyll on my mac, and getting the following 

```
 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rubygems/core_ext/kernel_warn (LoadError) 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require' 	from /Library/Ruby/Site/2.3.0/rubygems.rb:1395:in `<top (required)>' 	from <internal:gem_prelude>:4:in `require' 	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
```

can anyone help to let me know what i should do, I tried so many things to no avail.

**Comment by DirtyF** [comment]
Have your read https://jekyllrb.com/docs/installation/macos/ ?

This repo is only for Jekyll bugs, please post your question on our dedicated forum at https://talk.jekyllrb.com.
