### ISSUE TITLE
You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)

### ISSUE THREAD

**Issue by shangchihh** [jekyll/jekyll#7463]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  macOS 10.14.2          |
| `jekyll`         | 3.8.5     |
| `github-pages`   | No     |

---

## Expected Behaviour

`jekyll -v` and `jekyll serve` works correctly

## Current Behavior

I type `jekyll -v` in the `~/` directory and it works fine, but when I type `jekyll -v` in my jekyll project folder, it reports an error:

```
Traceback (most recent call last):
	13: from /usr/local/lib/ruby/gems/2.6.0/bin/jekyll:23:in `<main>'
	12: from /usr/local/lib/ruby/gems/2.6.0/bin/jekyll:23:in `load'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
	 9: from /usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/bundler.rb:101:in `setup'
	 8: from /usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/bundler.rb:135:in `definition'
	 7: from /usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/bundler/definition.rb:34:in `build'
	 6: from /usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:13:in `evaluate'
	 5: from /usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:234:in `to_definition'
	 4: from /usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:234:in `new'
	 3: from /usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/bundler/definition.rb:83:in `initialize'
	 2: from /usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/bundler/definition.rb:83:in `new'
	 1: from /usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/bundler/lockfile_parser.rb:95:in `initialize'
/usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version': You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)
```

I try to run `jekyll serve`, it still report the same error message.

**Comment by DirtyF** [comment]
You can try:

# update Rubygems
`gem update --system`

# update bundler
`gem install bundler`

# update Gemfile.lock
`bundler update --bundler`

**Comment by nathanbw** [comment]
I'm seeing this same issue. I'm using ruby 2.6.0 installed via `ruby-install` and selected with `chruby`. Below is some more detailed information from my system. (MacOS High Sierra)

```
Last command had exit code: 0 at 17:02
nathan@Nathans-Mac-Pro:~
$ cd src/nathan/nbw-static/
Last command had exit code: 0 at 17:02
nathan@Nathans-Mac-Pro:~/src/nathan/nbw-static
$ jekyll build
Traceback (most recent call last):
	13: from /Users/nathan/.gem/ruby/2.6.0/bin/jekyll:23:in `<main>'
	12: from /Users/nathan/.gem/ruby/2.6.0/bin/jekyll:23:in `load'
	11: from /Users/nathan/.gem/ruby/2.6.0/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
	10: from /Users/nathan/.gem/ruby/2.6.0/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
	 9: from /Users/nathan/.rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler.rb:101:in `setup'
	 8: from /Users/nathan/.rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler.rb:135:in `definition'
	 7: from /Users/nathan/.rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/definition.rb:34:in `build'
	 6: from /Users/nathan/.rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:13:in `evaluate'
	 5: from /Users/nathan/.rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:234:in `to_definition'
	 4: from /Users/nathan/.rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:234:in `new'
	 3: from /Users/nathan/.rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/definition.rb:83:in `initialize'
	 2: from /Users/nathan/.rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/definition.rb:83:in `new'
	 1: from /Users/nathan/.rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/lockfile_parser.rb:95:in `initialize'
/Users/nathan/.rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version': You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)
Last command had exit code: 1 at 17:02
nathan@Nathans-Mac-Pro:~/src/nathan/nbw-static
$ bundler --version
Bundler version 2.0.1
Last command had exit code: 0 at 17:02
nathan@Nathans-Mac-Pro:~/src/nathan/nbw-static
$ ruby --version ; gem --version
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin17]
3.0.1
Last command had exit code: 0 at 17:02
nathan@Nathans-Mac-Pro:~/src/nathan/nbw-static
$ echo $PATH
/Users/nathan/.gem/ruby/2.6.0/bin:/Users/nathan/.rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/bin:/Users/nathan/.rubies/ruby-2.6.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/nathan/.cargo/bin:/Users/nathan/bin
Last command had exit code: 0 at 17:03
nathan@Nathans-Mac-Pro:~/src/nathan/nbw-static
$ gem list

*** LOCAL GEMS ***

addressable (2.5.2)
bigdecimal (default: 1.4.1)
bundler (2.0.1, default: 1.17.2)
cmath (default: 1.0.0)
colorator (1.1.0)
concurrent-ruby (1.1.4)
csv (default: 3.0.2)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.0)
e2mmap (default: 0.1.0)
em-websocket (0.5.1)
etc (default: 1.0.1)
eventmachine (1.2.7)
fcntl (default: 1.0.0)
ffi (1.10.0)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
forwardable-extended (2.6.0)
gdbm (default: 2.0.0)
http_parser.rb (0.6.0)
i18n (0.9.5)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
jekyll (3.8.5)
jekyll-feed (0.11.0)
jekyll-sass-converter (1.5.2)
jekyll-seo-tag (2.5.0)
jekyll-watch (2.1.2)
json (default: 2.1.0)
kramdown (1.17.0)
liquid (4.0.1)
listen (3.1.5)
logger (default: 1.3.0)
matrix (default: 0.1.0)
mercenary (0.3.6)
minima (2.5.0)
minitest (5.11.3)
mutex_m (default: 0.1.0)
net-telnet (0.2.0)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
pathutil (0.16.2)
power_assert (1.1.3)
prime (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (3.0.3)
rake (12.3.2)
rb-fsevent (0.10.3)
rb-inotify (0.10.0)
rdoc (default: 6.1.0)
rexml (default: 3.1.9)
rouge (3.3.0)
rss (default: 0.2.7)
ruby_dep (1.5.0)
safe_yaml (1.0.4)
sass (3.7.3)
sass-listen (4.0.0)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (default: 0.7)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
test-unit (3.2.9)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
Last command had exit code: 0 at 17:03
nathan@Nathans-Mac-Pro:~/src/nathan/nbw-static
$ 
```

**Comment by ashmaroli** [comment]
@nathanbw This is not a bug in Jekyll. Jekyll has no constraints on the Bundler version. If anything this could be an issue with Bundler itself.

First try running Jekyll with Bundler:
```
bundle exec jekyll build
```
If error persists, try the following steps:
- Delete existing `Gemfile.lock`
- Update Rubygems:
  ```
  gem update --system
  ```
- Run Jekyll with Bundler:
  ```
  bundle exec jekyll build
  ```

**Comment by MtnBiker** [comment]
`heroku buildpacks:set https://github.com/bundler/heroku-buildpack-bundler2`

from https://github.com/bundler/bundler/issues/6784

For a different situation, but worth a look

**Comment by bcartwri96** [comment]
I had a similar issue where my gemfile was bundled with 2.0.1 (as shown in my gemfile.lock) and my bundle --version outputted 2.0.1 but my application said `You must use Bundler 2 or greater with this lockfile.`

`gem update --system` worked for me! Thanks @ikeshavgiri

**Comment by localhostdotdev** [comment]
`spring stop` can also solve this (bundler 1.17 was loaded in memory I guess, even though I installed and used bundler 2)

**Comment by zorek9502** [comment]
I had a similar issue using rails, I did what DirtyF commented on 5 Jan and it' worked. 

update Rubygems
gem update --system

update bundler
gem install bundler

update Gemfile.lock in your project
bundler update --bundler
