### ISSUE TITLE
Concurrent ruby conflict error when trying to create a new Jekyll website

### ISSUE THREAD

**Issue by matejlatin** [jekyll/jekyll#7544]
I'm trying to create a new Jekyll website, I had created them in the past and if I run `jekyll serve` that website works.

Today I tried to create a new website and I received a 'concurrent ruby conflict' error. I have no Idea what that means.

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      macOS Mojave 10.14.2      |
| `jekyll`         | Don't know     |
| `github-pages`   | Don't know     |

---

## Expected Behaviour

Create a new jekyll website

## Current Behavior

The following is what I get:

```
Matejs-MacBook-Pro:~ matejlatin$ jekyll new my-awesome-website
/Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2290:in `raise_if_conflicts': Unable to activate concurrent-ruby-ext-1.1.3, because concurrent-ruby-1.1.4 conflicts with concurrent-ruby (= 1.1.3) (Gem::ConflictError)
	from /Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
	from /Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems.rb:220:in `rescue in try_activate'
	from /Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems.rb:213:in `try_activate'
	from /Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/matejlatin/.rvm/gems/ruby-2.3.3/gems/concurrent-ruby-1.1.4/lib/concurrent/utility/native_extension_loader.rb:62:in `try_load_c_extension'
	from /Users/matejlatin/.rvm/gems/ruby-2.3.3/gems/concurrent-ruby-1.1.4/lib/concurrent/utility/native_extension_loader.rb:30:in `block in load_native_extensions'
	from /Users/matejlatin/.rvm/gems/ruby-2.3.3/gems/concurrent-ruby-1.1.4/lib/concurrent/utility/native_extension_loader.rb:30:in `each'
	from /Users/matejlatin/.rvm/gems/ruby-2.3.3/gems/concurrent-ruby-1.1.4/lib/concurrent/utility/native_extension_loader.rb:30:in `load_native_extensions'
	from /Users/matejlatin/.rvm/gems/ruby-2.3.3/gems/concurrent-ruby-1.1.4/lib/concurrent/synchronization.rb:5:in `<top (required)>'
	from /Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/matejlatin/.rvm/gems/ruby-2.3.3/gems/concurrent-ruby-1.1.4/lib/concurrent/map.rb:3:in `<top (required)>'
	from /Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/matejlatin/.rvm/gems/ruby-2.3.3/gems/i18n-0.9.5/lib/i18n.rb:1:in `<top (required)>'
	from /Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/matejlatin/.rvm/gems/ruby-2.3.3/gems/jekyll-3.8.5/lib/jekyll.rb:38:in `<top (required)>'
	from /Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/matejlatin/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/matejlatin/.rvm/gems/ruby-2.3.3/gems/jekyll-3.8.5/exe/jekyll:8:in `<top (required)>'
	from /Users/matejlatin/.rvm/gems/ruby-2.3.3/bin/jekyll:23:in `load'
	from /Users/matejlatin/.rvm/gems/ruby-2.3.3/bin/jekyll:23:in `<main>'
	from /Users/matejlatin/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/matejlatin/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ashmaroli** [comment]
This really a strange issue. I can't figure out why `concurrent-ruby-1.1.4` is trying to load `concurrent-ruby-ext-1.1.4`.. :man_shrugging: 
That said, this is not a Jekyll issue.
To proceed, you can simply uninstall `concurrent-ruby-1.1.3` and `concurrent-ruby-ext-1.1.3` gems entirely and ensure that there is no `Gemfile` in the directory you invoke `jekyll new` from.

Closing, since there's nothing much to be done at our end.

**Comment by DirtyF** [comment]
@matejlatin On another topic, Ruby 2.3 will go EOL at the end of march, next Jekyll version will drop support fu Ruby 2.3.
