### ISSUE TITLE
jekyll 3.8.3 | Error:  uninitialized constant FFI::Platform::CPU

### ISSUE THREAD

**Issue by chopin2712** [jekyll/jekyll#7712]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  Ubuntu 19.10       |
| `jekyll`         | Latest     |
| `github-pages`   | No     |

---

## Current Behavior

I was trying to run
```
sudo apt install jekyll
jekyll new my-awesome-site
cd my-awesome-site
bundle exec jekyll serve 
```
But it didn't works and gave me the following error code:
xec jekyll serve
/var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/drops/document_drop.rb:8: warning: already initialized constant Jekyll::Drops::DocumentDrop::NESTED_OBJECT_FIELD_BLACKLIST
/usr/lib/ruby/vendor_ruby/jekyll/drops/document_drop.rb:8: warning: previous definition of NESTED_OBJECT_FIELD_BLACKLIST was here
/var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/drops/drop.rb:8: warning: already initialized constant Jekyll::Drops::Drop::NON_CONTENT_METHODS
/usr/lib/ruby/vendor_ruby/jekyll/drops/drop.rb:8: warning: previous definition of NON_CONTENT_METHODS was here
Configuration file: /home/chopin/Git/test/jekll/my-awesome-site/website/my_blog/_config.yml
            Source: /home/chopin/Git/test/jekll/my-awesome-site/website/my_blog
       Destination: /home/chopin/Git/test/jekll/my-awesome-site/website/my_blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.363 seconds.
jekyll 3.8.3 | Error:  uninitialized constant FFI::Platform::CPU

## Installation setup
I am on Ubuntu 19.10 and I have installed Jekyll
I have installed Jekyll through the following line:
`sudo apt install jekyll` because the common line: `gem install bundler jekyll` didn't work.

**Comment by ashmaroli** [comment]
> because the common line: `gem install bundler jekyll` didn't work.

What was the error there?
You seem to be pulling in `/usr/lib/ruby/vendor_ruby/jekyll` and creating conflicts with `/var/lib/gems/2.5.0/gems/jekyll-3.8.5/`

**Comment by chopin2712** [comment]
> > because the common line: `gem install bundler jekyll` didn't work.
> 
> What was the error there?
> You seem to be pulling in `/usr/lib/ruby/vendor_ruby/jekyll` and creating conflicts with `/var/lib/gems/2.5.0/gems/jekyll-3.8.5/`

Before the command just didn't work, when I typed `jekyll` It says that the command doesn't exist.

But now, I don't know why, it works, well, no. I uninstall the apt and installed by this command and now when I type `jekyll` it give me the help output. 

But my problem is not solved, I always have the same error when I am trying to start the new site.

**Comment by ashmaroli** [comment]
What is the current error?
You can get the stacktrace by using the `--trace` switch:
```
bundle exec jekyll build --trace
```

**Comment by chopin2712** [comment]
This command give me the following output:
```
Configuration file: /home/chopin/Git/test/jekll/my-awesome-site/website/_config.yml
            Source: /home/chopin/Git/test/jekll/my-awesome-site/website
       Destination: /home/chopin/Git/test/jekll/my-awesome-site/website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.302 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

**Comment by ashmaroli** [comment]
@chopin2712 I don't see any error nor a stacktace..
How about the following?
```
bundle exec jekyll serve --trace
```

**Comment by chopin2712** [comment]
> @chopin2712 I don't see any error nor a stacktace..
> How about the following?
> 
> ```
> bundle exec jekyll serve --trace
> ```

It gives me the following output : 
```
Configuration file: /home/chopin/Git/test/jekll/my-awesome-site/website/_config.yml
            Source: /home/chopin/Git/test/jekll/my-awesome-site/website
       Destination: /home/chopin/Git/test/jekll/my-awesome-site/website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.31 seconds.
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
NameError: uninitialized constant FFI::Platform::CPU
  /usr/lib/ruby/vendor_ruby/ffi/platform.rb:57:in `<module:Platform>'
  /usr/lib/ruby/vendor_ruby/ffi/platform.rb:37:in `<module:FFI>'
  /usr/lib/ruby/vendor_ruby/ffi/platform.rb:32:in `<top (required)>'
  /usr/lib/ruby/vendor_ruby/ffi/ffi.rb:31:in `require'
  /usr/lib/ruby/vendor_ruby/ffi/ffi.rb:31:in `<top (required)>'
  /usr/lib/ruby/vendor_ruby/ffi.rb:9:in `require'
  /usr/lib/ruby/vendor_ruby/ffi.rb:9:in `<top (required)>'
  /usr/lib/ruby/vendor_ruby/rb-inotify/native.rb:1:in `require'
  /usr/lib/ruby/vendor_ruby/rb-inotify/native.rb:1:in `<top (required)>'
  /usr/lib/ruby/vendor_ruby/rb-inotify.rb:2:in `require'
  /usr/lib/ruby/vendor_ruby/rb-inotify.rb:2:in `<top (required)>'
  /usr/lib/ruby/vendor_ruby/listen/adapter/linux.rb:30:in `require'
  /usr/lib/ruby/vendor_ruby/listen/adapter/linux.rb:30:in `_configure'
  /usr/lib/ruby/vendor_ruby/listen/adapter/base.rb:45:in `block in configure'
  /usr/lib/ruby/vendor_ruby/listen/adapter/base.rb:40:in `each'
  /usr/lib/ruby/vendor_ruby/listen/adapter/base.rb:40:in `configure'
  /usr/lib/ruby/vendor_ruby/listen/adapter/base.rb:63:in `start'
  /usr/lib/ruby/vendor_ruby/listen/listener.rb:68:in `block in <class:Listener>'
  /usr/lib/ruby/vendor_ruby/listen/fsm.rb:121:in `instance_eval'
  /usr/lib/ruby/vendor_ruby/listen/fsm.rb:121:in `call'
  /usr/lib/ruby/vendor_ruby/listen/fsm.rb:91:in `transition_with_callbacks!'
  /usr/lib/ruby/vendor_ruby/listen/fsm.rb:57:in `transition'
  /usr/lib/ruby/vendor_ruby/listen/listener.rb:91:in `start'
  /usr/lib/ruby/vendor_ruby/jekyll/watcher.rb:26:in `watch'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:94:in `call'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:94:in `watch'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:43:in `process'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `block in start'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `each'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `start'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
  /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `block in execute'
  /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `each'
  /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `execute'
  /usr/lib/ruby/vendor_ruby/mercenary/program.rb:42:in `go'
  /usr/lib/ruby/vendor_ruby/mercenary.rb:19:in `program'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
  /usr/local/bin/jekyll:23:in `load'
  /usr/local/bin/jekyll:23:in `<top (required)>'
```

**Comment by ashmaroli** [comment]
The issue seems to be because of the gems installed in your `vendor_ruby` directory.
Can you list all the gems installed in that directory?
```
cd /usr/lib/ruby/vendor_ruby/
ls -a
```

**Comment by chopin2712** [comment]
> The issue seems to be because of the gems installed in your `vendor_ruby` directory.
> Can you list all the gems installed in that directory?
> 
> ```
> cd /usr/lib/ruby/vendor_ruby/
> ls -a
> ```

It gives me the following :
```
.                     jekyll-coffeescript       pg.rb
..                    jekyll-coffeescript.rb    posix
2.5.0                 jekyll-feed.rb            posix-spawn.rb
addressable           jekyll-gist               power_assert
addressable.rb        jekyll-gist.rb            power_assert.rb
afm.rb                jekyll-paginate           prawn
Ascii85               jekyll-paginate.rb        prawn.rb
ascii85.rb            jekyll-sass-converter     pygments
blankslate.rb         jekyll-sass-converter.rb  pygments.rb
classifier-reborn     jekyll-watch              rake
classifier-reborn.rb  jekyll-watch.rb           rake.rb
coderay               jeventmachine.rb          rb-inotify
coderay.rb            json                      rb-inotify.rb
coffee_script         json.rb                   rc4.rb
coffee-script.rb      kramdown                  rdiscount.rb
coffee_script.rb      kramdown.rb               redcarpet
colorator             launchy.rb                redcarpet.rb
colorator.rb          liquid                    rouge
concurrent            liquid.rb                 rouge.rb
concurrent-edge.rb    listen                    rubygems
concurrent.rb         listen.rb                 safe_yaml
did_you_mean          markdown.rb               safe_yaml.rb
did_you_mean.rb       mercenary                 sass
em                    mercenary.rb              sass.rb
em-websocket          mime                      sequel
em-websocket.rb       mime-types-data.rb        sequel_pg
eventmachine.rb       minitest                  sequel.rb
execjs                minitest.rb               stringex
execjs.rb             molinillo                 stringex_lite.rb
fast-stemmer.rb       molinillo.rb              stringex.rb
fast_stemmer.rb       multi_json                test
feed.xml              multi_json.rb             test-unit.rb
ffi                   net                       thor
ffi.rb                net-telnet.rb             thor.rb
forwardable           oj                        toml
hashery               oj.rb                     toml.rb
hashery.rb            parslet                   ttfunk
hoe                   parslet.rb                ttfunk.rb
http                  pathutil                  xmlrpc
http_parser.rb        pathutil.rb               xmlrpc.rb
i18n                  pdf                       yajl
i18n.rb               pdf-reader.rb             yajl.rb
jekyll                pg
```

**Comment by ashmaroli** [comment]
Hmm.. I expected to see only dependencies of Jekyll there. It looks like you're using Ruby for more than just Jekylling. Is that correct?

**Comment by chopin2712** [comment]
Yes, it can be, but I don't know when I install an app which app uses Gem.

**Comment by ashmaroli** [comment]
Okay, you can delete the directories for `ffi` and `listen` for now. Then go back to your jekyll project directory, and run;
```sh
bundle update
bundle exec jekyll s -t # shorthand for the command you ran earlier
```

**Comment by chopin2712** [comment]
I made the following commands:
```
cd /usr/lib/ruby/vendor_ruby/
sudo rm -r ffi
sudo rm -r listen
cd PATH/TO/MY/PROJECT
bundle update
bundle exec jekyll s -t
```
And for the last line it gives me : 
```
Configuration file: /home/chopin/Git/test/jekll/my-awesome-site/website/_config.yml
            Source: /home/chopin/Git/test/jekll/my-awesome-site/website
       Destination: /home/chopin/Git/test/jekll/my-awesome-site/website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.402 seconds.
  Dependency Error: Yikes! It looks like you don't have jekyll-watch or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- listen/logger' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
Jekyll::Errors::MissingDependencyException: jekyll-watch
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/external.rb:68:in `rescue in block in require_with_graceful_fail'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/external.rb:56:in `block in require_with_graceful_fail'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/external.rb:55:in `each'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/external.rb:55:in `require_with_graceful_fail'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:87:in `watch'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:43:in `process'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `block in start'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `each'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `start'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
  /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `block in execute'
  /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `each'
  /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `execute'
  /usr/lib/ruby/vendor_ruby/mercenary/program.rb:42:in `go'
  /usr/lib/ruby/vendor_ruby/mercenary.rb:19:in `program'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
  /usr/local/bin/jekyll:23:in `load'
  /usr/local/bin/jekyll:23:in `<top (required)>'
```

**Comment by ashmaroli** [comment]
Hmm.. this is indeed frustrating.
Looks like you'll have to resort to setting up *local bundles* for every Jekyll project..

1. Move into your Jekyll project directory and run `bundle config --local path vendor`
2. Then reinstall the entire dependency tree for your project by running `bundle install`
3. Start Jekyll server.

To summarize:
```
cd PATH/TO/YOUR/PROJECT
bundle config --local path vendor
bundle install
bundle exec jekyll s -t
```

**Comment by chopin2712** [comment]
Thank you so much, it works! This is what commands I needed to type:
```
bundle config --local path vendor
bundle install
bundle update listen
bundle exec jekyll s -t
```
Then I can go to http://localhost:4000 and It works!!!! Thank you so much!

**Comment by ashmaroli** [comment]
Yay! Glad you got it all working.
I think you can restore the backup for the `vendor_ruby` directory now. That shouldn't bother you anymore.

Happy Jekyllin.

**Comment by jonorthwash** [comment]
I've been having the same problem on Debian, i.e. when I try to serve the site it says `jekyll 3.8.3 | Error:  uninitialized constant FFI::Platform::CPU`.

I've tried setting up local bundles and am getting this:

```ruby
$ bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/...........
Using public_suffix 3.1.0
Using addressable 2.6.0
Using bundler 2.0.1
Using colorator 1.1.0
Using concurrent-ruby 1.1.5
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using ffi 1.11.1
Using forwardable-extended 2.6.0
Using i18n 0.9.5
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.0
Using sass-listen 4.0.0
Using sass 3.7.4
Using jekyll-sass-converter 1.5.2
Fetching listen 3.1.5
Downloading listen-3.1.5 revealed dependencies not in the API or the lockfile
(rb-fsevent (>= 0.9.4, ~> 0.9), ruby_dep (~> 1.2)).
Either installing with `--full-index` or running `bundle update listen` should
fix the problem.
```

Any thoughts?

**Comment by jonorthwash** [comment]
Okay, `bundle update listen` worked (although it reported `Bundler attempted to update listen but its version stayed the same`).  But now I can serve the site!

I should mention that from the very beginning I was just trying to follow the Quickstart instructions at https://jekyllrb.com/docs/ , and `bundle exec jekyll serve` has consistently given me that.  If I hadn't been persistent (for a couple weeks, poking friends who use jekyll, stopping in #jekyll on IRC, and someone on IRC eventually encouraging me to check the issues here), I would never have figured this out.

My guess is that this issues affects most debian systems, and that you'll stop getting new debian users if a fix isn't found.  This work-around is fine, but it's not part of the Quickstart instructions, and many people won't be as persistent as I was.

**Comment by ashmaroli** [comment]
@jonorthwash Thank you for the tip.
We'll update our documentation.

/cc @DirtyF

**Comment by attibalazs** [comment]
thank you boss, i had the same issue and your instructions solved it for me!

**Comment by ytzemih** [comment]
@jonorthwash I tried your suggestion resulting in the same error. On Ubuntu 19.10, [that](https://stackoverflow.com/questions/57105493/error-uninitialized-constant-ffiplatformcpu-on-starting-jekyll-server) worked for me: Installation through `bundle` rather than `apt`.
