### ISSUE TITLE
How can I tell Jekyll to use ruby 2.6, rather than 2.0? (MacOS High Sierra)

### ISSUE THREAD

**Issue by gaoyang86** [jekyll/jekyll#7760]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |       Mac OS High Sierra     |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |
| bash      | zsh |

---

## Expected Behaviour

Jekyll could run when I type `jekyll` in terminal.

## Current Behavior
First I installed `rbenv` and then installed `ruby-2.6.3` with `rbenv`.

Then I installed jekyll 

`sudo gem install bundle jekyll`

This output shows up:

`Successfully installed jekyll-3.8.6`

so I am sure the jekyll is installed.

So I checked the jekyll's version:
`jekyll -v`

However, got an error:
`zsh: /usr/local/bin/jekyll: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin: no such file or directory`

It seems my ruby is out of date, so I checked the ruby version again:
`ruby -v`
Output:
`ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin17]`

So when I boot Jekyll, it looks for ruby 2.0, rather than ruby 2.6, which I just installed. 

How can I tell jekyll to use ruby 2.6?
 
Helps needed, thanks!

**Comment by gaoyang86** [comment]
The output of `gem info jekyll` is:

```
*** LOCAL GEMS ***

jekyll (3.8.6)
    Author: Tom Preston-Werner
    Homepage: https://github.com/jekyll/jekyll
    License: MIT
    Installed at: /usr/local/lib/ruby/gems/2.6.0

    A simple, blog aware, static site generator.
```

**Comment by gaoyang86** [comment]
The output of `sudo gem env` is:
```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.4
  - RUBY VERSION: 2.6.3 (2019-04-16 patchlevel 62) [x86_64-darwin17]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/Yang/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /usr/local/opt/ruby/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/lib/ruby/gems/2.6.0/bin
  - SPEC CACHE DIRECTORY: /Users/Yang/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby/2.6.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-17
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.6.0
     - /Users/Yang/.gem/ruby/2.6.0
     - /usr/local/Cellar/ruby/2.6.3/lib/ruby/gems/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/opt/ruby/bin
     - /Users/Yang/anaconda3/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /Library/TeX/texbin
     - /usr/local/aria2/bin
     - /opt/X11/bin
     - /usr/local/git/bin
     - /Users/Yang/.rvm/bin
```

**Comment by ashmaroli** [comment]
This is why we **don't recommend installing Jekyll via `sudo`** in our documentation.
One possible fix would be to reinstall Jekyll **without `sudo`**:
```bash
sudo gem uninstall jekyll -f
gem install jekyll
```

**Comment by gaoyang86** [comment]
@ashmaroli  Thanks for the reply! 

I removed Jekyll using `sudo gem uninstall jekyll --force` (`-f` is ambiguous, and after some searching I found `--force` works)

But `gem install jekyll` led to a permission issue:

```
➜  ~ gem install jekyll
Fetching jekyll-3.8.6.gem
#<Thread:0x00007fb379b2e768@/usr/local/lib/ruby/site_ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	7: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
	6: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
	5: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/source.rb:206:in `download'
	4: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:158:in `download'
	3: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:305:in `cache_update_path'
	2: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:877:in `write_binary'
	1: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:877:in `open'
/usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:877:in `initialize': Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.6.0/cache/jekyll-3.8.6.gem (Errno::EACCES)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.6.0/cache/jekyll-3.8.6.gem
```

May I ask how can I fix this? Thanks in advance :)

**Comment by ashmaroli** [comment]
@DirtyF I'm not very well-versed with permissions on macOS.
Any inputs?

**Comment by DirtyF** [comment]
Maybe start with https://jekyllrb.com/docs/installation/macos/ and let us know how it works.

**Comment by gaoyang86** [comment]
@DirtyF @ashmaroli Thanks for the reply!

Short answer: still got a permission problem.

---Here is what I did---

Gladly, the link that DirtyF posted was the same one that I had already followed before I raised this issue.

So ruby was ready:

```
ruby -v
# ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]
which ruby
#/usr/local/opt/ruby/bin/ruby
```

I started with local Jekyll install:

`gem install --user-install bundler jekyll`

The prompt said that `/Users/Yang/.gem/ruby/2.6.0/bin is not in the path`, so I added it to my .zshrc:

`export PATH=/Users/Yang/.gem/ruby/2.6.0/bin:$PATH`

and then restarted the terminal.

`gem install --user-install bundler jekyll` again, still bumped into a permission problem:

```
Successfully installed bundler-2.0.2
Parsing documentation for bundler-2.0.2
Done installing documentation for bundler after 2 seconds
Fetching jekyll-3.8.6.gem
#<Thread:0x00007fea8cfde340@/usr/local/lib/ruby/site_ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	7: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
	6: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
	5: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/source.rb:206:in `download'
	4: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:158:in `download'
	3: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:305:in `cache_update_path'
	2: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:877:in `write_binary'
	1: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:877:in `open'
/usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:877:in `initialize': Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.6.0/cache/jekyll-3.8.6.gem (Errno::EACCES)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.6.0/cache/jekyll-3.8.6.gem
```

Any suggestions? Thanks!

**Comment by gaoyang86** [comment]
Hi @DirtyF @ashmaroli 
Update:

I worked around this problem by following DirtyF's answer in another issue!

https://github.com/jekyll/jekyll/issues/7170#issuecomment-409529689

Now I could use jekyll to create a new static site:

```
➜  Blogposts jekyll new blog
Running bundle install in /Users/Yang/Projects/Blogposts/blog...
  Bundler: Fetching gem metadata from https://rubygems.org/.................
  Bundler: Fetching gem metadata from https://rubygems.org/..
  Bundler: Resolving dependencies...
  Bundler: Using public_suffix 3.1.1
  Bundler: Using addressable 2.6.0
  Bundler: Using bundler 2.0.2
  Bundler: Using colorator 1.1.0
  Bundler: Using concurrent-ruby 1.1.5
  Bundler: Using eventmachine 1.2.7
  Bundler: Using http_parser.rb 0.6.0
  Bundler: Using em-websocket 0.5.1
  Bundler: Using ffi 1.11.1
  Bundler: Using forwardable-extended 2.6.0
  Bundler: Using i18n 0.9.5
  Bundler: Using rb-fsevent 0.10.3
  Bundler: Using rb-inotify 0.10.0
  Bundler: Using sass-listen 4.0.0
  Bundler: Using sass 3.7.4
  Bundler: Using jekyll-sass-converter 1.5.2
  Bundler: Using ruby_dep 1.5.0
  Bundler: Using listen 3.1.5
  Bundler: Using jekyll-watch 2.2.1
  Bundler: Using kramdown 1.17.0
  Bundler: Using liquid 4.0.3
  Bundler: Using mercenary 0.3.6
  Bundler: Using pathutil 0.16.2
  Bundler: Using rouge 3.7.0
  Bundler: Using safe_yaml 1.0.5
  Bundler: Using jekyll 3.8.6
  Bundler: Using jekyll-feed 0.12.1
  Bundler: Using jekyll-seo-tag 2.6.1
  Bundler: Using minima 2.5.0
  Bundler: Bundle complete! 6 Gemfile dependencies, 29 gems now installed.
  Bundler: Use `bundle info [gemname]` to see where a bundled gem is installed.
New jekyll site installed in /Users/Yang/Projects/Blogposts/blog.
```

---Here is what I did---

First go to config file: `vim ./zshrc`

add these two lines at the end:

```
export GEM_HOME=$HOME/gems
export PATH=$HOME/gems/bin:$PATH
```

restart the terminal, and install jekyll again locally:

`gem install --user-install bundler jekyll`

the output is:

```
Fetching bundler-2.0.2.gem
Successfully installed bundler-2.0.2
Parsing documentation for bundler-2.0.2
Done installing documentation for bundler after 2 seconds
Fetching jekyll-3.8.6.gem
Successfully installed jekyll-3.8.6
Parsing documentation for jekyll-3.8.6
Installing ri documentation for jekyll-3.8.6
Done installing documentation for jekyll after 1 seconds
2 gems installed
```

Then jekyll works! 

Thanks for help!

- Gao Yang

**Comment by ashmaroli** [comment]
@gaoyang86 We're glad that you got it all sorted out successfully.
Happy Jekyllin'! :smiley:
