### ISSUE TITLE
undefined method `fix_common_issues' for #<Jekyll::Configuration:0x0000000006324e10> (NoMethodError)

### ISSUE THREAD

**Issue by memorate** [jekyll/jekyll#7831]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     windows10       |
| `jekyll`         | 4.0.0     |
| `github-pages`   | github-pages 200     |

---

## Expected Behaviour

Is there anybody knows how to fix?!!!!!
#### i ran the command "jekyll server --trance",and it showed:
```
Traceback (most recent call last):
        22: from D:/Ruby/bin/jekyll:23:in `<main>'
        21: from D:/Ruby/bin/jekyll:23:in `load'
        20: from D:/Ruby/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
        19: from D:/Ruby/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        18: from D:/Ruby/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        17: from D:/Ruby/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        16: from D:/Ruby/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        15: from D:/Ruby/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        14: from D:/Ruby/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        13: from D:/Ruby/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
        12: from D:/Ruby/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
        11: from D:/Ruby/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
        10: from D:/Ruby/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:30:in `process'
         9: from D:/Ruby/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:30:in `new'
         8: from D:/Ruby/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:33:in `initialize'
         7: from D:/Ruby/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:114:in `reset'
         6: from D:/Ruby/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/hooks.rb:101:in `trigger'
         5: from D:/Ruby/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/hooks.rb:101:in `each'
         4: from D:/Ruby/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/hooks.rb:102:in `block in trigger'
         3: from D:/Ruby/lib/ruby/gems/2.6.0/gems/github-pages-200/lib/github-pages.rb:19:in `block in <top (required)>'
         2: from D:/Ruby/lib/ruby/gems/2.6.0/gems/github-pages-200/lib/github-pages/configuration.rb:125:in `set'
         1: from D:/Ruby/lib/ruby/gems/2.6.0/gems/github-pages-200/lib/github-pages/configuration.rb:132:in `set!'
D:/Ruby/lib/ruby/gems/2.6.0/gems/github-pages-200/lib/github-pages/configuration.rb:101:in `effective_config': undefined method `fix_common_issues' for #<Jekyll::Configuration:0x0000000006324e10> (NoMethodError)
```

Help!!!!!     THANKS A LOT
## Additional
And i fuound the "fix_common_issues" method in the configuration.rb, below 11th line is that:
```
      # Given a user's config, determines the effective configuration by building a user
      # configuration sandwhich with our overrides overriding the user's specified
      # values which themselves override our defaults.
      #
      # Returns the effective Configuration
      #
      # Note: this is a highly modified version of Jekyll#configuration
      def effective_config(user_config)
        # Merge user config into defaults
        config = Jekyll::Utils.deep_merge_hashes(defaults_for_env, user_config)
          .fix_common_issues
          .add_default_collections

        # Allow theme to be explicitly disabled via "theme: null"
        config["theme"] = user_config["theme"] if user_config.key?("theme")

        exclude_cname(config)

        # Merge overwrites into user config
        config = Jekyll::Utils.deep_merge_hashes config, OVERRIDES

        restrict_and_config_markdown_processor(config)

        configure_plugins(config)

        config
      end
```
#### i have tried to uninstall github-pages 200 and install github-pages 196, but unfortunately it also can't work.

**Comment by ashmaroli** [comment]
Technically, `github-pages` is not compatible with Jekyll 4.0 yet.

**Comment by DirtyF** [comment]
And I'm not sure they will given you can build with Github Actions now.
