### ISSUE TITLE
Cannot build the project : failed to load command: jekyll and undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by NoobiCodi** [jekyll/jekyll#7863]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |macOS 10.15            |
| `jekyll`         | jekyll 4.0.0     |
| `github-pages`   | No     |
| `ruby`   | ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]     |

---

Hello, 
I wanted to build my project but I got an error :

```shell
bundle exec jekyll build --trace
```
```
bundler: failed to load command: jekyll (/Project/vendor/bundle/ruby/2.6.0/bin/jekyll)
NoMethodError: undefined method `+' for nil:NilClass
  /Project/_plugins/sitemap-generator.rb:184:in `fill_location'
  /Project/_plugins/sitemap-generator.rb:144:in `fill_url'
  /Project/_plugins/sitemap-generator.rb:111:in `block in fill_posts'
  /Project/_plugins/sitemap-generator.rb:109:in `each'
  /Project/_plugins/sitemap-generator.rb:109:in `fill_posts'
  /Project/_plugins/sitemap-generator.rb:83:in `generate'
  /Project/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:185:in `block in generate'
  /Project/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:183:in `each'
  /Project/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:183:in `generate'
  /Project/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:75:in `process'
  /Project/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
  /Project/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
  /Project/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
  /Project/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
  /Project/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
  /Project/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
  /Project/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /Project/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Project/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Project/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Project/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Project/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Project/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
  /Project/vendor/bundle/ruby/2.6.0/bin/jekyll:23:in `load'
  /Project/vendor/bundle/ruby/2.6.0/bin/jekyll:23:in `<top (required)>'
```
Here is my gemfile : 
```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "jekyll", "~> 4.0"

group :jekyll_plugins do
 	gem 'jekyll-sitemap'
	gem 'jekyll-admin'
end
```
and my config :
```yml
markdown: kramdown
baseurl: ""
exclude: ["start"]
include: ["_pages", "_images"]
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-admin
```
Nota bene : the command `bundle exec jekyll serve` works

**Comment by ashmaroli** [comment]
The error is stemming from `_plugins/sitemap-generator.rb:184`.. Removing that plugin should resolve this..

**Comment by NoobiCodi** [comment]
Its worked ! thanks a lot, i was afraid about a big error 😆
