### ISSUE TITLE
Issue when running jekyll serve: no implicit conversion of String into Integer (TypeError)

### ISSUE THREAD

**Issue by alexgt1** [jekyll/jekyll#7866]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Mojave |            | 10.14.16
| `jekyll`         | Latest     |
| no   | no     |

---

## Expected Behaviour

Site is built in my local environment 

## Current Behavior

```
 Generating... 
Traceback (most recent call last):
	23: from /Users/george/.gem/ruby/2.6.0/bin/jekyll:23:in `<main>'
	22: from /Users/george/.gem/ruby/2.6.0/bin/jekyll:23:in `load'
	21: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
	20: from /usr/local/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	19: from /usr/local/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	18: from /usr/local/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	17: from /usr/local/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	16: from /usr/local/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	15: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	14: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	13: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
	12: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	11: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
	10: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
	 9: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
	 8: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:74:in `process'
	 7: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:174:in `read'
	 6: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/reader.rb:20:in `read'
	 5: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/readers/collection_reader.rb:17:in `read'
	 4: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/readers/collection_reader.rb:17:in `each_value'
	 3: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/readers/collection_reader.rb:18:in `block in read'
	 2: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/collection.rb:68:in `read'
	 1: from /Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/collection.rb:223:in `sort_docs!'
/Users/george/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/collection.rb:223:in `[]': no implicit conversion of String into Integer (TypeError)
```

## Code Sample

jekyll serve

**Comment by ashmaroli** [comment]
Please check your **`collections:`** configuration in your `_config.yml`. It has to either be a list of items or a map of key-value pairs.
Remember YAML is sensitive to indentation.

The code under the scanner reads as:
```rb
# lib/jekyll/collection.rb:223

if metadata["order"].is_a?(Array)
```
```
no implicit conversion of String into Integer
```
means that `metadata` has been evaluated into a String which is invalid.

**Comment by alexgt1** [comment]
Thanks a lot! 
It was caused by an indentation error.
