### ISSUE TITLE
jekyll 4.0 trace

### ISSUE THREAD

**Issue by tophackr** [jekyll/jekyll#7952]
in the continuation of not working #7936

```
MBP-Aleksandr:calendar tophackr$ bundle exec jekyll serve
Configuration file: /Users/tophackr/Documents/Jekyll/calendar/_config.yml
            Source: /Users/tophackr/Documents/Jekyll/calendar
       Destination: /Users/tophackr/Documents/Jekyll/calendar/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.143 seconds.
 Auto-regeneration: enabled for '/Users/tophackr/Documents/Jekyll/calendar'
                    ------------------------------------------------
      Jekyll 4.0.0   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
```
```
MBP-Aleksandr:calendar tophackr$ bundle exec jekyll serve --trace
Configuration file: /Users/tophackr/Documents/Jekyll/calendar/_config.yml
            Source: /Users/tophackr/Documents/Jekyll/calendar
       Destination: /Users/tophackr/Documents/Jekyll/calendar/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.152 seconds.
 Auto-regeneration: enabled for '/Users/tophackr/Documents/Jekyll/calendar'
Traceback (most recent call last):
	26: from /Users/tophackr/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	25: from /Users/tophackr/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	24: from /Users/tophackr/.rvm/gems/ruby-2.6.3/bin/jekyll:23:in `<main>'
	23: from /Users/tophackr/.rvm/gems/ruby-2.6.3/bin/jekyll:23:in `load'
	22: from /Users/tophackr/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
	21: from /Users/tophackr/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	20: from /Users/tophackr/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	19: from /Users/tophackr/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	18: from /Users/tophackr/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	17: from /Users/tophackr/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	16: from /Users/tophackr/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	15: from /Users/tophackr/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	14: from /Users/tophackr/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
	13: from /Users/tophackr/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	12: from /Users/tophackr/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:102:in `process'
	11: from /Users/tophackr/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:215:in `start_up_webrick'
	10: from /Users/tophackr/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:215:in `new'
	 9: from /Users/tophackr/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/webrick/httpserver.rb:47:in `initialize'
	 8: from /Users/tophackr/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/webrick/server.rb:108:in `initialize'
	 7: from /Users/tophackr/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/webrick/server.rb:127:in `listen'
	 6: from /Users/tophackr/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/webrick/utils.rb:65:in `create_listeners'
	 5: from /Users/tophackr/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/socket.rb:762:in `tcp_server_sockets'
	 4: from /Users/tophackr/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/socket.rb:227:in `foreach'
	 3: from /Users/tophackr/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/socket.rb:227:in `each'
	 2: from /Users/tophackr/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/socket.rb:764:in `block in tcp_server_sockets'
	 1: from /Users/tophackr/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/socket.rb:201:in `listen'
/Users/tophackr/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/socket.rb:201:in `bind': Address already in use - bind(2) for 127.0.0.1:4000 (Errno::EADDRINUSE)```

**Comment by DirtyF** [comment]
This is not a Jekyll bug but a problem with your Ruby installl, if our documentation doesn't help, feel free to [ask for help our our forum](https://talk.jekyllrb.com).

**Comment by ashmaroli** [comment]
The error message should give you a hint:
```
Address already in use - bind(2) for 127.0.0.1:4000 (Errno::EADDRINUSE)
```
You already have a server running and mounted at `http://localhost:4000`. Stop whatever that is and try serving again.
