### ISSUE TITLE
undefined method `really_windows?' for Jekyll::Utils::Platforms:Module (NoMethodError)

### ISSUE THREAD

**Issue by BenLeggiero** [jekyll/jekyll#7984]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Ubuntu 18.04.2 LTS on Windows Subsystem for Linux on Windows 10 Pro 1903 |
| `jekyll`         | 3.8.5      |
| `github-pages`   | 204        |

---

## Expected Behaviour

No `NoSuchMethod` errors

## Current Behavior

```bash
$ bundle exec jekyll serve --trace --incremental
/var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/drops/document_drop.rb:8: warning: already initialized constant Jekyll::Drops::DocumentDrop::NESTED_OBJECT_FIELD_BLACKLIST
/usr/lib/ruby/vendor_ruby/jekyll/drops/document_drop.rb:8: warning: previous definition of NESTED_OBJECT_FIELD_BLACKLIST was here
/var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/drops/drop.rb:8: warning: already initialized constant Jekyll::Drops::Drop::NON_CONTENT_METHODS
/usr/lib/ruby/vendor_ruby/jekyll/drops/drop.rb:8: warning: previous definition of NON_CONTENT_METHODS was here
/usr/lib/ruby/vendor_ruby/jekyll/hooks.rb:56: warning: constant ::Fixnum is deprecated
Configuration file: /home/supuhstar/Projects/Collaborative/SapphDavis.me/_config.yml
Traceback (most recent call last):
        14: from /usr/local/bin/jekyll:23:in `<main>'
        13: from /usr/local/bin/jekyll:23:in `load'
        12: from /var/lib/gems/2.5.0/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
        11: from /usr/lib/ruby/vendor_ruby/mercenary.rb:19:in `program'
        10: from /usr/lib/ruby/vendor_ruby/mercenary/program.rb:42:in `go'
         9: from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `execute'
         8: from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `each'
         7: from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `block in execute'
         6: from /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
         5: from /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:89:in `start'
         4: from /usr/lib/ruby/vendor_ruby/jekyll/command.rb:40:in `configuration_from_options'
         3: from /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll.rb:117:in `configuration'
         2: from /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll.rb:117:in `tap'
         1: from /var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll.rb:118:in `block in configuration'
/var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll.rb:129:in `set_timezone': undefined method `really_windows?' for Jekyll::Utils::Platforms:Module (NoMethodError)
```

### Command:

```bash
bundle exec jekyll serve --trace --incremental
```

### Gemfile.lock:

```gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (6.0.2.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.2)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.11.1)
    colorator (1.1.0)
    commonmarker (0.17.13)
      ruby-enum (~> 0.5)
    concurrent-ruby (1.1.5)
    dnsruby (1.61.3)
      addressable (~> 2.5)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    ethon (0.12.0)
      ffi (>= 1.3.0)
    eventmachine (1.2.7)
    execjs (2.7.0)
    faraday (1.0.0)
      multipart-post (>= 1.2, < 3)
    ffi (1.12.1)
    forwardable-extended (2.6.0)
    gemoji (3.0.1)
    github-pages (204)
      github-pages-health-check (= 1.16.1)
      jekyll (= 3.8.5)
      jekyll-avatar (= 0.7.0)
      jekyll-coffeescript (= 1.1.1)
      jekyll-commonmark-ghpages (= 0.1.6)
      jekyll-default-layout (= 0.1.4)
      jekyll-feed (= 0.13.0)
      jekyll-gist (= 1.5.0)
      jekyll-github-metadata (= 2.13.0)
      jekyll-mentions (= 1.5.1)
      jekyll-optional-front-matter (= 0.3.2)
      jekyll-paginate (= 1.1.0)
      jekyll-readme-index (= 0.3.0)
      jekyll-redirect-from (= 0.15.0)
      jekyll-relative-links (= 0.6.1)
      jekyll-remote-theme (= 0.4.1)
      jekyll-sass-converter (= 1.5.2)
      jekyll-seo-tag (= 2.6.1)
      jekyll-sitemap (= 1.4.0)
      jekyll-swiss (= 1.0.0)
      jekyll-theme-architect (= 0.1.1)
      jekyll-theme-cayman (= 0.1.1)
      jekyll-theme-dinky (= 0.1.1)
      jekyll-theme-hacker (= 0.1.1)
      jekyll-theme-leap-day (= 0.1.1)
      jekyll-theme-merlot (= 0.1.1)
      jekyll-theme-midnight (= 0.1.1)
      jekyll-theme-minimal (= 0.1.1)
      jekyll-theme-modernist (= 0.1.1)
      jekyll-theme-primer (= 0.5.4)
      jekyll-theme-slate (= 0.1.1)
      jekyll-theme-tactile (= 0.1.1)
      jekyll-theme-time-machine (= 0.1.1)
      jekyll-titles-from-headings (= 0.5.3)
      jemoji (= 0.11.1)
      kramdown (= 1.17.0)
      liquid (= 4.0.3)
      mercenary (~> 0.3)
      minima (= 2.5.1)
      nokogiri (>= 1.10.4, < 2.0)
      rouge (= 3.13.0)
      terminal-table (~> 1.4)
    github-pages-health-check (1.16.1)
      addressable (~> 2.3)
      dnsruby (~> 1.60)
      octokit (~> 4.0)
      public_suffix (~> 3.0)
      typhoeus (~> 1.3)
    html-pipeline (2.12.3)
      activesupport (>= 2)
      nokogiri (>= 1.4)
    http_parser.rb (0.6.0)
    i18n (0.9.5)
      concurrent-ruby (~> 1.0)
    jekyll (3.8.5)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 0.7)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 1.14)
      liquid (~> 4.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (>= 1.7, < 4)
      safe_yaml (~> 1.0)
    jekyll-avatar (0.7.0)
      jekyll (>= 3.0, < 5.0)
    jekyll-coffeescript (1.1.1)
      coffee-script (~> 2.2)
      coffee-script-source (~> 1.11.1)
    jekyll-commonmark (1.3.1)
      commonmarker (~> 0.14)
      jekyll (>= 3.7, < 5.0)
    jekyll-commonmark-ghpages (0.1.6)
      commonmarker (~> 0.17.6)
      jekyll-commonmark (~> 1.2)
      rouge (>= 2.0, < 4.0)
    jekyll-default-layout (0.1.4)
      jekyll (~> 3.0)
    jekyll-feed (0.13.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-gist (1.5.0)
      octokit (~> 4.2)
    jekyll-github-metadata (2.13.0)
      jekyll (>= 3.4, < 5.0)
      octokit (~> 4.0, != 4.4.0)
    jekyll-mentions (1.5.1)
      html-pipeline (~> 2.3)
      jekyll (>= 3.7, < 5.0)
    jekyll-optional-front-matter (0.3.2)
      jekyll (>= 3.0, < 5.0)
    jekyll-paginate (1.1.0)
    jekyll-readme-index (0.3.0)
      jekyll (>= 3.0, < 5.0)
    jekyll-redirect-from (0.15.0)
      jekyll (>= 3.3, < 5.0)
    jekyll-relative-links (0.6.1)
      jekyll (>= 3.3, < 5.0)
    jekyll-remote-theme (0.4.1)
      addressable (~> 2.0)
      jekyll (>= 3.5, < 5.0)
      rubyzip (>= 1.3.0)
    jekyll-sass-converter (1.5.2)
      sass (~> 3.4)
    jekyll-seo-tag (2.6.1)
      jekyll (>= 3.3, < 5.0)
    jekyll-sitemap (1.4.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-swiss (1.0.0)
    jekyll-theme-architect (0.1.1)
      jekyll (~> 3.5)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-cayman (0.1.1)
      jekyll (~> 3.5)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-dinky (0.1.1)
      jekyll (~> 3.5)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-hacker (0.1.1)
      jekyll (~> 3.5)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-leap-day (0.1.1)
      jekyll (~> 3.5)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-merlot (0.1.1)
      jekyll (~> 3.5)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-midnight (0.1.1)
      jekyll (~> 3.5)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-minimal (0.1.1)
      jekyll (~> 3.5)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-modernist (0.1.1)
      jekyll (~> 3.5)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-primer (0.5.4)
      jekyll (> 3.5, < 5.0)
      jekyll-github-metadata (~> 2.9)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-slate (0.1.1)
      jekyll (~> 3.5)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-tactile (0.1.1)
      jekyll (~> 3.5)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-time-machine (0.1.1)
      jekyll (~> 3.5)
      jekyll-seo-tag (~> 2.0)
    jekyll-titles-from-headings (0.5.3)
      jekyll (>= 3.3, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    jemoji (0.11.1)
      gemoji (~> 3.0)
      html-pipeline (~> 2.2)
      jekyll (>= 3.0, < 5.0)
    kramdown (1.17.0)
    liquid (4.0.3)
    listen (3.2.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.3.6)
    mini_portile2 (2.4.0)
    minima (2.5.1)
      jekyll (>= 3.5, < 5.0)
      jekyll-feed (~> 0.9)
      jekyll-seo-tag (~> 2.1)
    minitest (5.14.0)
    multipart-post (2.1.1)
    nokogiri (1.10.7)
      mini_portile2 (~> 2.4.0)
    octokit (4.15.0)
      faraday (>= 0.9)
      sawyer (~> 0.8.0, >= 0.5.3)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (3.1.1)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rouge (3.13.0)
    ruby-enum (0.7.2)
      i18n
    rubyzip (2.1.0)
    safe_yaml (1.0.5)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sawyer (0.8.2)
      addressable (>= 2.3.5)
      faraday (> 0.8, < 2.0)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    thread_safe (0.3.6)
    typhoeus (1.3.1)
      ethon (>= 0.9.0)
    tzinfo (1.2.6)
      thread_safe (~> 0.1)
    unicode-display_width (1.6.1)
    zeitwerk (2.2.2)

PLATFORMS
  ruby

DEPENDENCIES
  github-pages
  jekyll-feed (~> 0.6)
  jekyll-redirect-from
  jekyll-sitemap

BUNDLED WITH
   1.16.1
```

---

Do let me know if there's anything else I can provide which might help solve this issue! 😄

**Comment by ashmaroli** [comment]
You have two versions of Jekyll.
- One version vendored by your docker-image or Debian package-manager  or similar:
  ```
  /usr/lib/ruby/vendor_ruby/jekyll/
  ```
- Another version installed as part of GitHub Pages:
  ```
  /var/lib/gems/2.5.0/gems/jekyll-3.8.5/
  ```

If you have the permission to delete the entire Jekyll folder inside ` /usr/lib/ruby/vendor_ruby/`, you're good to go.
