### ISSUE TITLE
mojave installation problems

### ISSUE THREAD

**Issue by RDMelamed** [jekyll/jekyll#8027]
I honestly tried so many things that I'm not sure what fixed it, but I was getting this error:

```
[~]> gem install bundler jekyll
Successfully installed bundler-2.1.4
Parsing documentation for bundler-2.1.4
Done installing documentation for bundler after 1 seconds
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
 	ERROR: Failed to build gem native extension.
    current directory: /Users/melamed/gems/gems/ffi-1.12.2/ext/ffi_c
/usr/local/opt/ruby/bin/ruby -I /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0 -r ./siteconf20200225-46738-1jma0xi.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... yes
checking for ffi_call() in -lffi... yes
checking for ffi_closure_alloc()... no
checking for shlwapi.h... no
checking for rb_thread_call_without_gvl()... yes
checking for ruby_native_thread_p()... yes
checking for ruby_thread_has_gvl_p()... yes
creating extconf.h
creating Makefile
current directory: /Users/melamed/gems/gems/ffi-1.12.2/ext/ffi_c
make "DESTDIR=" clean
current directory: /Users/melamed/gems/gems/ffi-1.12.2/ext/ffi_c
make "DESTDIR="
Configuring libffi
clang-4.0: error: unsupported option '-print-multi-os-directory'
clang-4.0: error: no input files
```

I think I fixed it by getting ffi installed, which was its own nightmare finally solved here: https://github.com/ffi/ffi/issues/611#issuecomment-364621532

**Comment by RDMelamed** [comment]
Nope, spoke too soon. The installation no longer gives an error but it does not work at all, ie

```
> jekyll build
Traceback (most recent call last):
	7: from /Users/melamed/gems/bin/jekyll:23:in `<main>'
	6: from /Users/melamed/gems/bin/jekyll:23:in `load'
	5: from /Users/melamed/.gem/ruby/2.7.0/gems/jekyll-4.0.0/exe/jekyll:8:in `<top (required)>'
	4: from /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	3: from /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	2: from /Users/melamed/.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll.rb:32:in `<top (required)>'
	1: from /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
```

**Comment by RDMelamed** [comment]
Ugh I had to give up on Jekyll. I spent a lot of time, at least 8 hours, trying to get basic things to run but I could only ever get the tutorial working. I guess it's less complicated on older versions of OSX.
