### ISSUE TITLE
Error when running `jekyll new .`

### ISSUE THREAD

**Issue by paniash** [jekyll/jekyll#8145]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Arch Linux  |
| `jekyll`         | 4.0.0   |
| `github-pages`   | Latest     |

---

## Expected Behaviour
Running `jekyll new .` in my current working directory should make a new `jekyll` environment in the directory.

## Current Behavior
When running `jekyll new .` in my current working directory, I get a huge error log that I don't understand why it's happening.

## Code Sample
```
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': libffi.so.6: cannot open shared object file: No such file or directory - /home/ashish/.gem/ruby/2.7.0/extensions/x86_64-linux/2.7.0/ffi-1.12.2/ffi_c.so (LoadError)
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/ashish/.gem/ruby/2.7.0/gems/ffi-1.12.2/lib/ffi.rb:6:in `rescue in <top (required)>'
	from /home/ashish/.gem/ruby/2.7.0/gems/ffi-1.12.2/lib/ffi.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/ashish/.gem/ruby/2.7.0/gems/sassc-2.3.0/lib/sassc/native.rb:3:in `<top (required)>'
	from /home/ashish/.gem/ruby/2.7.0/gems/sassc-2.3.0/lib/sassc.rb:31:in `require_relative'
	from /home/ashish/.gem/ruby/2.7.0/gems/sassc-2.3.0/lib/sassc.rb:31:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/ashish/.gem/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/ashish/.gem/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/ashish/.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll.rb:206:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/ashish/.gem/ruby/2.7.0/gems/jekyll-4.0.0/exe/jekyll:8:in `<top (required)>'
	from /home/ashish/.gem/ruby/2.7.0/bin/jekyll:23:in `load'
	from /home/ashish/.gem/ruby/2.7.0/bin/jekyll:23:in `<main>'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- 2.7/ffi_c (LoadError)
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/ashish/.gem/ruby/2.7.0/gems/ffi-1.12.2/lib/ffi.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/ashish/.gem/ruby/2.7.0/gems/sassc-2.3.0/lib/sassc/native.rb:3:in `<top (required)>'
	from /home/ashish/.gem/ruby/2.7.0/gems/sassc-2.3.0/lib/sassc.rb:31:in `require_relative'
	from /home/ashish/.gem/ruby/2.7.0/gems/sassc-2.3.0/lib/sassc.rb:31:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/ashish/.gem/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/ashish/.gem/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/ashish/.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll.rb:206:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/ashish/.gem/ruby/2.7.0/gems/jekyll-4.0.0/exe/jekyll:8:in `<top (required)>'
	from /home/ashish/.gem/ruby/2.7.0/bin/jekyll:23:in `load'
	from /home/ashish/.gem/ruby/2.7.0/bin/jekyll:23:in `<main>'
```

**Comment by ashmaroli** [comment]
By default, Jekyll doesn't allow initializing a non-empty directory as Jekyll workspace. So,
`jekyll new .` raising an error is expected.
The recommended route is to move up to the parent directory and running `jekyll new <name>`. If it is not empty, you need to pass it the `--force` switch as well.

That said, when you installed the `jekyll` gem, was there any error?
From the error report above, a gem named `ffi` did not install properly. Try reinstalling that gem by running the following commands:
```
gem uninstall ffi
gem install ffi
```
Then try running `jekyll new <name>` again.

**Comment by paniash** [comment]
Thank you very much. Uninstalling and reinstalling `ffi` seemed to solve the issue. I was not aware of the fact that Jekyll doesn't initialize non-empty directories. Thank you very much :)

**Comment by benthayer** [comment]
Wow! I just installed jekyll on Arch today and had the _exact same issue_ . Glad to see it resolved so fast. Maybe this issue deserves to be re-opened?

**Comment by ashmaroli** [comment]
@benthayer Why reopen? If it is the *exact same issue*, then the *exact same solution* applies.., don't they?

**Comment by benthayer** [comment]
Being on a fresh install, I guess it's my assumption that somehow that package isn't installing correctly because of some issue with the install script and that it would make sense to update whatever install scripts are causing that issue.

I'm not sure though, could just be some weird thing I did on accident, and fixing it would probably lead down a rabbit hole, but since we posted within a day of each other, it makes me think some updates on arch have caused this issue and it will happen for others also.
