### ISSUE TITLE
undefined method `to_i' for date

### ISSUE THREAD

**Issue by guoyunhe** [jekyll/jekyll#8146]
- I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
  - I ran `jekyll doctor` to check my configuration
  - I read the contributing document at https://jekyllrb.com/docs/contributing/

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |           openSUSE Tumbleweed |
| `jekyll`         | 4.0.0 |
| `github-pages`   | No |

---

## Expected Behaviour
Should compile

## Current Behavior

Compile error:

```
Configuration file: /home/guo/git/suse/jekyll-theme/_config.yml
            Source: /home/guo/git/suse/jekyll-theme
       Destination: /home/guo/git/suse/jekyll-theme/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Traceback (most recent call last):
        33: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/bin/jekyll:23:in `<main>'
        32: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/bin/jekyll:23:in `load'
        31: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
        30: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        29: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        28: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        27: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        26: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        25: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        24: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
        23: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
        22: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
        21: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
        20: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
        19: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
        18: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:76:in `process'
        17: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:202:in `render'
        16: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:515:in `render_pages'
        15: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:515:in `each'
        14: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:516:in `block in render_pages'
        13: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:523:in `render_regenerated'
        12: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:61:in `run'
        11: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/page.rb:179:in `trigger_hooks'
        10: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/hooks.rb:101:in `trigger'
         9: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/hooks.rb:101:in `each'
         8: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/hooks.rb:102:in `block in trigger'
         7: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/bundler/gems/jekyll-locale-dc5c46cadd09/lib/jekyll-locale.rb:45:in `block in <top (required)>'
         6: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/bundler/gems/jekyll-locale-dc5c46cadd09/lib/jekyll/locale/mixins/support.rb:16:in `hreflangs'
         5: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/bundler/gems/jekyll-locale-dc5c46cadd09/lib/jekyll/locale/mixins/support.rb:30:in `sibling_data'
         4: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/bundler/gems/jekyll-locale-dc5c46cadd09/lib/jekyll/locale/mixins/support.rb:30:in `map'
         3: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/bundler/gems/jekyll-locale-dc5c46cadd09/lib/jekyll/locale/mixins/support.rb:31:in `block in sibling_data'
         2: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/bundler/gems/jekyll-locale-dc5c46cadd09/lib/jekyll/locale/mixins/support.rb:24:in `publish?'
         1: from /home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/publisher.rb:10:in `publish?'
/home/guo/git/suse/jekyll-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/publisher.rb:14:in `hidden_in_the_future?': undefined method `to_i' for #<Date: 2018-01-01 ((2458120j,0s,0n),+0s,2299161j)> (NoMethodError)
Did you mean?  to_s
```

## Code Sample

I am working on this branch https://github.com/openSUSE/jekyll-theme/tree/l10n-feat

```
bundle exec jekyll serve --trace
```

It looks like the same issue as #7110

**Comment by guoyunhe** [comment]
Turn off `jekyll-archives` plugin or downgrade `jekyll` solve the issue.

**Comment by ashmaroli** [comment]
> downgrade `jekyll` solve the issue

By downgrade, what Jekyll version were you suggesting downgrading to..?

**Comment by guoyunhe** [comment]
@ashmaroli jekyll 3.8 seems work

**Comment by ashmaroli** [comment]
Oh. Jekyll 3.6 is a bit very old. Did you try testing with Jekyll 3.7 and Jekyll 3.8 too..?
If not, don't bother..

**Comment by guoyunhe** [comment]
No, just 3.6 and 4.0...

**Comment by DirtyF** [comment]
Please provide an example public repository when we can reproduce the issue. Thanks.

**Comment by guoyunhe** [comment]
Please pull https://github.com/openSUSE/jekyll-theme/tree/l10n-feat

**Comment by DirtyF** [comment]
Not reproduced:

```
jekyll-opensuse-theme on  master [!?] via 💎 v2.7.1
 bundle list | grep jekyll
  * jekyll (4.0.1)
  * jekyll-archives (2.1.1)
  * jekyll-paginate (1.1.0)
  * jekyll-sass-converter (2.1.0)
  * jekyll-watch (2.2.1)

jekyll-opensuse-theme on  master [!?] via 💎 v2.7.1
 bundle exec jekyll build
Configuration file: /Users/frank/code/jekyll-opensuse-theme/_config.yml
            Source: /Users/frank/code/jekyll-opensuse-theme
       Destination: /Users/frank/code/jekyll-opensuse-theme/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.167 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

Closing as it does not look like an issue with core jekyll package.
