### ISSUE TITLE
Error: `keep_dirs': undefined method `flat_map' for "assets":String (NoMethodError)

### ISSUE THREAD

**Issue by germanfr** [jekyll/jekyll#8232]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Fedora 32          |
| `jekyll`         | 4.0.1 (there are no newer versions in Fedora) |
| `github-pages`   | No     |

---

## Expected Behaviour

Expected to not fail or ignore the keep_files setting.

## Current Behavior

I generate my CSS and JS files with gulp and place them directly in the `_site/assets/` folder, so I need to use the `keep_files: assets` option so that jekyll does not erase them. But when I run `$ jekyll build` I get this error and jekyll stops:

```
Traceback (most recent call last):
	20: from /usr/bin/jekyll:23:in `<main>'
	19: from /usr/bin/jekyll:23:in `load'
	18: from /usr/share/gems/gems/jekyll-4.0.1/exe/jekyll:15:in `<top (required)>'
	17: from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	16: from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	15: from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	14: from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	13: from /usr/share/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	12: from /usr/share/gems/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	11: from /usr/share/gems/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	10: from /usr/share/gems/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `each'
	 9: from /usr/share/gems/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	 8: from /usr/share/gems/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:36:in `process'
	 7: from /usr/share/gems/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:65:in `build'
	 6: from /usr/share/gems/gems/jekyll-4.0.1/lib/jekyll/command.rb:28:in `process_site'
	 5: from /usr/share/gems/gems/jekyll-4.0.1/lib/jekyll/site.rb:77:in `process'
	 4: from /usr/share/gems/gems/jekyll-4.0.1/lib/jekyll/site.rb:211:in `cleanup'
	 3: from /usr/share/gems/gems/jekyll-4.0.1/lib/jekyll/cleaner.rb:15:in `cleanup!'
	 2: from /usr/share/gems/gems/jekyll-4.0.1/lib/jekyll/cleaner.rb:25:in `obsolete_files'
	 1: from /usr/share/gems/gems/jekyll-4.0.1/lib/jekyll/cleaner.rb:44:in `existing_files'
/usr/share/gems/gems/jekyll-4.0.1/lib/jekyll/cleaner.rb:97:in `keep_dirs': undefined method `flat_map' for "assets":String (NoMethodError)
```

I'm not sure if this is already solved in the latest version, but I didn't find any bug report of this. So just in case...

### _config.yml

```yml
author: '...'
title: '...'
description: '...'
# url: https://...

timezone: Europe/Madrid
source: src/site/
keep_files: assets
```

### My project file structure

```
├── _config.yml
├── gulpfile.js
├── package.json
├── _site
│   ├── assets
│   │   ├── css
│   │   │   ├── main.css
│   │   └── js
│   │       └── index.min.js
│   └── index.html
└── src
    ├── js
    │   └── index.js
    ├── scss
    │   ├── _headerbar.scss
    │   └── main.scss
    └── site
        └── index.html
```

(All files in src/ are empty).

**Comment by ashmaroli** [comment]
Based on the source code:
https://github.com/jekyll/jekyll/blob/81c13507c8222a97f62ecad1c9804eb42a074b93/lib/jekyll/configuration.rb#L23
and documentation at https://jekyllrb.com/docs/configuration/default/
`keep_dirs:` should point to an array.

So, the config would be:
```yaml
keep_dirs:
- .git
- .svn
- assets

**Comment by germanfr** [comment]
@ashmaroli Sorry, my bad. Thank you. 

Anyways, I ran `$ jekyll doctor` before posting the issue but it didn't complain at all. I'm not sure if it is supposed to detect these kind of errors.
