### ISSUE TITLE
Jekyll is not runing on my pc anyone

### ISSUE THREAD

**Issue by gustavolinux** [jekyll/jekyll#8267]
bundle exec jekyll serve --port 8080 --host localhost
```
Configuration file: /home/gustavo/Dropbox/Drop-Documents/Eu Professor/Website/_config.yml
/usr/lib/ruby/gems/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/lib/ruby/gems/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/lib/ruby/gems/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/lib/ruby/gems/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/lib/ruby/gems/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/lib/ruby/gems/2.7.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:55: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
            Source: /home/gustavo/Dropbox/Drop-Documents/Eu Professor/Website
       Destination: /home/gustavo/Dropbox/Drop-Documents/Eu Professor/Website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
                    done in 0.74 seconds.
/home/gustavo/.gem/ruby/2.7.0/gems/pathutil-0.16.2/lib/pathutil.rb:502: warning: Using the last argument as keyword parameters is deprecated
bundler: failed to load command: jekyll (/usr/bin/jekyll)
LoadError: libffi.so.6: cannot open shared object file: No such file or directory - /usr/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/ffi-1.11.1/ffi_c.so
  /usr/lib/ruby/gems/2.7.0/gems/ffi-1.11.1/lib/ffi.rb:6:in `require'
  /usr/lib/ruby/gems/2.7.0/gems/ffi-1.11.1/lib/ffi.rb:6:in `rescue in <top (required)>'
  /usr/lib/ruby/gems/2.7.0/gems/ffi-1.11.1/lib/ffi.rb:3:in `<top (required)>'
  /usr/lib/ruby/gems/2.7.0/gems/rb-inotify-0.10.0/lib/rb-inotify/native.rb:1:in `require'
  /usr/lib/ruby/gems/2.7.0/gems/rb-inotify-0.10.0/lib/rb-inotify/native.rb:1:in `<top (required)>'
  /usr/lib/ruby/gems/2.7.0/gems/rb-inotify-0.10.0/lib/rb-inotify.rb:2:in `require'
  /usr/lib/ruby/gems/2.7.0/gems/rb-inotify-0.10.0/lib/rb-inotify.rb:2:in `<top (required)>'
  /usr/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/adapter/linux.rb:30:in `require'
  /usr/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/adapter/linux.rb:30:in `_configure'
  /usr/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:45:in `block in configure'
  /usr/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:40:in `each'
  /usr/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:40:in `configure'
  /usr/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:63:in `start'
  /usr/lib/ruby/2.7.0/forwardable.rb:235:in `start'
  /usr/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/listener.rb:68:in `block in <class:Listener>'
  /usr/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `instance_eval'
  /usr/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `call'
  /usr/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
  /usr/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/fsm.rb:57:in `transition'
  /usr/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/listener.rb:91:in `start'
  /usr/lib/ruby/gems/2.7.0/gems/jekyll-watch-2.2.1/lib/jekyll/watcher.rb:26:in `watch'
  /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/build.rb:94:in `call'
  /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/build.rb:94:in `watch'
  /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/build.rb:43:in `process'
  /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/serve.rb:93:in `block in start'
  /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/serve.rb:93:in `each'
  /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/serve.rb:93:in `start'
  /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
  /home/gustavo/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /home/gustavo/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /home/gustavo/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /home/gustavo/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /home/gustavo/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/exe/jekyll:15:in `<top (required)>'
  /usr/bin/jekyll:23:in `load'
  /usr/bin/jekyll:23:in `<top (required)>'
```

**Comment by DirtyF** [comment]
Please use the proper issue template and provide more information about your context.
