### ISSUE TITLE
Kramdown not working

### ISSUE THREAD

**Issue by alexandre1985** [jekyll/jekyll#8295]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |    Archlinux 5.4.50       |
| `jekyll`         | Latest   4.1.1  |

---

## Expected Behaviour

Compile markdown tags

## Current Behavior

not compiling

## Jekyll
```
$ jekyll doctor                                                                                                               
Configuration file: /home/daniel/me/coding/web/pagina-pessoal/_config.yml
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
jekyll 3.8.6 | Error:  no implicit conversion of nil into String
Traceback (most recent call last):
        39: from /home/daniel/.gem/ruby/2.7.0/bin/bundle:23:in `<main>'
        38: from /home/daniel/.gem/ruby/2.7.0/bin/bundle:23:in `load'
        37: from /home/daniel/.gem/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
        36: from /home/daniel/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
        35: from /home/daniel/.gem/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
        34: from /home/daniel/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
        33: from /home/daniel/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
        32: from /home/daniel/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
        31: from /home/daniel/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
        30: from /home/daniel/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        29: from /home/daniel/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        28: from /home/daniel/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
        27: from /home/daniel/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
        26: from /home/daniel/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
        25: from /home/daniel/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
        24: from /home/daniel/.gem/ruby/2.7.0/bin/jekyll:23:in `<top (required)>'
        23: from /home/daniel/.gem/ruby/2.7.0/bin/jekyll:23:in `load'
        22: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/exe/jekyll:15:in `<top (required)>'
        21: from /home/daniel/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        20: from /home/daniel/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        19: from /home/daniel/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        18: from /home/daniel/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        17: from /home/daniel/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        16: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/doctor.rb:17:in `block (2 levels) in init_with_program'
        15: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/doctor.rb:26:in `process'
        14: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:173:in `generate'
        13: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:173:in `each'
        12: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:175:in `block in generate'
        11: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-sitemap-1.4.0/lib/jekyll/jekyll-sitemap.rb:13:in `generate'
        10: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-sitemap-1.4.0/lib/jekyll/jekyll-sitemap.rb:65:in `file_exists?'
         9: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-sitemap-1.4.0/lib/jekyll/jekyll-sitemap.rb:65:in `any?'
         8: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-sitemap-1.4.0/lib/jekyll/jekyll-sitemap.rb:65:in `block in file_exists?'
         7: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/page.rb:101:in `url'
         6: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/page.rb:87:in `template'
         5: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/page.rb:171:in `html?'
         4: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/convertible.rb:89:in `output_ext'
         3: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/renderer.rb:45:in `output_ext'
         2: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/renderer.rb:250:in `permalink_ext'
         1: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-multiple-languages-plugin-1.7.0/lib/jekyll-multiple-languages-plugin.rb:248:in `permalink'
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-multiple-languages-plugin-1.7.0/lib/jekyll-multiple-languages-plugin.rb:248:in `+': no implicit conversion of nil into String (TypeError)
```

## Code Sample
 O [pdf sobre a fala][fala-pdf] sendo
[fala-pdf]:/fala/

show, after `jekyll build` not as a anchor link, but exactly as `O [pdf sobre a fala][fala-pdf] sendo`

**Comment by ashmaroli** [comment]
Based on your report, the error is from a plugin you're using: `jekyll-multiple-languages-plugin`
```
1: from /home/daniel/.gem/ruby/2.7.0/gems/jekyll-multiple-languages-plugin-1.7.0/lib/jekyll-multiple-languages-plugin.rb:248:in `permalink'
/home/daniel/.gem/ruby/2.7.0/gems/jekyll-multiple-languages-plugin-1.7.0/lib/jekyll-multiple-languages-plugin.rb:248:in `+':
no implicit conversion of nil into String (TypeError)
```
And regarding the anchor tag not rendering, it could be your Markdown text itself. You need to separate the link definitions by a newline.
The following is not correct:
```
O [pdf sobre a fala][fala-pdf] sendo
[fala-pdf]:/fala/
```
The following is correct:
```
O [pdf sobre a fala][fala-pdf] sendo

[fala-pdf]:/fala/
```

**Comment by alexandre1985** [comment]
Thank you.

My link definition is already separeted by a new line.
