### ISSUE TITLE
When run jekyll serve throw error: start_with NoMethodError

### ISSUE THREAD

**Issue by GrayYoung** [jekyll/jekyll#8307]
## My Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Windows 10 |
| `jekyll`         | 4.1.1     |
| `ruby`   | 2.7.1     |
| `gem`   | 3.1.2     |

---

## Current Behavior
Run `jekyll serve` and throw the error:

```
PS D:\Development\Marching> jekyll serve --trace
Configuration file: D:/Development/Marching/_config.yml
            Source: D:/Development/Marching
       Destination: D:/Development/Marching/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
                    done in 3.743 seconds.
Traceback (most recent call last):
        21: from C:/Ruby27-x64/bin/jekyll:23:in `<main>'
        20: from C:/Ruby27-x64/bin/jekyll:23:in `load'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:43:in `process'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:88:in `watch'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-watch-2.2.1/lib/jekyll/watcher.rb:25:in `watch'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-watch-2.2.1/lib/jekyll/watcher.rb:48:in `build_listener'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-watch-2.2.1/lib/jekyll/watcher.rb:102:in `listen_ignore_paths'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-watch-2.2.1/lib/jekyll/watcher.rb:91:in `to_exclude'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-watch-2.2.1/lib/jekyll/watcher.rb:78:in `custom_excludes'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-watch-2.2.1/lib/jekyll/watcher.rb:78:in `map'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-watch-2.2.1/lib/jekyll/watcher.rb:78:in `block in custom_excludes'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll.rb:178:in `sanitized_path': undefined method `start_with?' for #<Array:0x000000000751afc0> (NoMethodError)
PS D:\Development\Marching>
```

**Comment by ashmaroli** [comment]
Please rerun the command with `--trace` and update your post above with the stack trace.

**Comment by GrayYoung** [comment]
> 
> 
> Please rerun the command with `--trace` and update your post above with the stack trace.

Hi, I updated the post.

**Comment by ashmaroli** [comment]
@GrayYoung The error is in your config file.
The `exclude` setting should be a list of strings.
