### ISSUE TITLE
Standard Windows installation instructions fail

### ISSUE THREAD

**Issue by axelfontaine** [jekyll/jekyll#8885]
## My Environment

Fresh installation following the exact instructions on https://jekyllrb.com/docs/installation/windows/

Note that it is not clear which choices should be made (1,2,3) when running `ridk install`. I also assumed it was safe the let the RubyInstaller wizard launch that as a last step when it offered it.

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Win 10 x64 21H1 |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

## Expected Behaviour

Jekyll works as expected on my Windows machine

## Current Behavior

```
> jekyll serve
Configuration file: C:/Workspaces/aaa.com/_config.yml
            Source: C:/Workspaces/aaa.com
       Destination: C:/Workspaces/aaa.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 1.654 seconds.
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
 Auto-regeneration: enabled for 'C:/Workspaces/aaa.com'
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
<internal:C:/Programs/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick (LoadError)
        from <internal:C:/Programs/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `require_relative'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `setup'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:100:in `process'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Programs/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
        from C:/Programs/Ruby30-x64/bin/jekyll:23:in `load'
        from C:/Programs/Ruby30-x64/bin/jekyll:23:in `<main>'
```

The default instructions are clearly missing something along the lines of `gem install webrick`.

**Comment by ashmaroli** [comment]
Its mentioned under https://jekyllrb.com/docs/#instructions since its applicable to all platforms

**Comment by axelfontaine** [comment]
I may be blind, but I don't see it. On a fresh Ruby install, running

```
C:\Users\Axel>gem install jekyll bundler
Fetching unicode-display_width-1.8.0.gem
Fetching terminal-table-2.0.0.gem
Fetching safe_yaml-1.0.5.gem
Fetching rouge-3.26.1.gem
Fetching forwardable-extended-2.6.0.gem
Fetching pathutil-0.16.2.gem
Fetching mercenary-0.4.0.gem
Fetching liquid-4.0.3.gem
Fetching kramdown-2.3.1.gem
Fetching kramdown-parser-gfm-1.1.0.gem
Fetching ffi-1.15.4-x64-mingw32.gem
Fetching rb-inotify-0.10.1.gem
Fetching rb-fsevent-0.11.0.gem
Fetching listen-3.7.0.gem
Fetching jekyll-watch-2.2.1.gem
Fetching sassc-2.4.0-x64-mingw32.gem
Fetching jekyll-sass-converter-2.1.0.gem
Fetching concurrent-ruby-1.1.9.gem
Fetching i18n-1.8.11.gem
Fetching http_parser.rb-0.8.0.gem
Fetching eventmachine-1.2.7-x64-mingw32.gem
Fetching em-websocket-0.5.3.gem
Fetching colorator-1.1.0.gem
Fetching public_suffix-4.0.6.gem
Fetching jekyll-4.2.1.gem
Fetching addressable-2.8.0.gem
Successfully installed unicode-display_width-1.8.0
Successfully installed terminal-table-2.0.0
Successfully installed safe_yaml-1.0.5
Successfully installed rouge-3.26.1
Successfully installed forwardable-extended-2.6.0
Successfully installed pathutil-0.16.2
Successfully installed mercenary-0.4.0
Successfully installed liquid-4.0.3
Successfully installed kramdown-2.3.1
Successfully installed kramdown-parser-gfm-1.1.0
Successfully installed ffi-1.15.4-x64-mingw32
Successfully installed rb-inotify-0.10.1
Successfully installed rb-fsevent-0.11.0
Successfully installed listen-3.7.0
Successfully installed jekyll-watch-2.2.1
Successfully installed sassc-2.4.0-x64-mingw32
Successfully installed jekyll-sass-converter-2.1.0
Successfully installed concurrent-ruby-1.1.9
Successfully installed i18n-1.8.11
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed http_parser.rb-0.8.0
Successfully installed eventmachine-1.2.7-x64-mingw32
Successfully installed em-websocket-0.5.3
Successfully installed colorator-1.1.0
Successfully installed public_suffix-4.0.6
Successfully installed addressable-2.8.0
Successfully installed jekyll-4.2.1
Parsing documentation for unicode-display_width-1.8.0
Installing ri documentation for unicode-display_width-1.8.0
Parsing documentation for terminal-table-2.0.0
Installing ri documentation for terminal-table-2.0.0
Parsing documentation for safe_yaml-1.0.5
Installing ri documentation for safe_yaml-1.0.5
Parsing documentation for rouge-3.26.1
Installing ri documentation for rouge-3.26.1
Parsing documentation for forwardable-extended-2.6.0
Installing ri documentation for forwardable-extended-2.6.0
Parsing documentation for pathutil-0.16.2
Installing ri documentation for pathutil-0.16.2
Parsing documentation for mercenary-0.4.0
Installing ri documentation for mercenary-0.4.0
Parsing documentation for liquid-4.0.3
Installing ri documentation for liquid-4.0.3
Parsing documentation for kramdown-2.3.1
Installing ri documentation for kramdown-2.3.1
Parsing documentation for kramdown-parser-gfm-1.1.0
Installing ri documentation for kramdown-parser-gfm-1.1.0
Parsing documentation for ffi-1.15.4-x64-mingw32
Installing ri documentation for ffi-1.15.4-x64-mingw32
Parsing documentation for rb-inotify-0.10.1
Installing ri documentation for rb-inotify-0.10.1
Parsing documentation for rb-fsevent-0.11.0
Installing ri documentation for rb-fsevent-0.11.0
Parsing documentation for listen-3.7.0
Installing ri documentation for listen-3.7.0
Parsing documentation for jekyll-watch-2.2.1
Installing ri documentation for jekyll-watch-2.2.1
Parsing documentation for sassc-2.4.0-x64-mingw32
Installing ri documentation for sassc-2.4.0-x64-mingw32
Parsing documentation for jekyll-sass-converter-2.1.0
Installing ri documentation for jekyll-sass-converter-2.1.0
Parsing documentation for concurrent-ruby-1.1.9
Installing ri documentation for concurrent-ruby-1.1.9
Parsing documentation for i18n-1.8.11
Installing ri documentation for i18n-1.8.11
Parsing documentation for http_parser.rb-0.8.0
unknown encoding name "chunked\r\n\r\n25" for ext/ruby_http_parser/vendor/http-parser-java/tools/parse_tests.rb, skipping
Installing ri documentation for http_parser.rb-0.8.0
Parsing documentation for eventmachine-1.2.7-x64-mingw32
Installing ri documentation for eventmachine-1.2.7-x64-mingw32
Parsing documentation for em-websocket-0.5.3
Installing ri documentation for em-websocket-0.5.3
Parsing documentation for colorator-1.1.0
Installing ri documentation for colorator-1.1.0
Parsing documentation for public_suffix-4.0.6
Installing ri documentation for public_suffix-4.0.6
Parsing documentation for addressable-2.8.0
Installing ri documentation for addressable-2.8.0
Parsing documentation for jekyll-4.2.1
Installing ri documentation for jekyll-4.2.1
Done installing documentation for unicode-display_width, terminal-table, safe_yaml, rouge, forwardable-extended, pathutil, mercenary, liquid, kramdown, kramdown-parser-gfm, ffi, rb-inotify, rb-fsevent, listen, jekyll-watch, sassc, jekyll-sass-converter, concurrent-ruby, i18n, http_parser.rb, eventmachine, em-websocket, colorator, public_suffix, addressable, jekyll after 17 seconds
Fetching bundler-2.2.31.gem
Successfully installed bundler-2.2.31
Parsing documentation for bundler-2.2.31
Installing ri documentation for bundler-2.2.31
Done installing documentation for bundler after 3 seconds
27 gems installed
```

absolutely did *not* install `webrick` on my machine.

Also note my other comment:

> Note that it is not clear which choices should be made (1,2,3) when running ridk install. I also assumed it was safe the let the RubyInstaller wizard launch that as a last step when it offered it.

**Comment by axelfontaine** [comment]
OK, nevermind. Just saw the note in red applicable to point 5. 
You might want to 
- at least move that up from point 6 to point 5 where it applies
- or better yet, fix the standard instructions to work with the latest Ruby versions
- or mandate that Ruby 2.7.x be used

Either way the status quo is confusing and some quick improvements can fix that.

**Comment by ashmaroli** [comment]
> * move that up from point 6 to point 5 where it applies

The *red* note isn't part of the *numbered list*. Hence a general heads-up at the end of the list.


> * fix the standard instructions to work with the latest Ruby versions

In the *Prerequisites* section, we do say Jekyll requires **Ruby 2.5.0 or higher**
And in a later note, we also mention the need to include `webrick` gem for Ruby 3.0 onwards.
From the next minor release onward, (i.e. `>= jekyll-4.3`) `webrick` will be marked as a dependency with all supported Ruby versions.

> * or mandate that Ruby 2.7.x be used

Technically, there is no hard basis to make such a mandate. Therefore, we won't enforce a single Ruby version.

**Comment by axelfontaine** [comment]
The fact remains that I find the current setup instructions too difficult. That's maybe just me, the mountain of forum posts across the internet by other Windows users probably suggests otherwise.

My background is JVM and not Ruby, so no doubt one may feel different coming from the native ecosystem.

In the past I was faced with similar issues when I expanded https://github.com/flyway/flyway beyond a pure JVM scope by adding a CLI and non-JVM users found it difficult to see how exactly they should set up their JVM correctly. The solution I ended going for was packaging a private copy of the JVM with the CLI. The compatibility problems were gone. Users could get started with the tool they came for without needing to fight with underlying technology. Have you considered doing the same?

I feel like creating a Jekyll distribution that contains its own private Ruby runtime with all necessary gems in the exact right versions you have tested, would alleviate a lot of pains like this one. Disk space is cheap anyway. What do you think?

**Comment by ashmaroli** [comment]
> I feel like creating a Jekyll distribution that contains its own private Ruby runtime with all necessary gems in the exact right versions you have tested,

There was a plan to do something *similar* with [jekyll-docker](https://github.com/envygeeks/jekyll-docker). But it was never made official and has remained third-party project.
