### ISSUE TITLE
[Docs]: can't run site locally with plugin without changing Gemfile

### ISSUE THREAD

**Issue by EmilySeville7cfg** [jekyll/jekyll#8917]
### Operating System

Linux Mint 20.2 Cinnamon

### Ruby Version

ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

### Jekyll Version

jekyll 4.2.1

### Expected Behavior

No startup site preview error when plugin names are not mentioned in Gemfile explicitly.

### Current Behavior

It is [written](https://jekyllrb.com/docs/plugins/installation/) that we can just (second option):
- add plugin under `plugins:` key in `_config.yml`
- install mention plugin via `gem install`

But `bundle exec jekyll serve` fails until smth like this is not added to Gemfile:

```ruby
["jekyll-default-layout",
  "jekyll-gist",
  "jekyll-github-metadata",
  "jekyll-optional-front-matter",
  "jekyll-paginate",
  "jekyll-readme-index",
  "jekyll-titles-from-headings",
  "jekyll-relative-links"].each do |plugin|
  gem plugin
end
```

### Relevant log output

```shell
Configuration file: /home/emilyseville7cfg/Documents/mine/jekyll/console-utils/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-default-layout or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the jekyll-default-layout gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- jekyll-default-layout' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
Traceback (most recent call last):
        36: from /home/emilyseville7cfg/gems/bin/bundle:23:in `<main>'
        35: from /home/emilyseville7cfg/gems/bin/bundle:23:in `load'
        34: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/exe/bundle:36:in `<top (required)>'
        33: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        32: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/exe/bundle:48:in `block in <top (required)>'
        31: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli.rb:25:in `start'
        30: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        29: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli.rb:31:in `dispatch'
        28: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        27: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        26: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        25: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli.rb:484:in `exec'
        24: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:23:in `run'
        23: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
        22: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `load'
        21: from /home/emilyseville7cfg/gems/bin/jekyll:23:in `<top (required)>'
        20: from /home/emilyseville7cfg/gems/bin/jekyll:23:in `load'
        19: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
        18: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        17: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        16: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        15: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        14: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        13: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        12: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        11: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
        10: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
         9: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `process'
         8: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `new'
         7: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/site.rb:36:in `initialize'
         6: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/site.rb:131:in `setup'
         5: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/plugin_manager.rb:22:in `conscientious_require'
         4: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/plugin_manager.rb:30:in `require_gems'
         3: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:57:in `require_with_graceful_fail'
         2: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:57:in `each'
         1: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:60:in `block in require_with_graceful_fail'
/home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:60:in `require': cannot load such file -- jekyll-default-layout (LoadError)
        36: from /home/emilyseville7cfg/gems/bin/bundle:23:in `<main>'
        35: from /home/emilyseville7cfg/gems/bin/bundle:23:in `load'
        34: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/exe/bundle:36:in `<top (required)>'
        33: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        32: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/exe/bundle:48:in `block in <top (required)>'
        31: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli.rb:25:in `start'
        30: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        29: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli.rb:31:in `dispatch'
        28: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        27: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        26: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        25: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli.rb:484:in `exec'
        24: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:23:in `run'
        23: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
        22: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `load'
        21: from /home/emilyseville7cfg/gems/bin/jekyll:23:in `<top (required)>'
        20: from /home/emilyseville7cfg/gems/bin/jekyll:23:in `load'
        19: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
        18: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        17: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        16: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        15: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        14: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        13: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        12: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        11: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
        10: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
         9: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `process'
         8: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `new'
         7: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/site.rb:36:in `initialize'
         6: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/site.rb:131:in `setup'
         5: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/plugin_manager.rb:22:in `conscientious_require'
         4: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/plugin_manager.rb:30:in `require_gems'
         3: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:57:in `require_with_graceful_fail'
         2: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:57:in `each'
         1: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:58:in `block in require_with_graceful_fail'
/home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:73:in `rescue in block in require_with_graceful_fail': jekyll-default-layout (Jekyll::Errors::MissingDependencyException)
```
```


### Code Sample

Default Jekyll template is used. Only several plugins installed listed above.

**Comment by ashmaroli** [comment]
Technically, this would be a bug in Bundler instead of Jekyll.
Bundler is the program that evaluates Gemfiles not Jekyll.

**Comment by EmilySeville7cfg** [comment]
Please answer in [this](https://github.com/rubygems/rubygems/issues/5239#issuecomment-1002593605) issue.

**Comment by ashmaroli** [comment]
@EmilySeville7cfg I apologize for redirecting you to the Bundler repository.
I had misunderstood your report.

The behavior you have reported is expected because Bundler narrows the scope of installed gems to the runtime dependencies resolved from having the (given) Gemfile resolved.

Perhaps the documentation needs to be more explicit on that aspect.

**Comment by EmilySeville7cfg** [comment]
That's would be nice to describe the plugin setup instructions more accurate. ;)
