### ISSUE TITLE
[Bug]: undefined method `to_sym' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by osfanbuff63** [jekyll/jekyll#9074]
### Operating System

Windows 10

### Ruby Version

ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]

### Jekyll Version

jekyll 4.2.2

### Expected Behavior

I expected my site to run correctly when I ran:
```shell
bundle exec jekyll serve
```

### Current Behavior

When I run `bundle exec jekyll serve`, it will fail with the error `undefined method `to_sym' for nil:NilClass (NoMethodError)`. 

Plugins:
```yml
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jemoji
```

### Relevant log output

```shell
C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/frontmatter_defaults.rb:160:in `applies_type?': undefined method `to_sym' for nil:NilClass (NoMethodError)

      !scope.key?("type") || type&.to_sym.eql?(scope["type"].to_sym)
                                                            ^^^^^^^
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/frontmatter_defaults.rb:102:in `applies?'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/frontmatter_defaults.rb:203:in `block in matching_sets'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/frontmatter_defaults.rb:202:in `select'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/frontmatter_defaults.rb:202:in `matching_sets'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/frontmatter_defaults.rb:63:in `find'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/page.rb:55:in `block in initialize'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/page.rb:75:in `permalink'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:240:in `permalink_ext'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:46:in `output_ext'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/convertible.rb:89:in `output_ext'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/page.rb:172:in `html?'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/page.rb:82:in `template'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/page.rb:96:in `url'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-sitemap-1.4.0/lib/jekyll/jekyll-sitemap.rb:65:in `block in file_exists?'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-sitemap-1.4.0/lib/jekyll/jekyll-sitemap.rb:65:in `any?'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-sitemap-1.4.0/lib/jekyll/jekyll-sitemap.rb:65:in `file_exists?'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-sitemap-1.4.0/lib/jekyll/jekyll-sitemap.rb:13:in `generate'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:193:in `block in generate'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:191:in `each'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:191:in `generate'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:79:in `process'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:28:in `process_site'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/bin/jekyll:25:in `load'
        from C:/Users/matty/Desktop/Wii-Guide/vendor/bundle/ruby/3.1.0/bin/jekyll:25:in `<main>'
```

### Steps to reproduce

1. Clone my repo [here](https://github.com/osfanbuff63/Wii-Guide/)
2. Checkout the `refactor-jekyll` branch
3. Run `bundle install` to install dependencies
4. Run `bundle exec jekyll serve`

**Comment by osfanbuff63** [comment]
Turns out this was a config issue
