### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PingalPie** [jekyll/jekyll#9078]
### Operating System

Arch linux 

### Ruby Version

ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]

### Jekyll Version

jekyll 4.2.2

### Expected Behavior

I expected that it will run a webserver
This is my first time using jekyll
```
jekyll serve
```

### Current Behavior

I got this error
```
                    ------------------------------------------------
      Jekyll 4.2.2   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick (LoadError)
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `require_relative'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `setup'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:100:in `process'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /home/yash/.local/share/gem/ruby/3.0.0/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
        from /home/yash/.local/share/gem/ruby/3.0.0/bin/jekyll:25:in `load'
        from /home/yash/.local/share/gem/ruby/3.0.0/bin/jekyll:25:in `<main>'
```

### Steps to reproduce issue

- clone this [repo](https://github.com/Bugswriter/website-1)
- go into repo
- do ```jekyll serve```

**Comment by PingalPie** [comment]
No need for me now because I am going to learn Jekyll and make my own website and launch it. Solve it for someone else
