### ISSUE TITLE
[Bug]: `jekyll serve` halts with an error `cannot load such file -- webrick` in jekyll/jekyll:4 image

### ISSUE THREAD

**Issue by hotoku** [jekyll/jekyll#9110]
### Operating System

Docker on Mac (intel chip)

### Ruby Version

ruby 3.1.1p18

### Jekyll Version

jekyll 4.2.2

### Expected Behavior

I expected the server launches by the following command.

```
docker run --rm --volume=$(pwd):/srv/jekyll -p 4000:4000 --name jekyll jekyll/jekyll:4 jekyll serve --drafts --livereload
```

### Current Behavior

The process halts displaying the following error message.

```
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
[33mConfiguration file: none[0m
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.04 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
[31m                    ------------------------------------------------[0m
[31m      Jekyll 4.2.2   Please append `--trace` to the `serve` command [0m
[31m                     for any additional information or backtrace. [0m
[31m                    ------------------------------------------------[0m
<internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick (LoadError)
	from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `require_relative'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `setup'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:100:in `process'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /usr/gem/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
	from /usr/gem/bin/jekyll:25:in `load'
	from /usr/gem/bin/jekyll:25:in `<main>'
```

**Comment by mohits** [comment]
Hi! For reference, Ruby 3.0 does not ship with webrick. That is the reason for the problem you are experiencing. See here: https://github.com/github/pages-gem/issues/752.

**Comment by hotoku** [comment]
Thank you for the answer and reference. I understand.

**Comment by hotoku** [comment]
I found source of docker image is managed in anther repository and the same issue is registered. [link](https://github.com/envygeeks/jekyll-docker/issues/340) So I close this issue.
