### ISSUE TITLE
[Docs]: Installation not working on Ubuntu 22.04 LTS with Ruby 3 and no Ruby 2.7 Ubuntu packages for GitHub pages

### ISSUE THREAD

**Issue by thediveo** [jekyll/jekyll#9115]
I don't know if this is a documentation issue or not, but following the installation instructions it is not possible to run `bundle exec jekyll serve` as described, on a GitHub pages documentation. It fails with an error about not being able to convert a hash into an int.

As Ubuntu 22.04LTS doesn't have any Ruby 2.7 packages anymore, jekyll has become unusable on this recent LTS distribution.

Please document a way to get this working.

**Comment by yboulkaid** [comment]
I have tried the setup from the [ubuntu instructions](https://jekyllrb.com/docs/installation/ubuntu/) on a fresh 22.04 on EC2 and all the steps ran successfully until the point where I wanted to start the server (`bundle exec jekyll serve`).

This failed because of a missing webrick:
```
/home/ubuntu/gems/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
        from /home/ubuntu/gems/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
```

This is a known problem and will be fixed by the next release. 

However, I couldn't reproduce the error with not being able to convert a hash into an int, could you provide the full error message and stacktrace?

**Comment by thediveo** [comment]
I'm using the Gomega Github pages jekyll documentation, https://github.com/onsi/gomega and then the docs/ subdirectory in this repository. Even after all gems and starting all over again, the error persists:

```
bundle exec jekyll serve
Configuration file: /home/xxx/github/gomega/docs/_config.yml
   GitHub Metadata: site.name is set in _config.yml, but many plugins and themes expect site.title to be used instead. To avoid potential inconsistency, Jekyll GitHub Metadata will not set site.title to the repository's name.
            Source: /home/xxx/github/gomega/docs
       Destination: /home/xxx/github/gomega/docs/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
                    done in 2.198 seconds.
jekyll 3.9.0 | Error:  no implicit conversion of Hash into Integer
/home/xxx/gems/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read': no implicit conversion of Hash into Integer (TypeError)
        from /home/xxx/gems/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read'
        from /home/xxx/gems/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:75:in `proc_version'
        from /home/xxx/gems/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:40:in `bash_on_windows?'
        from /home/xxx/gems/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:77:in `watch'
        from /home/xxx/gems/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:43:in `process'
        from /home/xxx/gems/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
        from /home/xxx/gems/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
        from /home/xxx/gems/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
        from /home/xxx/gems/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from /home/xxx/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /home/xxx/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /home/xxx/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /home/xxx/gems/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /home/xx/xgems/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /home/xxx/gems/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
        from /home/xxx/gems/bin/jekyll:25:in `load'
        from /home/xxx/gems/bin/jekyll:25:in `<main>```

**Comment by thediveo** [comment]
@yboulkaid thank you so much! Will test to be sure and then PR to onsi so that we have this of the lawn in the future.
