### ISSUE TITLE
[Bug]: No such file or directory @ rb_sysopen - /path/to/file/that/exists (Errno::ENOENT)

### ISSUE THREAD

**Issue by yagarea** [jekyll/jekyll#9120]
### Operating System

Arch Linux  5.18.16-arch1-1 

### Ruby Version

ruby 3.0.4p208 

### Jekyll Version

jekyll 4.2.2

### Expected Behavior

Not crash and generate static path to file.

### Current Behavior

Crash

### Relevant log output

```shell
john@arch-thinkpad ~/O/k/hrarem (master)> bundle exec jekyll serve --trace -d test/
Configuration file: /home/john/Organisations/ksp/hrarem/_config.yml
             LaTeX: no macros loaded
            Source: /home/john/Organisations/ksp/hrarem
       Destination: /home/john/Organisations/ksp/hrarem/test
 Incremental build: disabled. Enable with --incremental
      Generating...
bundler: failed to load command: jekyll (/home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/bin/jekyll)
/home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/utils.rb:141:in `initialize': No such file or directory @ rb_sysopen - /home/john/Organisations/ksp/hrarem/games/informaticka-soutez/2022j/soutez/26-Z3-2.mp (Errno::ENOENT)
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/utils.rb:141:in `open'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/utils.rb:141:in `has_yaml_header?'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:52:in `block in read_directories'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:48:in `each'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:48:in `read_directories'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:89:in `block in retrieve_dirs'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:86:in `each'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:86:in `retrieve_dirs'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:60:in `read_directories'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:89:in `block in retrieve_dirs'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:86:in `each'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:86:in `retrieve_dirs'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:60:in `read_directories'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:89:in `block in retrieve_dirs'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:86:in `each'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:86:in `retrieve_dirs'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:60:in `read_directories'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:89:in `block in retrieve_dirs'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:86:in `each'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:86:in `retrieve_dirs'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:60:in `read_directories'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/reader.rb:16:in `read'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:181:in `read'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:78:in `process'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:28:in `process_site'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:65:in `build'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:36:in `process'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/bin/jekyll:25:in `load'
	from /home/john/Organisations/ksp/hrarem/vendor/bundle/ruby/3.0.0/bin/jekyll:25:in `<top (required)>'
	from /home/john/.local/share/gem/ruby/3.0.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `load'
	from /home/john/.local/share/gem/ruby/3.0.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/john/.local/share/gem/ruby/3.0.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:23:in `run'
	from /home/john/.local/share/gem/ruby/3.0.0/gems/bundler-2.3.12/lib/bundler/cli.rb:483:in `exec'
	from /home/john/.local/share/gem/ruby/3.0.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/john/.local/share/gem/ruby/3.0.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/john/.local/share/gem/ruby/3.0.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/john/.local/share/gem/ruby/3.0.0/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in `dispatch'
	from /home/john/.local/share/gem/ruby/3.0.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/john/.local/share/gem/ruby/3.0.0/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in `start'
	from /home/john/.local/share/gem/ruby/3.0.0/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
	from /home/john/.local/share/gem/ruby/3.0.0/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /home/john/.local/share/gem/ruby/3.0.0/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
	from /home/john/.local/share/gem/ruby/3.0.0/bin/bundle:25:in `load'
	from /home/john/.local/share/gem/ruby/3.0.0/bin/bundle:25:in `<main>'
```
```


### Code Sample

_No response_

**Comment by yagarea** [comment]
File was invalid symlink
