### ISSUE TITLE
[Bug]: Can't serve and build pages with ruby 3.2

### ISSUE THREAD

**Issue by invalidusrname** [jekyll/jekyll#9231]
### Operating System

Mac OS 13.1

### Ruby Version

ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin22]

### Jekyll Version

jekyll 4.3.1

### Expected Behavior

I'm having a little bit of trouble serving my site running on Ruby 3.2

```
bundle exec jekyll serve --trace
```

It looks like this is a problem with liquid. It appears to be fixed in https://github.com/Shopify/liquid/issues/1625 and released in v5. It's also a good idea to keep gem dependencies on this project up to date. Can we look into getting jekyll updated to this version of liquid so this works with the latest version of ruby?

### Current Behavior

```
bundle exec jekyll serve

Configuration file: /Users/matt/dev/play/charlotte-ruby.github.io/_config.yml
            Source: /Users/matt/dev/play/charlotte-ruby.github.io
       Destination: /Users/matt/dev/play/charlotte-ruby.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Liquid Exception: undefined method `tainted?' for nil:NilClass in /Users/matt/dev/play/charlotte-ruby.github.io/_layouts/post.html
                    ------------------------------------------------
      Jekyll 4.3.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
/Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:124:in `taint_check': undefined method `tainted?' for nil:NilClass (NoMethodError)

      return unless obj.tainted?
                       ^^^^^^^^^
```

### Relevant log output

```shell
bundle exec jekyll serve --trace
Configuration file: /Users/matt/dev/play/charlotte-ruby.github.io/_config.yml
            Source: /Users/matt/dev/play/charlotte-ruby.github.io
       Destination: /Users/matt/dev/play/charlotte-ruby.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Liquid Exception: undefined method `tainted?' for nil:NilClass in /Users/matt/dev/play/charlotte-ruby.github.io/_layouts/post.html
bundler: failed to load command: jekyll (/Users/matt/.asdf/installs/ruby/3.2.0/bin/jekyll)
/Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:124:in `taint_check': undefined method `tainted?' for nil:NilClass (NoMethodError)

      return unless obj.tainted?
                       ^^^^^^^^^
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:89:in `render'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/tags/assign.rb:26:in `render'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:129:in `render_liquid'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:192:in `render_layout'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:161:in `place_in_layouts'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:93:in `render_document'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:63:in `run'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:578:in `render_regenerated'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:563:in `block (2 levels) in render_docs'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:562:in `each'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:562:in `block in render_docs'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:561:in `each_value'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:561:in `render_docs'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:210:in `render'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:80:in `process'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:28:in `process_site'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:65:in `build'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:36:in `process'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/exe/jekyll:15:in `<top (required)>'
	from /Users/matt/.asdf/installs/ruby/3.2.0/bin/jekyll:25:in `load'
	from /Users/matt/.asdf/installs/ruby/3.2.0/bin/jekyll:25:in `<top (required)>'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli.rb:491:in `exec'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.1/libexec/bundle:45:in `block in <top (required)>'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.1/libexec/bundle:33:in `<top (required)>'
	from /Users/matt/.asdf/installs/ruby/3.2.0/bin/bundle:25:in `load'
	from /Users/matt/.asdf/installs/ruby/3.2.0/bin/bundle:25:in `<main>'
```

**Comment by UlyssesZh** [comment]
This is because the latest Jekyll version (4.3.1) still depends on Liquid 4.0.3, which had not merged Shopify/liquid#1268. Jekyll should have bumped the dependency on Liquid to ~> 5.

**Comment by UlyssesZh** [comment]
Before they update Jekyll, a workaround is to modify the codes in `/Users/matt/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/` to remove the taint check (although it is not good practice to modify libraries).

**Comment by haircutfish** [comment]
Is there a fix to this yet or are we just waiting for an update to drop as I didn't know about it uploaded to my blog and now my blog is town because it won't fix a problem

**Comment by teanijarv** [comment]
Following this thread as I have the same issue. Are there any official announcements when the next jekyll version with this specific fix is released or would it be reasonable to roll back to Ruby 3.1?

**Comment by TheStranjer** [comment]
![image](https://user-images.githubusercontent.com/791672/210021647-c6fb8810-c81c-47c5-99d5-4038f3b8b89e.png)

**Comment by invalidusrname** [comment]
I noticed there was a couple of PRs open that attempt to solve this problem:

https://github.com/jekyll/jekyll/pull/8662
https://github.com/jekyll/jekyll/pull/9036
https://github.com/jekyll/jekyll/pull/9030
https://github.com/jekyll/jekyll/pull/9229

Perhaps we can combine forces here?

**Comment by ashmaroli** [comment]
Theoretically, the fix to this is actually trivial: *Add the removed methods (the ones Jekyll would need) back into Ruby Core*. But monkey-patching core Ruby classes isn't a good idea. It will only be acceptable if there is no other option.

**Comment by invalidusrname** [comment]
> EDIT: _WAS_ a bug in Liquid. It was removed 23 July 2020:
> 
> [Shopify/liquid@065ccbc](https://github.com/Shopify/liquid/commit/065ccbc4aa5b4955dae9743509907bd9ad0db0b9)

This is more Liquid doing their part to keep the library up to date. When ruby 3.2 was released, it removed many deprecated methods.

**Comment by 0xdf223** [comment]
Same here. Mine was showing up in failures in liquid-c. When I removed that from my Gemfile, I started getting the tainted error. 

Updating my `.gitlab-ci.yml` file just like @criadoperez fixed it for me (`image: ruby:3.1.3`), and I could even add `liquid-c` back in. I assume monitoring this thread will alert me to when this is fixed.

**Comment by ashmaroli** [comment]
To Everyone intending to use Jekyll on Ruby 3.2, we have decided to patch the issue at our end with #9248. 
Please point your Gemfile to the pull request and let us know if your build still fails:

```ruby
# in your Gemfile
gem "jekyll", github: "jekyll/jekyll", ref: "refs/pull/9248/head"
```

**Comment by tiesebarrell** [comment]
> To Everyone intending to use Jekyll on Ruby 3.2, we have decided to patch the issue at our end with #9248. Please point your Gemfile to the pull request and let us know if your build still fails:
> 
> ```ruby
> # in your Gemfile
> gem "jekyll", github: "jekyll/jekyll", ref: "refs/pull/9248/head"
> ```

Using the PR version instead fixes the issue in my build with 3.2.0 👍🏻

**Comment by ashmaroli** [comment]
Resolved with release of [Liquid 4.0.4](https://rubygems.org/gems/liquid/versions/4.0.4)

**Comment by invalidusrname** [comment]
Looks like this has been resolved with liquid 4.0.4 release. Since the gemspec brings in `~> 4`, this should get fixed by simply running `bundle`. Thanks guys!

**Comment by marmalamuc** [comment]
> ```ruby
> # in your Gemfile
> gem "jekyll", github: "jekyll/jekyll", ref: "refs/pull/9248/head"
> ```

Works for me! But will I have to remember to update my gemfile when the #9248 patch is released?

I read through the #9248 ticket, and it sounds like a new Liquid version was supposed to fix this, but I encountered this issue today when running `bundle update`.

**Comment by bethan-r** [comment]
> I read through the #9248 ticket, and it sounds like a new Liquid version was supposed to fix this, but I encountered this issue today when running `bundle update`.

Same issue here. Only installed Jekyll, Bundle and Ruby 3.2.0 today.

In the Gemfile.lock file generated with `bundle install`, Liquid version is listed under `jekyll (3.9.2)` as `liquid (~> 4.0)`. Further down the file, it's listed separately as `liquid (4.0.3)`. Very new to Jekyll - is that difference on purpose, so that jekyll uses version 4.0.4 but other gems use version 4.0.3, or is it a version contradiction that might be related to the issue?

Either way, when I edit Gemfile.lock so that both versions match, `liquid (~> 4.0)`, I get the error 'Your lockfile is unreadable' after trying `bundle update`, `bundle install` or `bundle exec jekyll serve`.
