### ISSUE TITLE
[Bug]: Conversion Error During Jekyll Build

### ISSUE THREAD

**Issue by BryanGoble** [jekyll/jekyll#9438]
### Operating System

Windows 11

### Ruby Version

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]

### Jekyll Version

jekyll 4.3.2

### Expected Behavior

I expected my site to be built successfully when I ran:
```
bundle exec jekyll build
```

### Current Behavior

I'm running into an issue when using the latest version of Jekyll. I just started with a fresh install of everything (ruby, jekyll, and all dependencies). As you can see in the error log, I'm receiving some sort of conversion error. However, I scrapped/uninstalled everything then installed jekyll 3.9.3 and had no issues running the build/serving the site. So I then uninstalled everything again just to be sure, but ran into the same issue when using 4.3.2. Lastly, I did all of the steps again to install 3.9.3 then tried updating to 4.3.2 rather than starting clean, but yet again had the same issue.

### Relevant log output

```shell
Configuration file: C:/Users/bryan/OneDrive/Documents/Everywhere Files/Coding Projects/VS Code Projects - Database/Projects/Professional Site (Jekyll)/bryangoble/_config.yml
            Source: C:/Users/bryan/OneDrive/Documents/Everywhere Files/Coding Projects/VS Code Projects - Database/Projects/Professional Site (Jekyll)/bryangoble
       Destination: C:/Users/bryan/OneDrive/Documents/Everywhere Files/Coding Projects/VS Code Projects - Database/Projects/Professional Site (Jekyll)/bryangoble/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2023-09-01-welcome-to-jekyll.markdown':
                    No such file or directory @ rb_sysopen - C:/Users/bryan/OneDrive/Documents/Everywhere Files/Coding Projects/VS Code Projects - Database/Projects/Professional Site (Jekyll)/bryangoble/.jekyll-cache/Jekyll/Cache/Jekyll--Converters--Markdown/fd/aa4200cef2544ec568b25970b3a49cf9b4f3d7015485506ccda914caf9c5b9
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/cache.rb:181:in `initialize': No such file or directory @ rb_sysopen - C:/Users/bryan/OneDrive/Documents/Everywhere Files/Coding Projects/VS Code Projects - Database/Projects/Professional Site (Jekyll)/bryangoble/.jekyll-cache/Jekyll/Cache/Jekyll--Converters--Markdown/fd/aa4200cef2544ec568b25970b3a49cf9b4f3d7015485506ccda914caf9c5b9 (Errno::ENOENT)
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/cache.rb:181:in `open'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/cache.rb:181:in `dump'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/cache.rb:97:in `[]='
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/cache.rb:108:in `rescue in getset'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/cache.rb:104:in `getset'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/converters/markdown.rb:85:in `convert'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:105:in `block in convert'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `reduce'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `convert'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:84:in `render_document'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:557:in `block (2 levels) in render_docs'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:556:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:556:in `block in render_docs'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:555:in `each_value'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:555:in `render_docs'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:210:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby32-x64/bin/jekyll:25:in `load'
        from C:/Ruby32-x64/bin/jekyll:25:in `<main>'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/cache.rb:84:in `[]': unhandled exception
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/cache.rb:105:in `getset'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/converters/markdown.rb:85:in `convert'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:105:in `block in convert'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `reduce'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `convert'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:84:in `render_document'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:557:in `block (2 levels) in render_docs'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:556:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:556:in `block in render_docs'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:555:in `each_value'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:555:in `render_docs'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:210:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby32-x64/bin/jekyll:25:in `load'
        from C:/Ruby32-x64/bin/jekyll:25:in `<main>'
```

### Code Sample

I've just done a fresh install of ruby, jekyll, and all dependencies. Then ran:
```
bundle exec jekyll serve
```

**Comment by BryanGoble** [comment]
After some more testing, I found the issue is caused by the inclusion of Jekyll-Feed in Jekyll. I tried disabling the plugin in `_config.yml`, but no change. Only thing that's worked so far was a solution found in #7928 which added the ability to disable disk cache. Either modify the `jekyll serve` command to `jekyll serve --disable-disk-cache` or your `_config.yml` with `disable_disk_cache: true`.

Seeing as how the last release of Jekyll-Feed was 14 October, 2022, I'm not entirely surprised that there are issues now.

This isn't a real fix, but it solves my current issue.

**Comment by jdromero88** [comment]
Hey @BryanGoble I believe this is because your Gemfile.lock. you can delete it and then do
```bash
bundle install
```
and then serve
```bash
bundle exec jekyll serve
```
I was able to run your repo https://github.com/BryanGoble/bryangoble.com without any errors with ruby 3.2.2 and Jekyll 4.3.2.
![image](https://github.com/jekyll/jekyll/assets/51330062/d944b79e-0a32-45d4-af48-f2018b3e7231)

**Comment by JacobSuWang** [comment]
This did not work for me.
Getting the following error: (same after installing jupyter)
```
  Conversion error: JekyllJupyterNotebook::Converter encountered an error while converting 'assets/jupyter/blog.ipynb':
                    No such file or directory - jupyter
                    ------------------------------------------------
      Jekyll 4.3.3   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
```

**Comment by mattr-** [comment]
Closing as the source code for the site in the original post is no longer accessible and there's a potential fix in the comments. Any new problems need to have their own issue filed for them.

**Comment by lvanveen** [comment]
Is there a fix for the second error, though? I also get the missing Jupyter error above when trying to deploy my site on GitHub.
