### ISSUE TITLE
[Bug]: jekyll build fails with Variable was not properly terminated with regexp: /\\}\\}/ (Liquid::SyntaxError)

### ISSUE THREAD

**Issue by bhati-pradeep** [jekyll/jekyll#9487]
### Operating System

Mac Monterey

### Ruby Version

ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-darwin21]

### Jekyll Version

jekyll 4.3.2

### Expected Behavior

 We are using github pages for hosting our Nutanix ansible plugin website. Github action for same should go fine without error.

### Current Behavior

Currently we use lot of yaml files in our ansible plugin for tests. Ansible have a way to use variables using "{{ variable }}". But jekyll build fails with   :

```
Liquid Exception: Liquid syntax error (line 286): Variable '{{ properties | combine ({ item['name'] : item['value'] }' was not properly terminated with regexp: /\}\}/ in tests/integration/targets/ntnx_ndb_databases_sanity/tasks/tests.yml
```

Code snippet its failing for: 
```yaml
- name: create properties map
  set_fact: 
      properties: "{{ properties | combine ({ item['name'] : item['value'] }) }}"
  loop: "{{result.response.properties}}" 
  no_log: true
```
This snippet can be found here : https://github.com/nutanix/nutanix.ansible/blob/b6dc17afede93878515a071d6f3293a71b3002bf/tests/integration/targets/ntnx_ndb_databases_sanity/tasks/tests.yml#L282

Error is at line : https://github.com/nutanix/nutanix.ansible/blob/b6dc17afede93878515a071d6f3293a71b3002bf/tests/integration/targets/ntnx_ndb_databases_sanity/tasks/tests.yml#L286

I even tried skipping the syntax check but its same error.

### Relevant log output

```shell
Liquid Exception: Liquid syntax error (line 286): Variable '{{ properties | combine ({ item['name'] : item['value'] }' was not properly terminated with regexp: /\}\}/ in tests/integration/targets/ntnx_ndb_databases_sanity/tasks/tests.yml
                    ------------------------------------------------
      Jekyll 4.3.2   Please append `--trace` to the `build` command
                     for any additional information or backtrace.
                    ------------------------------------------------
/Users/pradeep.bhati/.gem/ruby/3.1.3/gems/liquid-4.0.4/lib/liquid/block_body.rb:136:in `raise_missing_variable_terminator': Liquid syntax error (line 286): Variable '{{ properties | combine ({ item['name'] : item['value'] }' was not properly terminated with regexp: /\\}\\}/ (Liquid::SyntaxError)
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/liquid-4.0.4/lib/liquid/block_body.rb:128:in `create_variable'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/liquid-4.0.4/lib/liquid/block_body.rb:39:in `parse'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/liquid-4.0.4/lib/liquid/document.rb:10:in `parse'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/liquid-4.0.4/lib/liquid/document.rb:5:in `parse'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/liquid-4.0.4/lib/liquid/template.rb:130:in `parse'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/liquid-4.0.4/lib/liquid/template.rb:114:in `parse'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:124:in `render_liquid'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:80:in `render_document'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:564:in `block in render_pages'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `each'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `render_pages'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:211:in `render'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/bin/jekyll:25:in `load'
	from /Users/pradeep.bhati/.gem/ruby/3.1.3/bin/jekyll:25:in `<main>'
```

### Code Sample

- Clone repo : https://github.com/nutanix/nutanix.ansible
- Run "jekyll build"

**Comment by bhati-pradeep** [comment]
Full logs : https://github.com/nutanix/nutanix.ansible/actions/runs/6815577047/job/18534992225

**Comment by jk2K** [comment]
see https://github.com/jekyll/jekyll/issues/5458#issuecomment-252063824

you should Wrap that whole block with `{% raw %}…{% endraw %}` to let Liquid know not to try to parse it

**Comment by ashmaroli** [comment]
Closing as this is the expected behavior and the solution is to wrap non-Liquid markup with a `raw` Liquid block tag.
