### ISSUE TITLE
[Bug]: jekyll not working after upgrade from Debian 11 to 12 

### ISSUE THREAD

**Issue by improvethings** [jekyll/jekyll#9488]
### Operating System

Debian 12

### Ruby Version

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]

### Jekyll Version

jekyll 4.3.2

### Expected Behavior

I'm trying to run 
$ bundle exec jekyll serve 
# after a successful 
$ bundle update

### Current Behavior

$ bundle exec jekyll serve: 
/var/lib/gems/3.1.0/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read': no implicit conversion of Hash into Integer (TypeError)
	from /var/lib/gems/3.1.0/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read'
	from /var/lib/gems/3.1.0/gems/jekyll-3.8.7/lib/jekyll/utils/platforms.rb:75:in `proc_version'
	from /var/lib/gems/3.1.0/gems/jekyll-3.8.7/lib/jekyll/utils/platforms.rb:40:in `bash_on_windows?'
	from /var/lib/gems/3.1.0/gems/jekyll-3.8.7/lib/jekyll/commands/build.rb:77:in `watch'
	from /var/lib/gems/3.1.0/gems/jekyll-3.8.7/lib/jekyll/commands/build.rb:43:in `process'
	from /var/lib/gems/3.1.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /var/lib/gems/3.1.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `each'
	from /var/lib/gems/3.1.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `start'
	from /var/lib/gems/3.1.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /var/lib/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /var/lib/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /var/lib/gems/3.1.0/gems/jekyll-3.8.7/exe/jekyll:15:in `<top (required)>'
	from /usr/local/bin/jekyll:25:in `load'
	from /usr/local/bin/jekyll:25:in `<main>'

### Relevant log output

```shell
$ jekyll -v
/usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:309:in `check_for_activated_spec!': You have already activated jekyll-sass-converter 3.0.0, but your Gemfile requires jekyll-sass-converter 2.2.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:25:in `block in setup'
	from /usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/spec_set.rb:138:in `each'
	from /usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/spec_set.rb:138:in `each'
	from /usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:24:in `map'
	from /usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:24:in `setup'
	from /usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler.rb:162:in `setup'
	from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bin/jekyll:25:in `load'
	from /usr/local/bin/jekyll:25:in `<main>'
$ cat Gemfile
source "https://rubygems.org"

gem "jekyll", "~> 3.8.6"
gem "minimal-mistakes-jekyll"
gem 'jekyll-redirect-from'
gem 'rexml'

# so I tried adding *gem 'jekyll-sass-converter', '2.2.0'* to Gemfile but then I get: 
$ bundle exec jekyll serve
Bundler could not find compatible versions for gem "jekyll-sass-converter":
  In Gemfile:
    jekyll-sass-converter (= 2.2.0)

    jekyll (~> 3.8.6) was resolved to 3.8.7, which depends on
      jekyll-sass-converter (~> 1.0)

$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.5)
      public_suffix (>= 2.0.2, < 6.0)
    base64 (0.2.0)
    colorator (1.1.0)
    concurrent-ruby (1.2.2)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    eventmachine (1.2.7)
    faraday (2.7.11)
      base64
      faraday-net_http (>= 2.0, < 3.1)
      ruby2_keywords (>= 0.0.4)
    faraday-net_http (3.0.2)
    ffi (1.16.3)
    forwardable-extended (2.6.0)
    http_parser.rb (0.8.0)
    i18n (0.9.5)
      concurrent-ruby (~> 1.0)
    jekyll (3.8.7)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 0.7)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 1.14)
      liquid (~> 4.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (>= 1.7, < 4)
      safe_yaml (~> 1.0)
    jekyll-feed (0.17.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-gist (1.5.0)
      octokit (~> 4.2)
    jekyll-include-cache (0.2.1)
      jekyll (>= 3.7, < 5.0)
    jekyll-paginate (1.1.0)
    jekyll-redirect-from (0.16.0)
      jekyll (>= 3.3, < 5.0)
    jekyll-sass-converter (1.5.2)
      sass (~> 3.4)
    jekyll-sitemap (1.4.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    kramdown (1.17.0)
    liquid (4.0.4)
    listen (3.8.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.3.6)
    minimal-mistakes-jekyll (4.24.0)
      jekyll (>= 3.7, < 5.0)
      jekyll-feed (~> 0.1)
      jekyll-gist (~> 1.5)
      jekyll-include-cache (~> 0.1)
      jekyll-paginate (~> 1.1)
      jekyll-sitemap (~> 1.3)
    octokit (4.25.1)
      faraday (>= 1, < 3)
      sawyer (~> 0.9)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (5.0.3)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.6)
    rouge (3.30.0)
    ruby2_keywords (0.0.5)
    safe_yaml (1.0.5)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sawyer (0.9.2)
      addressable (>= 2.3.5)
      faraday (>= 0.17.3, < 3)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  jekyll (~> 3.8.6)
  jekyll-redirect-from
  minimal-mistakes-jekyll
  rexml

BUNDLED WITH
   2.3.15
```

**Comment by mattr-** [comment]
There are newer versions in the Jekyll 3.x release series. Why have you pinned to 3.8.x?

**Comment by improvethings** [comment]
I'm not sure, I just removed that to _gem 'jekyll'_ in the Gemfile without the version and it seems to work now, thanks for the quick response and simple fix!
