### ISSUE TITLE
Missing data directory causing jekyll to raise exceptions

### ISSUE THREAD

**Issue by lukebewitched** [jekyll/jekyll#9601]
### Operating System

Windows 10 WSL 2

### Ruby Version

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]

### Jekyll Version

jekyll 4.3.3

### Expected Behavior

I expected my chirpy installation which was working previously to output the version of jekyll  when I run ```jekyll -v```.

### Current Behavior

After running the command and other several commands like ```bundle exec jekyll s```, I found out that the error originated from a missing directory in the gems local folder. I was using chirpy to document my code when this happened.

### Relevant log output

```shell
C:\Users\frankdexdevs\Documents\kails\lukebewitched.github.io>bundle exec jekyll s
C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/addressable-2.8.6/lib/addressable/idna/pure.rb:163:in `initialize': No such file or directory @ rb_sysopen - C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/addressable-2.8.6/data/unicode.data (Errno::ENOENT)
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/addressable-2.8.6/lib/addressable/idna/pure.rb:163:in `open'
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/addressable-2.8.6/lib/addressable/idna/pure.rb:163:in `<module:IDNA>'
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/addressable-2.8.6/lib/addressable/idna/pure.rb:21:in `<module:Addressable>'
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/addressable-2.8.6/lib/addressable/idna/pure.rb:20:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/addressable-2.8.6/lib/addressable/idna.rb:25:in `rescue in <top (required)>'
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/addressable-2.8.6/lib/addressable/idna.rb:20:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/addressable-2.8.6/lib/addressable/uri.rb:21:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll.rb:33:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/exe/jekyll:8:in `<top (required)>'
        from C:/Ruby32-x64/bin/jekyll:32:in `load'
        from C:/Ruby32-x64/bin/jekyll:32:in `<main>'
<internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- idn (LoadError)
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/addressable-2.8.6/lib/addressable/idna/native.rb:20:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/addressable-2.8.6/lib/addressable/idna.rb:21:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/addressable-2.8.6/lib/addressable/uri.rb:21:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll.rb:33:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from C:/Users/frankdexdevs/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/exe/jekyll:8:in `<top (required)>'
        from C:/Ruby32-x64/bin/jekyll:32:in `load'
        from C:/Ruby32-x64/bin/jekyll:32:in `<main>'
```

**Comment by lukebewitched** [comment]
<img src="https://media4.giphy.com/media/Sxqxi2sGBBhhc3Qb5s/giphy.gif"/>
After a long research, I realized there's two addressable versions, 2.8.4 and 2.8.6 in the same dir. I checked in to compare the two versions and what I noticed is that v2.8.4 had a data dir that wasn't available in v2.8.6. I copied this folder to the v2.8.6 and alas, it worked! 

I don't know why it missed the data directory but I think it's an issue worth checking to ensure this folder is inclusive in the latest version. I hope anyone who faces this issue comes across this and solves it asap.

Cheers and happy coding.
