### ISSUE TITLE
[Bug]: Older wdm version causing site creation issues

### ISSUE THREAD

**Issue by hcthoemmes** [jekyll/jekyll#9669]
### Operating System

Windows 10

### Ruby Version

ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x64-mingw-ucrt]

### Jekyll Version

jekyll 4.3.3

### Expected Behavior

On running `jekyll new [sitename]`, all gems should install correctly, and subsequently `bundle exec jekyll serve` should properly open the created site.

### Current Behavior

Bundler throws errors when installing the wdm gem. As of 3 days ago, wdm was updated to 0.2.0. If the version is manually changed in the directory's gemfile, all goes well. This bug report is here to suggest that the default wdm version is changed,

### Relevant log output

```shell
D:\[directory]>jekyll new myblog
Running bundle install in D:/_CODE/_HIGARB/myblog...
  Bundler: Fetching gem metadata from https://rubygems.org/............
  Bundler: Resolving dependencies...
  Bundler: Installing wdm 0.1.1 with native extensionsGem::Ext::BuildError: ERROR: Failed to build gem native extension.  Bundler:
  Bundler: current directory: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/wdm-0.1.1/ext/wdm
  Bundler: C:/Ruby33-x64/bin/ruby.exe extconf.rb
  Bundler: checking for -lkernel32... yes
  Bundler: checking for windows.h... yes
  Bundler: checking for ruby.h... yes
  Bundler: checking for HAVE_RUBY_ENCODING_H... yes
  Bundler: checking for rb_thread_call_without_gvl()... yes
  Bundler: creating Makefile
  Bundler:
  Bundler: current directory: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/wdm-0.1.1/ext/wdm
  Bundler: make DESTDIR\= sitearchdir\=./.gem.20240907-19616-xf6mkg
  Bundler: sitelibdir\=./.gem.20240907-19616-xf6mkg clean
  Bundler: bash.exe: warning: could not find /tmp, please create!
  Bundler:
  Bundler: current directory: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/wdm-0.1.1/ext/wdm
  Bundler: make DESTDIR\= sitearchdir\=./.gem.20240907-19616-xf6mkg
  Bundler: sitelibdir\=./.gem.20240907-19616-xf6mkg
  Bundler: generating wdm_ext-x64-mingw-ucrt.def
  Bundler: bash.exe: warning: could not find /tmp, please create!
  Bundler: compiling entry.c
  Bundler: compiling memory.c
  Bundler: compiling monitor.c
  Bundler: compiling queue.c
  Bundler: compiling rb_change.c
  Bundler: rb_change.c: In function 'extract_absolute_path_from_notification':
  Bundler: rb_change.c:139:5: warning: 'RB_OBJ_TAINT' is deprecated: taintedness turned out
  Bundler: to be a wrong idea. [-Wdeprecated-declarations]
  Bundler: 139 | OBJ_TAINT(path);
  Bundler: | ^~~~~~~~~
  Bundler: In file included from
  Bundler: C:/Ruby33-x64/include/ruby-3.3.0/ruby/internal/core/rstring.h:30,
  Bundler: from
  Bundler: C:/Ruby33-x64/include/ruby-3.3.0/ruby/internal/arithmetic/char.h:29,
  Bundler: from
  Bundler: C:/Ruby33-x64/include/ruby-3.3.0/ruby/internal/arithmetic.h:24,
  Bundler: from C:/Ruby33-x64/include/ruby-3.3.0/ruby/ruby.h:28,
  Bundler: from C:/Ruby33-x64/include/ruby-3.3.0/ruby.h:38,
  Bundler: from wdm.h:22,
  Bundler: from rb_change.c:4:
  Bundler: C:/Ruby33-x64/include/ruby-3.3.0/ruby/internal/fl_type.h:824:1: note: declared
  Bundler: here
  Bundler: 824 | RB_OBJ_TAINT(VALUE obj)
  Bundler: | ^~~~~~~~~~~~
  Bundler: compiling rb_monitor.c
  Bundler: rb_monitor.c: In function 'rb_monitor_run_bang':
  Bundler: rb_monitor.c:509:29: error: implicit declaration of function
  Bundler: 'rb_thread_call_without_gvl' [-Wimplicit-function-declaration]
  Bundler: 509 | waiting_succeeded = rb_thread_call_without_gvl(wait_for_changes,
  Bundler: monitor->process_event, stop_monitoring, monitor);
  Bundler: | ^~~~~~~~~~~~~~~~~~~~~~~~~~
  Bundler: make: *** [Makefile:248: rb_monitor.o] Error 1
  Bundler:
  Bundler: make failed, exit code 2
  Bundler:
  Bundler: Gem files will remain installed in
  Bundler: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/wdm-0.1.1 for inspection.
  Bundler: Results logged to
  Bundler: C:/Ruby33-x64/lib/ruby/gems/3.3.0/extensions/x64-mingw-ucrt/3.3.0/wdm-0.1.1/gem_make.out
  Bundler:
  Bundler: C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  Bundler: C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/ext/builder.rb:51:in `block in
  Bundler: make'
  Bundler: C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/ext/builder.rb:43:in `each'
  Bundler: C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/ext/builder.rb:43:in `make'
  Bundler: C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:42:in
  Bundler: `build'
  Bundler: C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/ext/builder.rb:193:in
  Bundler: `build_extension'
  Bundler: C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/ext/builder.rb:227:in `block
  Bundler: in build_extensions'
  Bundler: C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  Bundler: C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/ext/builder.rb:224:in
  Bundler: `build_extensions'
  Bundler: C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/installer.rb:853:in
  Bundler: `build_extensions'
  Bundler: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/rubygems_gem_installer.rb:109:in
  Bundler: `build_extensions'
  Bundler: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/rubygems_gem_installer.rb:28:in
  Bundler: `install'
  Bundler: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/source/rubygems.rb:205:in
  Bundler: `install'
  Bundler: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/installer/gem_installer.rb:54:in
  Bundler: `install'
  Bundler: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/installer/gem_installer.rb:16:in
  Bundler: `install_from_spec'
  Bundler: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/installer/parallel_installer.rb:132:in
  Bundler: `do_install'
  Bundler: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/installer/parallel_installer.rb:123:in
  Bundler: `block in worker_pool'
  Bundler: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/worker.rb:62:in
  Bundler: `apply_func'
  Bundler: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/worker.rb:57:in
  Bundler: `block in process_queue'
  Bundler: <internal:kernel>:187:in `loop'
  Bundler: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/worker.rb:54:in
  Bundler: `process_queue'
  Bundler: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/worker.rb:90:in
  Bundler: `block (2 levels) in create_threads'
  Bundler:
  Bundler: An error occurred while installing wdm (0.1.1), and Bundler cannot continue.
  Bundler:
  Bundler: In Gemfile:
  Bundler: wdm
```

**Comment by ashmaroli** [comment]
Thanks for reporting, but has already fixed via https://github.com/jekyll/jekyll/commit/3a8b2822f148671214e370e7b4e58f5063dd3462
