### ISSUE TITLE
[Bug]: CSV still not a separate dependency

### ISSUE THREAD

**Issue by rockstorm101** [jekyll/jekyll#9741]
### Operating System

Alpine 3.21

### Ruby Version

Ruby 3.4.1

### Jekyll Version

Jekyll 4.3.4

### Expected Behavior

The command run was: `bundler exec jekyll new myblog`. Expectation was a successful build.

### Current Behavior

I get the error shown as log output. I'm no expert but it seems to be due to missing CSV gem. This dependency was supposed to be added on #9522 but it seems Jekyll 4.3.4 still does not list CSV as a dependency as can be seen [here][1]. Jekyll 4.3.4 is not usable under Ruby 3.4+ as is.

Downgrading to Ruby 3.3.6 worked as expected.

[1]: https://rubygems.org/gems/jekyll

EDIT: To work under Ruby 3.4.1 I had to add both 'csv' and 'base64' gems as extra dependencies.

### Relevant log output

```shell
/usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll.rb:26: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
/usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll.rb:28: warning: csv was loaded from the standard library, but is not part of the default gems starting from Ruby 3.4.0.
You can add csv to your Gemfile or gemspec to silence this warning.
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
/usr/local/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require': cannot load such file -- csv (LoadError)
	from /usr/local/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
	from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll.rb:28:in '<top (required)>'
	from /usr/local/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require'
	from /usr/local/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
	from /usr/local/bundle/gems/jekyll-4.3.4/exe/jekyll:8:in '<top (required)>'
	from /usr/local/bundle/bin/jekyll:25:in 'Kernel#load'
	from /usr/local/bundle/bin/jekyll:25:in '<top (required)>'
	from /usr/local/bundle/gems/bundler-2.6.2/lib/bundler/cli/exec.rb:59:in 'Kernel.load'
	from /usr/local/bundle/gems/bundler-2.6.2/lib/bundler/cli/exec.rb:59:in 'Bundler::CLI::Exec#kernel_load'
	from /usr/local/bundle/gems/bundler-2.6.2/lib/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
	from /usr/local/bundle/gems/bundler-2.6.2/lib/bundler/cli.rb:452:in 'Bundler::CLI#exec'
	from /usr/local/bundle/gems/bundler-2.6.2/lib/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
	from /usr/local/bundle/gems/bundler-2.6.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
	from /usr/local/bundle/gems/bundler-2.6.2/lib/bundler/vendor/thor/lib/thor.rb:538:in 'Bundler::Thor.dispatch'
	from /usr/local/bundle/gems/bundler-2.6.2/lib/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
	from /usr/local/bundle/gems/bundler-2.6.2/lib/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
	from /usr/local/bundle/gems/bundler-2.6.2/lib/bundler/cli.rb:29:in 'Bundler::CLI.start'
	from /usr/local/bundle/gems/bundler-2.6.2/exe/bundle:28:in 'block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.6.2/lib/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
	from /usr/local/bundle/gems/bundler-2.6.2/exe/bundle:20:in '<top (required)>'
	from /usr/local/bundle/gems/bundler-2.6.2/exe/bundler:4:in 'Kernel#load'
	from /usr/local/bundle/gems/bundler-2.6.2/exe/bundler:4:in '<top (required)>'
	from /usr/local/bundle/bin/bundler:25:in 'Kernel#load'
	from /usr/local/bundle/bin/bundler:25:in '<main>'
```

**Comment by CookiePLMonster** [comment]
This is being worked on here: https://github.com/jekyll/jekyll/pull/9736

**Comment by Laguna1989** [comment]
Same issue on my system. Any update on this one?

**Comment by akingscote** [comment]
FWIW, i just added 
```
gem "csv"
gem "base64"
```
to my [Gemfile ](https://github.com/akingscote/akingscote.github.io/blob/main/Gemfile#L7)to get my jekyll app building 👍

**Comment by ashmaroli** [comment]
Resolved via v4.4.0

**Comment by yous** [comment]
Jekyll 3.10.0 also lacks `gem "base64"`.

- https://github.com/yous/whiteglass/actions/runs/13404698591/job/37442420017

<details><summary>bundle exec jekyll build</summary>

```
/home/runner/work/whiteglass/whiteglass/vendor/bundle/ruby/3.4.0/gems/jekyll-3.10.0/lib/jekyll.rb:26: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
/home/runner/work/whiteglass/whiteglass/vendor/bundle/ruby/3.4.0/gems/safe_yaml-1.0.5/lib/safe_yaml/transform.rb:1: warning: base64 was loaded from the standard library, but is not part of the default gems starting from Ruby 3.4.0.
You can add base64 to your Gemfile or gemspec to silence this warning.
bundler: failed to load command: jekyll (/home/runner/work/whiteglass/whiteglass/vendor/bundle/ruby/3.4.0/bin/jekyll)
/opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require': cannot load such file -- base64 (LoadError)
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
	from /home/runner/work/whiteglass/whiteglass/vendor/bundle/ruby/3.4.0/gems/safe_yaml-1.0.5/lib/safe_yaml/transform.rb:1:in '<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
	from /home/runner/work/whiteglass/whiteglass/vendor/bundle/ruby/3.4.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:22:in '<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
	from /home/runner/work/whiteglass/whiteglass/vendor/bundle/ruby/3.4.0/gems/jekyll-3.10.0/lib/jekyll.rb:34:in '<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
	from /home/runner/work/whiteglass/whiteglass/vendor/bundle/ruby/3.4.0/gems/jekyll-3.10.0/exe/jekyll:8:in '<top (required)>'
	from /home/runner/work/whiteglass/whiteglass/vendor/bundle/ruby/3.4.0/bin/jekyll:25:in 'Kernel#load'
	from /home/runner/work/whiteglass/whiteglass/vendor/bundle/ruby/3.4.0/bin/jekyll:25:in '<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundler/cli/exec.rb:59:in 'Kernel.load'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundler/cli/exec.rb:59:in 'Bundler::CLI::Exec#kernel_load'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundler/cli.rb:452:in 'Bundler::CLI#exec'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor.rb:538:in 'Bundler::Thor.dispatch'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundler/cli.rb:29:in 'Bundler::CLI.start'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/gems/3.4.0/gems/bundler-2.6.2/exe/bundle:28:in 'block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/3.4.0/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/lib/ruby/gems/3.4.0/gems/bundler-2.6.2/exe/bundle:20:in '<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/bin/bundle:25:in 'Kernel#load'
	from /opt/hostedtoolcache/Ruby/3.4.2/x64/bin/bundle:25:in '<main>'
Error: Process completed with exit code 1.
```

</details>

**Comment by ashmaroli** [comment]
Pinging @parkr regarding Ruby incompatibility with v3.10

**Comment by ashmaroli** [comment]
> I had to add these gems to the Gemfile to make it work (Jekyll 3.9.4, Ruby 3.4.4)

We haven't exactly ported the compatibility to the 3.x series. Please open a new issue ticket.
